### ISSUE TITLE
Unhandled rejection Error

### ISSUE THREAD

**Issue by R-obert** [npm/cli#1075]
Hello,

try "npm ls @ionic" and you will see an error message from npm itself:

```
$ npm -version
6.9.0
$ npm ls @ionic
Unhandled rejection Error: Invalid tag name "@ionic": Tags may not have any characters that encodeURIComponent encodes.
.
.
.
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
```

**Comment by ptvandi** [comment]
@R-obert I believe this error should probably be handled, but my understanding from the docs is that `npm ls` expects a package name, not just the scope. 

In my case, I was trying to track down `@emotion` to determine why it was getting bundled in one of my chunks. I came across this error because I was running `npm ls @emotion`. Adding the package name `npm ls @emotion/stylis` resolved the error for me.
