### ISSUE TITLE
[BUG] Error Installing "Forever"

### ISSUE THREAD

**Issue by umair-mirza** [npm/cli#1261]
# What / Why

Node version: 12.16.1
Npm version: 6.14.5

Here's the error I get when I install Forever with the following command:
`npm install -g forever`

Error:
`npm WARN deprecated path-is-absolute@2.0.0: This package is no longer relevant as Node.js 0.12 is unmaintained.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.`

## When

When I install Forever with the following command:
`npm install -g forever`

**Comment by ljharb** [comment]
That's not an error, that's a warning.

**Comment by shadowspawn** [comment]
This is a warning related to the package dependencies of `forever` and not an issue with `npm`, so you would be better to report the issue there.

It looks like it has been fixed in the `forever` project, but not released as yet: https://github.com/foreversd/forever/commit/437ca4a207f9963a3ef84588772035392cd96365
