### ISSUE TITLE
Registry and Replicate show different versions

### ISSUE THREAD

**Issue by gelpenaddict** [npm/cli#1656]
### Current Behavior:
Replicate and registry .npmjs.com show different package versions.

### Expected Behavior:
Replicate and registry .npmjs.com show the same package versions.

### Steps To Reproduce:

```
> npm view @luma.gl/constants --registry https://registry.npmjs.com/ 
@luma.gl/constants@8.2.0 | MIT | deps: none | versions: 91
```

```
> npm view @luma.gl/constants --registry https://replicate.npmjs.com/
@luma.gl/constants@8.1.3 | MIT | deps: none | versions: 90
```
This has happened with other packages too.

### Environment:
- OS: MacOS 10.14.2
- NPM: 6.13.6

**Comment by darcyclarke** [comment]
I'm closing this since we are only able to support issues that relate to the npm CLI itself. 

If you're experiencing issues with the npm registry/website you can contact support at https://www.npmjs.com/support OR, if you have feedback about the registry/website, you can add that to our new https://github.com/npm/feedback repo.
