### ISSUE TITLE
TypeError: URL is not a constructor in replace-info.js 

### ISSUE THREAD

**Issue by ewrayjohnson** [npm/cli#1658]
_This occurs with Nodejs 14.7.0_
On line 14 of replace-info.js an attempt is made to construct a `new URL(...)`, however URL is not a constructor.
One fix is to change line 1 to:
`const URL = require('url').URL;`
Another (possibly better) option to fix is to replace `new URL` with `URL.parse`

**Comment by aduh95** [comment]
Or just remove line 1:

https://github.com/npm/cli/blob/ad8fe71a4f8c6d717375a6c699aaa00f11521adf/lib/utils/replace-info.js#L1

Here `URL` refers to the `url` built-in module rather than the global `URL` object. That's unfortunate, the `url` module is not even used in this module. The following code fails because of that:

https://github.com/npm/cli/blob/ad8fe71a4f8c6d717375a6c699aaa00f11521adf/lib/utils/replace-info.js#L14-L15

The WHATWG `URL` object is [globally available on Node.js](https://nodejs.org/dist/latest/docs/api/url.html#url_class_url) since Node.js 10.0.0, although you still can use `require('url').URL` it is not a requirement and refers to the same object.

**Comment by claudiahdz** [comment]
Thank you for the catch, we'll make the proper changes considering we still have to support Node 6 on npm v6. The fix will be shipped next week.
