### ISSUE TITLE
[Question] documentation for phase 1 of workspace support in npm 7?

### ISSUE THREAD

**Issue by orzechowskid** [npm/cli#1752]
### Current Behavior:
running `npm install` in my top-level workspace does not seem to create a node_modules directory in my nested workspace.

### Expected Behavior:
not sure!  I am using `npm@next-7`, in which "phase 1" of workspace support has been added according to [this blog post](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major), but I'm unable to find documentation as to what specifically has been done and what is still outstanding.  Being pointed to documentation (or being told that none exists yet!) is the main goal of this issue.

### Steps To Reproduce:
1. create a test directory: `$ mkdir root; cd root`
2. create a root package.json file and add a dependency: `$ npm init -y; npm install --save lodash`
3. create a directory for a nested workspace: `$ mkdir -p packages/foo`
4. add workspace support to the root package.json: `"workspaces":  { "packages": [ "packages/*" ] },` as described by [the RFC](https://github.com/npm/rfcs/blob/latest/accepted/0026-workspaces.md)
5. create a package.json file for the nested workspace and add a dependency: `$ cd packages/foo ; npm init -y; npm install --save express; cd ../..`
6. remove all node_modules directories: `$ find . -name 'node_modules' | xargs rm -rf`
7. run `npm install` in the root workspace: `$ npm install`

at this point, no `node_modules` directory is present in the nested workspace.

### Environment:

- OS: Ubuntu 20.04.1
- Node: v14.9.0
- npm: 7.0.0-beta.8

thanks for any help you can provide!

**Comment by KilianKilmister** [comment]
I discovered it while debugging something in Arborist: the paths added to the `namespaces` field (takes standard globs) will be symlinked to the root `node_modules` folder, and commands like `npm install` run in the root package will cascade through the workspace packages.

that's what i know so far. theres probalby more

**Comment by orzechowskid** [comment]
that's what the RFC says should happen, yes.  and that seems to be the case if package-lock.json in the root workspace contains a `packages` field.  following the steps above does not create such a field.

**Comment by KilianKilmister** [comment]
@orzechowskid you have to check in `node-modules/.package-lock.json`. it's not in the other one

**Comment by ruyadorno** [comment]
hi @orzechowskid! In the [RFC](https://github.com/npm/rfcs/blob/latest/accepted/0026-workspaces.md) page you linked originally there is an example showing the expected behavior (installing deps of workspaces into top-level `node_modules` folder) which is actually quite similar to your example 😊 

Here's the result example as taken from the RFC, ([you can see it here in its context](https://github.com/npm/rfcs/blob/latest/accepted/0026-workspaces.md#expanding-on-symlinking-structure-and-package-lock-file-shape)):
```
$ tree
.
├── package-lock.json
├── node_modules
│   ├── lodash
│   ├── libnpmutil -> ./core/libnpmutil
│   ├── workspace-a -> ./packages/workspace-a
│   ├── workspace-b -> ./packages/workspace-b
│   ├── workspace-c -> ./packages/workspace-c
│   └── react
├── core
│   └── libnpmutil
└── packages
    ├── workspace-a
    ├── workspace-b
    └─ worspace-c
        └── node_modules
            └── workspace-b@1.0.0
```

In the example above, it's possible to have a `./core/libnpmutil/index.js` that contains a `require('lodash')` (so that you can `cd ./core/libnpmutil` and `node index.js` from there) and that `require('lodash')` is going to work as expected, this is possible due to [Node.js own module resolution](https://nodejs.org/dist/latest-v14.x/docs/api/modules.html#modules_all_together) that you can dig more in case you're curious about it.

Let me know if this is helpful enough and feel free to close the issue if that's the case 😄

**Comment by peterjuras** [comment]
I ran into a similar issue and I think it is related to #1762. The new npm configuration that contains the workspaces field appears to be ignored for me if there is an existing lockfile and the issue is that you are running `npm install lodash` before adding a workspaces field. (Although I consider this a bug)

I got npm@7 to correctly create a workspace by first ensuring that all folders & package.json files were configured correctly, removing all node_modules & package-lock.json files and then running npm install in the workspace root.

**Comment by orzechowskid** [comment]
I think it was a mistake on my part to include an example in my original report when all I was really looking for is documentation.  I was attempting to follow the issue template and tried to make clear what I was asking for, but it seems like I did not do a very good job and for that I apologize.

if I can rephrase:  how do I find out which features of npm workspaces are supported in the latest npm 7 betas and which are not, so I can file bugs against features that are supposed to work and be patient regarding features which are not?

**Comment by ruyadorno** [comment]
> if I can rephrase: how do I find out which features of npm workspaces are supported in the latest npm 7 betas and which are not, so I can file bugs against features that are supposed to work and be patient regarding features which are not?

oohh I see 😅 sorry I was really confused by the original post and replies.

so the one important thing to note here is that we still have some test and documentation work to wrap up **after** we're done with the beta 😁 so for now the best documentation available on what is supported really is that approved RFC that you linked originally. Anything not in there you may assume to not be supported for now (note: we already have an ongoing follow up RFC open to get feedback on implementing more workspaces features).

Hope this is more helpful now! 😄 Thanks for reaching out and helping us clarify that!

**Comment by orzechowskid** [comment]
ahh, that makes sense, thank you.  I will stick to what's in the RFC for now, and follow along with discussions in progress.  thanks again.

**Comment by mccxiv** [comment]
For people reaching this via search engine, [this RFC](https://github.com/npm/rfcs/blob/latest/implemented/0026-workspaces.md) is the only documentation available at the moment...

**Comment by limal** [comment]
I fell like the current documentation (RFC) is really lacking in real-life examples. If you're stuck like I was yesterday you can learn on my misconception of the npm's workspaces (they are not like yarn workspaces at all) and how to actually use them in my article [Simplify your monorepo with npm 7 workspaces ](https://dev.to/limal/simplify-your-monorepo-with-npm-7-workspaces-5gmj).

**Comment by J-Rojas** [comment]
Hmm so are nested workspaces currently supported? Is this feature currently tracked somewhere? I can confirm nested workspaces are not being hoisted into the root workspace or being added to the nested workspaces node_modules.

**Comment by ruyadorno** [comment]
> Hmm so are nested workspaces currently supported?

Not really.

> Is this feature currently tracked somewhere?

As of today I don't think so, it might be a good idea to poke the rest of the team about it over at https://github.com/npm/feedback/discussions to make sure it gets prioritized 😄 I know for sure it has been part of the discussion since we started working in the first phase of workspaces support but it's just low in terms of priorities compared to other features we still have to work on but rest assured it will not be forgotten.

The next priority for the cli in terms of workspaces is to [implement the workflows for working with workspaces](https://github.com/npm/rfcs/pull/117) and that is being tracked over at https://github.com/npm/roadmap/projects/1 as [CLI: workspaces phase 2](https://github.com/npm/roadmap/issues/30) (you can keep an eye in that roadmap in order to track what's in the radar for both registry and cli teams) 😊

**Comment by ruyadorno** [comment]
@limal thank you so much for that article! it's the kind of awesome content I love to see the community coming up with 😄

**Comment by ruyadorno** [comment]
Since I noticed there might be people still landing in this issue, let me leave some references to the official docs (which have been long been available since the original issue was open):
- `npm help workspaces` (for cli docs)
- `npm help workspaces --viewer=browser` render the cli docs in a browser (no internet required)
- Website docs: https://docs.npmjs.com/cli/v7/using-npm/workspaces

And here are some tutorial/guides from the community:
- [Simplify your monorepo with npm 7 workspaces ](https://dev.to/limal/simplify-your-monorepo-with-npm-7-workspaces-5gmj)
- [What You Need To Know About npm Workspaces ](https://dev.to/ruanmartinelli/what-you-need-to-know-about-npm-workspaces-5fd4)
- [npm v7 highlights](https://speakerdeck.com/ruyadorno/npm-v7-highlights)
