### ISSUE TITLE
[BUG] Do not default `name` prop in `package-lock.json` to dir name

### ISSUE THREAD

**Issue by valtlai** [npm/cli#1767]
### Current Behavior:
If there’s no the `name` property in `package.json`, the `name` property in `package-lock.json` defaults to the name of the parent directory.

### Expected Behavior:
If there’s no the `name` property in `package.json`, omit it from `package-lock.json` too.

I’m not sure if that was an intentional change, but I think the property should not default to the directory name, because the `name` property is sometimes useless (e.g., in a non-package repo) and it’s annoying that the name of the parent directory affects to the lockfile.

### Steps To Reproduce:
1) Create a `package.json` without the `name` property.
2) See the `name` property of `package-lock.json` containing the name of the parent directory.

### Environment:
- OS: MacOS 10.15.6
- Node: 14.8.0
- npm: 7.0.0-beta.9

**Comment by ruyadorno** [comment]
Hi @valtlai this is indeed an intended change, it's useful for us to make sure all nodes in the trees have names when loading a virtual tree (a tree built using only the package-lock file) - internally to [`@npmcli/arborist`](https://github.com/npm/arborist/) a tree node (even the root) name defaults to its pathname, so that's the reason why it gets set in the package-lock file (since this is supposed to be a best-effort-complete representation of the current installed tree).

I see how this may be annoying from an user point of view when peaking at it but it's actually quite useful 😊 

Thanks for the reports so far! We appreciate the help with testing the beta! 😄

**Comment by valtlai** [comment]
@ruyadorno, thank you for the information. I’ll just add the `name` property in `package.json` to make the package name stable. 😁
