### ISSUE TITLE
CommandFailed: npm install --unsafe-perm 

### ISSUE THREAD

**Issue by BruceLing** [npm/cli#1773]
ERROR: Command failed: npm install --unsafe-perm
npm WARN deprecated bson@1.0.9: Fixed a critical issue with BSON serialization documented in CVE-2019-2391, see https://bit.ly/2KcpXdo for more details
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm ERR! Linux 5.4.0-42-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

**Comment by darcyclarke** [comment]
Please use our standard bug template. I'm closing this for now. 

**Quick note though:** we do not support `npm@3.x` & node `8` has been out of maintenance/end-of-life since the beginning of the year. I'd suggest updating both & also updating your dependencies as you're receiving numerous deprecation warnings from old versions of packages.
