### ISSUE TITLE
npm publish corrupts README.md file on npmjs.com 

### ISSUE THREAD

**Issue by paboulos** [npm/cli#1802]
### Current Behavior:
The URL https://www.npmjs.com/package/ccdir and readme is unreadable. It has question marks inserted all over the page.
Readme is fine on Github https://github.com/paboulos/ccdir#readme

### Expected Behavior:
Readme should not be distorted after a publish.

### Steps To Reproduce:
1. Run npm publish
2. From web browser open URL https://www.npmjs.com/package/ccdir
3. See readme.

### Environment:
- OS: Win 10
- Node: 10.16.2
- npm: 6.14.5

**Comment by shadowspawn** [comment]
I cloned your repo and it looks like `README.md` is saved in UTF-16. My guess is GitHub supports this, but npmjs does not. 

I expect if you resave the file in UTF-8 (effectively the same as ascii since the file is ordinary characters) and then it will display as expected on npmjs when you publish a new version.

**Comment by paboulos** [comment]
Yes, resolved and closed.
