### ISSUE TITLE
[BUG] npm install enters an infinite loop on workspace

### ISSUE THREAD

**Issue by otakustay** [npm/cli#1843]
### Current Behavior:

`npm install` enters an infinite loop and cannot be interrupted via `CTRL+C`.

### Expected Behavior:

install should finish successfully.

### Steps To Reproduce:

Using repo: https://github.com/otakustay/npm-issue/tree/npm-7-infinite-loop

Run `npm install --verbose` in it.

### Environment:

- npm: 7.0.0-beta.11
- node: v14.7.0
- OS: macOS 10.15.6

**Comment by ruyadorno** [comment]
Hi @otakustay thank you so much for the report and the very handy reproduction repo! :smile: The infinite loop issue have now been fixed in `v7.0.0-beta.13` - it turns out that the linked workspaces have conflicting `peerDependencies` so now npm7 will properly display a nice error message showing up which peer dependency have the version conflicts so that you can fix it in your local project before installing again 😊 As usual you can get the latest beta version with:

```
npm i -g npm@next-7
```

Let us know if you find more issues and thanks again!
