### ISSUE TITLE
[BUG] Please clarify test/fixtures/third-party.md

### ISSUE THREAD

**Issue by voxik** [npm/cli#1912]
I would appreciate if the test/fixtures/third-party.md, which was introduced by 5e75850bc6258080de4e6c9cb5add378c2b9581f provided more context about the license. Because it is not clear to me what the license actually applies to. Looking at the content of scoped-underscore-1.3.1.tgz it contains completely different license. So I wonder what is actually covered by the third-party.md. Why the file was introduced?

Please note, that the license itself might not be considered "open source", because it doesn't permit modification.

**Comment by sutula** [comment]
@darcyclarke I question removing the "Bug" label.  Though the original post was posed as a request for information, the underlying issue is that license text was introduced into the project that appears to be misleading.  I would maintain this to be a project defect.

**Comment by isaacs** [comment]
I dug up the conversation with our legal team that led to the introduction of this license statement.

What follows is my understanding.  I am not a lawyer, but I was the one who added this file to the repo, and hopefully my layperson's account of the situation reduces confusion rather than adding to it.

Yes, you are correct, this is not the Underscore license.  Underscore (which npm bundles in its repository as a test fixture) includes code adapted from the JO abstract operation, which is copyright Ecma International.  The license on the JO abstract operation requires that the license here be included with all copies of JO or derivative works (which underscore's implementation arguably is).  Since the Underscore license does _not_ include this license, there was a concern that we'd be violating the Ecma International license on JO if we include Underscore in our repository.

It is not our job to police the world's licenses, and it may well be that Underscore is just fine in what they're doing for some reason, but as companies tend to prefer to be on the safe side of any legal hazards, we decided that adding the missing Ecma International license was less disruptive and less effort than going through and removing all uses of the Underscore test fixture.

Therefor, no, it is not in fact misleading to have this license.  It is (arguably) required when including the version of Underscore that we do, since Underscore includes a derivative of JO and does not include the JO license.  The license on _underscore itself_ is found in the usual place, as a file named `LICENSE` in the root of the bundled artifact.

JO and Underscore are not included with npm's "normal" distribution, so this is only relevant to use of the repository for testing and development of the npm cli itself.

I hope that this answers the question.  I'd be fine with a pull request that removes all use of the Underscore test fixture, but it's not a priority for me.  After all, in the opinion of the GitHub and Microsoft lawyers who were involved with npm, Inc.'s acquisition, this file is fine, and they know much more about these things than I do, so I defer to their judgement.
