### ISSUE TITLE
CDN for private packages

### ISSUE THREAD

**Issue by dharmatv** [npm/cli#1926]
- OS: Ubuntu 18.04
- Node: v10.15.3
- npm: 6.14.8

How to serve CDN for Private packages.
Is there any possibilities to get this
Please help me, anyone, out of this

**Comment by darcyclarke** [comment]
Hey @dharmatv. I'm sorry you're having issues. Please use our BUG template & fill out the fields for your current & expected experience so that we can properly help you. Unfortunately, based on the information provided, I can't properly help triage this bug, so I'll be closing this for now. Please feel free to open a new issue with more information if you think you've found a problem with the npm CLI.
