### ISSUE TITLE
[BUG] npm7 workspaces, dependencies specified as git are not properly linked

### ISSUE THREAD

**Issue by jsg2021** [npm/cli#1942]
### Current Behavior:
git-dependencies do not get deduped in workspaces. ex:
```
./a
./a/node_modules
./a/node_modules/b
./a/node_modules/c
./b
./b/node_modules
./b/node_modules/c
./c
./node_modules
./node_modules/esm
./node_modules/c -> ./c
./node_modules/b -> ./b
./node_modules/a -> ./a
```

### Expected Behavior:
git-dependencies in the workspace get deduped/linked
ex:
```
./a
./b
./c
./node_modules
./node_modules/esm
./node_modules/c -> ./c
./node_modules/b -> ./b
./node_modules/a -> ./a
```

### Steps To Reproduce:
Clone https://github.com/jsg2021/npm7-workspace-test 
Install

### Environment:
- OS: Fedora 32
- Node: 14.13.0
- npm: 7.0.0-rc.4

**Comment by jsg2021** [comment]
This is still occurring with the final 7.0.0

**Comment by jsg2021** [comment]
Also in 7.0.8

**Comment by jsg2021** [comment]
Still occurring on 7.0.13

**Comment by ljharb** [comment]
cc @ruyadorno for workspaces triage

**Comment by ruyadorno** [comment]
thanks @ljharb and sorry about the delay @jsg2021 😅 

I'm not sure **how** the example project was originally set up but there's one mismatch with the expectations from the npm cli in order to properly set up the workspaces structure. In order to beneift from symlinking the proper available workspaces, each of the workspaces consuming another one should list a valid semver range and the installer will make sure to prioritize workspaces over installing from the registry.

Concretely that means that we can get it working by applying the following changes:

#### In repo ./a:
```patch
diff --git a/package.json b/package.json
index 289bed3..7956fb3 100644
--- a/package.json
+++ b/package.json
@@ -7,7 +7,7 @@
     "url": "https://github.com/jsg2021/npm7-workspace-test-a.git"
   },
   "dependencies": {
-    "b": "github:jsg2021/npm7-workspace-test-b#master",
+    "b": "^1.0.0",
     "esm": "^3.2.25"
   }
 }
```

#### In repo ./b:

```patch
diff --git a/package.json b/package.json
index ab2780b..e856382 100644
--- a/package.json
+++ b/package.json
@@ -7,7 +7,7 @@
     "url": "https://github.com/jsg2021/npm7-workspace-test-b.git"
   },
   "dependencies": {
-    "c": "jsg2021/npm7-workspace-test-c",
+    "c": "^1.0.0",
     "esm": "^3.2.25"
   }
 }
```

And running `npm install` again from the root 😊 I just gave it a try here and it seems to work just fine:

<img width="899" alt="Screen shot comparing the results of npm install after patching each workspace package.json" src="https://user-images.githubusercontent.com/220900/103576750-9c111b00-4ea1-11eb-9cac-5692c38f5d00.png">

Please let me know in case there's something else I'm missing here 😅 we can always reopen the issue later.

**Comment by jsg2021** [comment]
@ruyadorno  This is an example of a project not using the registry for project modules. They only exist on github. Semvers won't necessarily exist. That is the bug. This project exists privately and solely in git. I should be able to specify a git dependency with or without a hash and the workspace resolve correctly.

**Comment by jsg2021** [comment]
Also, this is a workspace shaped like a mono-repo, but each dep is its own repo.

**Comment by jsg2021** [comment]
@ruyadorno @ljharb this should not be closed.

**Comment by ruyadorno** [comment]
@jsg2021 Thanks for the feedback! I get what was your intention here but unfortunately that's just outside of the scope of how workspaces was originally designed (which was to support semver ranges only).

You're more than welcome to come over to our [RFCs repo](https://github.com/npm/rfcs) and propose new ways to extend that support either by starting a Discussion there or by sending a RFC PR 😊 You could propose adding support to git/github specs and the team can follow along in the discussion with the broader community.

Thanks again, I appreciate you taking the time to bringing this issue over to our attention!

**Comment by jsg2021** [comment]
@ruyadorno you don't see a problem with only supporting a subset of version specifiers that npm supports for workspaces?

**Comment by jsg2021** [comment]
The fact that it works 95% of the way... feels like it's a bug. The only problem is the duplication/reify'd modules that exist as links... Makes me think its just a matter of saying the local link satisfies the git version spec... which, I would think it should?

**Comment by ruyadorno** [comment]
> @ruyadorno you don't see a problem with only supporting a subset of version specifiers that npm supports for workspaces?

Yes 👍  I do see how that can be a problem!

That's why I'm suggesting we take it to the RFCs discussions 😊 Given that it was not in the initial design I'll def need help from the team (and other collaborators such as @ljharb) to better understand how we can support different version specifiers.

If you prefer I can take it from here and start the discussion there (personally I prefer leaving room for folks to participate and champion their ideas/suggestions/etc, the RFC process is a good oportunity to engage with the rest of the team, we have weekly meetings over Zoom that are also streamed to Youtube). I'll try and make sure it gets in the agenda for tomorrow's meeting (2pm EST time) and will make sure you get notified with the info on how to join the call.

Thanks again! 😄

**Comment by jsg2021** [comment]
@ruyadorno thank you! I'll help where I can, but I'm not sure I'm completely ready to champion an RFC. :sweat_smile: I'm in central time, so a 2 pm EST call should be doable for me. I would be very interested in joining/watching.

**Comment by ruyadorno** [comment]
There we go: https://github.com/npm/rfcs/issues/301 😄

**Comment by jsg2021** [comment]
Thank you :)

**Comment by ruyadorno** [comment]
@jsg2021 here are the info on how to join the call today: https://github.com/npm/rfcs/issues/303
