### ISSUE TITLE
[BUG] npm outdated doesn't work in workspaces

### ISSUE THREAD

**Issue by justinfagnani** [npm/cli#2032]
### Current Behavior:
Running `npm outdated` in a workspace package results in a listing of all dependencies with a current version of `MISSING`.

### Expected Behavior:
`npm outdated` will show the current installed version of dependencies hoisted to the workspace root.

### Steps To Reproduce:
1. Create a workspace
2. Add a sub-package with dependencies 
3. Run `npm i` in the root of the workspace
4. Change directories into the sub-package
5. Run `npm outdated`

### Environment:
- OS: macOS
- Node: v15.0.1
- npm: 7.0.5

**Comment by vp2177** [comment]
Just wanted to add, that `npm outdated` also doesn't work in the root.
While it doesn't list packages as `MISSING`, it also doesn't check dependencies of packages in workspaces, but apparently only the dependencies directly in `package.json` in the root.

- npm: 7.3.0

**Comment by darcyclarke** [comment]
If you're looking to run `npm outdated` against the entire tree, utilize `npm outdated --all`; Unfortunately, today - we're still flushing out the details of running commands inside/against workspaces over on our RFCs repo (ref. [`Workspace v2`](https://github.com/npm/rfcs/pull/117))

**Comment by ruyadorno** [comment]
Starting from **npm@7.14.0** `npm outdated` now includes results for direct dependencies of workspaces by default 🎉 

They're listed in the "Depended by" column as `<workspace-name>@<workspace-version>` that gets a highlight color associated to workspaces, aiming to make it easier to identify them. This same highlight color is also used in `npm ls` and a few other commands.

**Comment by glen-84** [comment]
@ruyadorno,

This issue should not have been closed. Running `npm outdated` in a workspace still does not work. It only works from the root of the project.

**Comment by ruyadorno** [comment]
hi @glen-84 thanks for the comment, it will help me clarify some of the details of the current **npm workspaces** support.

In order to filter commands to only a single workspace, the syntax/workflow we have in place today is to execute commands from the project root and point to what workspace you want to filter for using the `-w` config, here's a quick example, given a workspace structure of:

```
.
+-- package.json
`-- packages
   +-- a
   |   `-- package.json
   `-- b
       `-- package.json
```

In order to run **outdated** showing only the results of outdated dependencies of workspace **a**, the syntax is: 

- `npm outdated -w a` (executed from the project root)

This syntax is also demonstrated in the context of adding new dependencies to a workspace or running commands in our "using workspaces" docs page: https://docs.npmjs.com/cli/v7/using-npm/workspaces

> Of course `npm outdated` is a special command given that it now also highlights and display results for workspace dependencies even when run with no arguments from the project root but this same filter syntax is used consistently across all the other npm top-level commands.

⚠️ **NOTE:** With that in mind, please note that we currently have a proposal to enable the same behavior of filtering results of a workspace when changing directory to that workspace as part of our RFC program to discuss new features, you can follow the progress and participate over here: https://github.com/npm/rfcs/pull/343

**Comment by glen-84** [comment]
@ruyadorno,

Thanks for the reply. I am aware of this, I was just mentioning that the issue reported in the OP has not yet been fixed – i.e. if you run the same command now, you still get invalid output. Yes, it may be fixed via https://github.com/npm/rfcs/pull/343 in future, but today users will still see confusing output, which may be enough reason to keep this issue open. It would be a different story if the command just printed "Command not supported inside a workspace; please run it from the project root directory.", but that's not the case.
