### ISSUE TITLE
Cannot install private github repository with https

### ISSUE THREAD

**Issue by bencergazda** [npm/cli#2054]
`npm install --verbose` with package.json containing

```
"dependencies": {
    "@SOME_ORG/SOME_PRIVATE_REPO": "git+https://{token}:x-oauth-basic@github.com/SOME_ORG/SOME_PRIVATE_REPO.git"
}
```

### Current Behavior:

```
...
npm http fetch GET 404 https://codeload.github.com/SOME_ORG/SOME_PRIVATE_REPO/tar.gz/[commit_hash] 323ms
...
npm info ok 
```

It uses SSH to connect, and not the given token.
- if no SSH is configured, it fails to install the repo _even if the token is valid_
- if SSH is configured, it installs the repo _even if the token is invalid_

### Expected Behavior:

It should use the credentials from the package URL. It should
- install the package with the given token, _even is SSH is not configured_
- if the given token is invalid, throw `npm ERR! remote: Invalid username or password.` error even _if it could use SSH_

It works as expected with npm@6.14.8

### Steps To Reproduce:

1. `npm install -g npm@7`
2. `npm install`
3. you should see the current behavior
4. `npm install -g npm@6`
5. `npm install`
6. it should work OK

### Environment:

- OS: Ubuntu 18.04.5 and Mac OS 10.15.7
- Node: 15.0.1
- npm: 7.0.5

**Comment by isaacs** [comment]
The change in npm/pacote#61 is the first half of this.  It will tell pacote to use git+https and _not_ fall back to ssh, if https auth is provided.  It will also use git+https as the `resolved` value in these cases.

The second part of the change will be fixed in @npmcli/arborist, by having it store git+https in the package{,-lock}.json files (instead of the shortcut or git+ssh) for known hosts when https auth is present.

**Comment by bencergazda** [comment]
Works great, thank you!

**Comment by pyon123** [comment]
@isaacs @bencergazda I am having the exactly same issue, but not sure how to solve this. would you like to explain in more detail?
