### ISSUE TITLE
[BUG] custom git user not being respected when installing from GitHub private org

### ISSUE THREAD

**Issue by privatenumber** [npm/cli#2091]
### Current Behavior:

Although I specify a different git user in `npm install` from GitHub, the `git ls-remote` always uses the user `git` and fails.

I believe I am given a different git user because this is a private org with enterprise authentication (Single-sign on / SSO).

### Expected Behavior:

For the `git ls-remote` to use the user I passed in.

### Steps To Reproduce:

```
➜  my-repo git:(master) ✗ npm i git+ssh://org-50000000@github.com:my-sso-org/my-repo.git
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/my-sso-org/my-repo.git
npm ERR! ERROR: This repository requires SSH certificate authentication. Contact the owner to receive a certificate.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/privatenumber/.npm/_logs/2020-10-30T19_50_52_865Z-debug.log
```

Notice I specified the user `org-50000000`, but the `git ls-remote` is using the user `git`.

If I run the command directly with the correct git user, it works fine.

### Environment:

OS: macOS 10.15.7
Node: 12.18.2
npm: 6.14.5

and I also checked that this was a bug in:

Node: 15.0.1
npm: 7.0.3

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
