### ISSUE TITLE
inconsistent handling of .npmignore between v6 an v7

### ISSUE THREAD

**Issue by gizero** [npm/cli#2126]
With a `.npmignore` consisting of the following patterns:

```
*
!dist/
``` 

I noticed that `v6` and `v7` behave differently. `npm pack --dry-run` from `v6` includes the content of `dist/` in the package while the same command from `v7` doesn't.

Digging a bit and bisecting the history led to blaming commit b9bc4f040 for such a change.

Reading the docs and comparing with how git handles `.gitignore` made me a little bit confused about the whole thing. Still, I believe `npm` itself changed its behaviour and this could lead to breakage. Was this somewhat intentional but did not get documented anywhere or should we need to address it as a bug?

### Current Behavior (v7):

```
$ cat .npmignore
*
!dist/
```
```
$ npm --version
7.0.3
```
```
$ npm pack --dry-run
npm notice
npm notice 📦  @fw-notifhub/notifhub@0.2.1
npm notice === Tarball Contents ===
npm notice 924B README.md
npm notice 36B  index.js
npm notice 866B package.json
npm notice === Tarball Details ===
npm notice name:          @fw-notifhub/notifhub
npm notice version:       0.2.1
npm notice filename:      @fw-notifhub/notifhub-0.2.1.tgz
npm notice package size:  998 B
npm notice unpacked size: 1.8 kB
npm notice shasum:        55321c3342a01855d0f06dc4a5e055b503b33e50
npm notice integrity:     sha512-hHtIOSQ4Wtn6a[...]dBCS7qMi/YQgQ==
npm notice total files:   3
npm notice
fw-notifhub-notifhub-0.2.1.tgz
```

Notice that `dist/index.js` is not included.

### Previous Behavior (v6):

```
$ npm --version
6.14.8
```
```
$ npm pack --dry-run
npm notice
npm notice 📦  @fw-notifhub/notifhub@0.2.1
npm notice === Tarball Contents ===
npm notice 5.0kB dist/index.js
npm notice 36B   index.js
npm notice 866B  package.json
npm notice 924B  README.md
npm notice === Tarball Details ===
npm notice name:          @fw-notifhub/notifhub
npm notice version:       0.2.1
npm notice filename:      fw-notifhub-notifhub-0.2.1.tgz
npm notice package size:  2.5 kB
npm notice unpacked size: 6.8 kB
npm notice shasum:        ba465bcad40d58317e3106c9c0536617febd22f0
npm notice integrity:     sha512-9/GHB/E4q5140[...]aSjULPcewCNdA==
npm notice total files:   4
npm notice
fw-notifhub-notifhub-0.2.1.tgz
```

Here `dist/index.js` ends up into the package.

**Comment by isaacs** [comment]
This is actually a case where npm v7 came _into_ alignment with how `.gitignore` files are handled.

Because you're ignoring `*`, and `*` does not contain a `/` character anywhere within it, that will _also_ match files whose basenames match `*` within directories, even within directories that are included.

Observe:

```
$ tree
.
├── .gitignore
├── dist
│  └── index.js
├── index.js
├── package.json
└── README.md

$ cat .gitignore
*
!dist/

$ git add dist/index.js
The following paths are ignored by one of your .gitignore files:
x
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```

In npm's case, we will stubbornly refuse to exclude files that we know are necessary for proper functioning of packages.  So, `README.md`, `package.json`, and `index.js` (which is presumably your `"main"` field), are included regardless of what the `.npmignore` file says.

I think what you probably want in your `.npmignore` file is this:

```
/*
!/dist
```

This will ignore only things matching `*` in the root, but include the root `dist` folder (and thus, all of its contents).

So, working as designed, sorry that you were relying on that bug. 😬

**Comment by macno** [comment]
Hi @isaacs 
I don't think that's true.
npm behaves differently from git.

In fact, if you change your `.npmignore` to

```
*
!dist/**
```
or
```
*
!dist/a/file/that/exists
!dist/another/file/that/exists
```
files are included
