### ISSUE TITLE
[BUG] node-stream-zip@1.3.5 , Unable to extract the nested zip, Error Invalid CRC

### ISSUE THREAD

**Issue by komal08** [npm/cli#2138]
Node Web Kit :0.49.0
Version : node-stream-zip@1.3.5
zip.extract method not able to extract the nested zip file or archived file in Production mode, But it does work in Developer mode.
ERROR : Invalid CRC

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
