### ISSUE TITLE
[BUG] Automation token response 403 forbidden

### ISSUE THREAD

**Issue by joshuaavalon** [npm/cli#2190]
### Current Behavior:

Automation token is failing authentication.

### Expected Behavior:

Automation token should work like Publish token.

### Steps To Reproduce:

1. Generate a "Automation" token
2. Run `npm whoami`

```
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://registry.npmjs.org/-/whoami
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```

P.S. My account enabled 2FA for authorization only.

### Environment:

- OS: Windows 10
- Node: 14.15.0
- npm: 6.14.8

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
