### ISSUE TITLE
IOS Problem

### ISSUE THREAD

**Issue by PrashantPrajapati13** [npm/cli#2191]
Cordova-plugin-device plugin is not working in IOS  latest version. What's the problem? and How can we resolve it?

**Comment by filipefreitas82** [comment]
I'm having the same issue:

>**cordova plugin add cordova-plugin-device**
Failed to fetch plugin cordova-plugin-device via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: npm: Command failed with exit code 1 Error output:
Unhandled rejection Error: EACCES: permission denied, open '~/.npm/_cacache/index-v5/c6/e8/df5cfb4ecfb4ca0a97f09fdd3109fb79761ae8e7af5b877c5079175580e2'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
