### ISSUE TITLE
[BUG] npm makes a suboptimal choice when deduping

### ISSUE THREAD

**Issue by jorrit** [npm/cli#2208]
### Current Behavior:

When the dependency tree contains many versions for one subdependency, npm puts the highest version at the top level (i.e., at node_modules/pkgname), even when another version has more referrals. This other version is then installed many times.

### Expected Behavior:

NPM checks for each package (that is not a direct dependency of the project) which version appears most often and puts that one on the top level, reducing duplication.

### Steps To Reproduce:
```sh
npm init
npm i next@10.0.2
npm ls source-map
```

source-map@0.6.1 should be the top level one, not @0.7.3.

### Environment:
Windows 10
Node 14.13.0
Npm 7.0.12

**Comment by wraithgar** [comment]
The current behavior is the intended one, and is not as such a bug.  Changing this is possible, but it would have to go through our RFC process, which you can find more information about [here](https://github.com/npm/rfcs)

**Comment by isaacs** [comment]
You can get slightly more aggressive deduping behavior by using `--prefer-dedupe`, but the heuristic is still to prefer a newer version (or the first one encountered in the tree building process) over a more commonly used version.  The heuristic suggested here would be pretty difficult to implement as a strict contract with decent guaranteed performance, since moving a more frequently used dep higher up in the tree can change which things are more/less popularly required within the rest of the tree as it is built out.

(When I say "pretty difficult", I mean, if you could do this, I'm pretty sure you'd have a solution to P=NP.)
