### ISSUE TITLE
[Question][bug] is the package-lock of nested dependencies considered for npm installation in parent package/app? 

### ISSUE THREAD

**Issue by kumarrishav** [npm/cli#2224]
### Current Behavior:

https://github.com/dainis/node-gcstats module is a dependency of another module A. When I do npm install in module A, it uses the pinned version mentioned in `node-gcstats` lock file https://github.com/dainis/node-gcstats/blob/master/package-lock.json#L724  (which has the vulnerabilities). How to update it to the latest version
### Steps To Reproduce:

node -v 
v12.18.4
npm -v
6.14.9

- create a module `testnpmpack` (you can start with npm init as well. Also made sure no lock file in the root of module `testnpmpack`)
```
{
  "name": "testnpmpack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "gc-stats": "^1.4.0"
  }
}
```
- `npm i`
-  `npm ls npm-packlist`
- 
```
└─┬ gc-stats@1.4.0
  └─┬ node-pre-gyp@0.13.0
    └── npm-packlist@1.4.1
```
gc-stats@1.4.0 has "node-pre-gyp": "^0.13.0" 
and node-pre-gyp@0.13.0 has "npm-packlist": "^1.1.6" 
and having `^` means, it should resolve to 1.4.8 , not 1.4.1

It should be resolved to the latest npm-packlist (for v1) i.e 1.4.8

**Comment by ljharb** [comment]
package-lock is dev-only, so it should only have an effect when it’s in the top-level directory (the one that `npm install` is reading from).

**Comment by ljharb** [comment]
What happens with npm v7.0.14?

**Comment by kumarrishav** [comment]
@ljharb same behaviour in npm v7.0.14 as well.

Also, I have updated the description with the steps to reproduce.

**Comment by kumarrishav** [comment]
Can you confirm this behavior/bug?

**Comment by nlf** [comment]
the package-lock.json file is not published as part of a package, so no your dependency's package-lock.json is not being followed.

the issue you're seeing is because gcstats bundles the node-pre-gyp dependency seen [here](https://github.com/dainis/node-gcstats/blob/master/package.json#L31-L33)

because of that, node-pre-gyp and all of its dependencies are installed per the package-lock.json in the repo, and then those modules are included as part of the published tarball. because they're bundled dependencies, the only possible way to update them is to bump the versions in the gcstats repo and publish a new version with the updates bundled as well

**Comment by kumarrishav** [comment]
ah. Because of `node-pre-gyp` being bundledDependencies, it bundles the node_modules as well (as per lock file transitive deps)

got it now. Thanks
