### ISSUE TITLE
[BUG] npm install dependencies failing

### ISSUE THREAD

**Issue by jramosss** [npm/cli#2242]
### Expected Behavior:

PD: the project runs normally in my other computer, so its not a problem of my project

**Comment by ljharb** [comment]
What about with npm@7?

**Comment by jramosss** [comment]
> What about with npm@7?

absolutely the same, i installed it as the README of this repo says, and still getting `Error: Argument #5: Expected object but got string`

**Comment by jramosss** [comment]
[2020-11-26T17_35_46_979Z-debug.log](https://github.com/npm/cli/files/5604401/2020-11-26T17_35_46_979Z-debug.log)
i couldnt get npm@7, installing with the script in the readme leads to the version 6.14.9

**Comment by ljharb** [comment]
you need an explicit `npm install -g npm@7` to get it; currently "latest" is set to v6.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
