### ISSUE TITLE
[BUG] 'npm install hapi@18.1.0' after 'npm install hapi@17.8.5' leads to broken hapi install

### ISSUE THREAD

**Issue by trentm** [npm/cli#2267]
### Current Behavior:

With node v15 and npm@7, when I do:

1. `npm install hapi@17.8.5`, then
2. `npm install hapi@18.1.0`

then the hapi installation is broken:

```
% ls node_modules/hapi
node_modules
```

### Expected Behavior:

I expect the hapi installation to not be broken. For example, if I `rm -rf node_modules/hapi` before the install of hapi@18.1.0, then I get a working installation:

```
% rm -rf node_modules

% npm install hapi@18.1.0
...
added 29 packages, and audited 29 packages in 1s
...

% ls node_modules/hapi
CHANGELOG.md        README.md           node_modules        package.json
LICENSE             lib                 npm-shrinkwrap.json
```

### Steps To Reproduce:

Here is a complete repro for me:

```
% ls
package.json


% cat package.json
{
  "name": "p",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": ""
}


% npm install hapi@17.8.5
npm WARN deprecated hapi@17.8.5: This version contains severe security issues and defects and should not be used! Please upgrade to the latest version of @hapi/hapi or consider a commercial license (https://github.com/hapijs/hapi/issues/4114)

added 30 packages, and audited 30 packages in 1s

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.


% ls node_modules/hapi
LICENSE             lib                 npm-shrinkwrap.json
README.md           node_modules        package.json


% npm install hapi@18.1.0

removed 1 package, changed 1 package, and audited 29 packages in 887ms

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.


% ls node_modules/hapi
node_modules
```

Some notes:
- If I `rm -rf node_modules/hapi` between `npm install ...`s, then I get a working installation.
- It isn't specific to *exactly* these versions of the "hapi" package:
    - For example, if I install "18.1.0" first, then "17.8.5" I observe the same broken install.
    - However, installing "17.8.5" then "17.8.4" does **not** result in a broken install.
    - Installing "18.1.0" then "18.0.1" does **not** result in a broken install.
    It feels like there is a dependence on changing between hapi@17 and hapi@18. However I have not fully explored that.

Here is a gist of "silly" log output for the second `npm install` in case it helps: https://gist.github.com/trentm/2f905e8ba11f85daccab92efe905b839

### Environment:

- OS: macOS 10.15.7, also reproduced on a Linux jenkins build agent (sorry I don't know the Linux distro and version for that right now)
- Node: v15.2.1
- npm: 7.0.15

**Comment by nlf** [comment]
thanks for the report, unfortunately i have some bad news. we don't intend to fix this problem.

the root cause is that older releases of hapi include an npm-shrinkwrap.json, but one that was heavily hand edited. in npm 5 and 6 we used the shrinkwrap as more of a guide and still ensured that your package tree was valid after applying it, however in npm 7 we have made the contract of shrinkwraps more strict so that they're more of a "what you ask for is exactly what you'll get" which will break the install to some degree in the case of these modified shrinkwraps.

there is an additional strange bug here in the disappearance of hapi itself, and we'll see if that's reproducible outside of hand edited shrinkwrap files, but if it's not that won't get fixed either.

as a maintainer of hapi as well as npm, i would encourage you to update to a newer hapi release. if you're already using 17 (or even 18) updating to the current `@hapi/hapi` version 20 release should be reasonably straight forward. we no longer provide a shrinkwrap for any currently supported version of hapi so they won't exhibit this weird behavior.

**Comment by trentm** [comment]
> the root cause is that older releases of hapi include an npm-shrinkwrap.json,...

Thanks for the cause info.

> as a maintainer of hapi as well as npm, i would encourage you to update to a newer hapi release

Totally understood. I maintain https://www.npmjs.com/package/elastic-apm-node, an APM library that hooks (grossly) in to many frameworks (including hapi), for which we test with old and new versions of those frameworks for compat. We definitely wouldn't be using such an old version of hapi ourselves, but, at least *currently* don't want to drop compat for our users.
