### ISSUE TITLE
[BUG] fsevents resolved as a non-optional dependencies on Windows

### ISSUE THREAD

**Issue by Jack-Works** [npm/cli#2291]
### Steps To Reproduce:

1. Check out this PR https://github.com/DimensionDev/Maskbook/pull/1980
2. Run `npm i` with npm7 on Windows

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     ~\AppData\Local\npm-cache\_logs\2020-12-07T08_12_27_509Z-debug.log
```

### Environment:

Windows 10
Node 15.3.0
npm 7.0.14

**Comment by Jack-Works** [comment]
https://github.com/npm/cli/blob/bf09e719c7f563a255b1e9af6b1237ebc5598db6/node_modules/%40npmcli/arborist/lib/arborist/build-ideal-tree.js#L226

I guess the problem is here. In my debug process, the `fsevents` is `optional: false` but `devOptional: true` so maybe it should be

```js
 if (!node.optional && !node.devOptional) { 
```

@isaacs is that right?

**Comment by isaacs** [comment]
So, no, that's not right.  A node that has `devOptional` set and does _not_ have `optional` or `dev` set is something that is _both_ an optional dep in the non-dev tree, _and_ a non-optional dep in the dev tree.  `devOptional` is there to handle cases where we wish to omit or prune both dev and optional deps, but things in this state would not be easy to track otherwise.  They're not an optional dep (because they're a non-optional dev dep) and they're not strictly a dev dep either (because they're an optional non-dev dep), but if you are removing both optional _and_ dev, then they should be removed.

But non-optional dev deps (like non-dev optional deps) will always have `devOptional` set on the Node object, so this patch is a bad idea, because non-optional dev deps that fail to install will be ignored.

See: https://github.com/npm/arborist#package-dependency-flags

What's weird, though, is that I only see fsevents in your tree with `optional=true` once it's built.  It looks like you might have updated from npm v6 to a version of the npm v7 beta that had a bug where it was not properly refreshing package metadata for items found in the old npm v6 lockfile.  This patch should fix your problem, and it would not happen again today for new upgraders:

```patch
diff --git a/package-lock.json b/package-lock.json
index 1ceee072..a04b8c43 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -18716,6 +18716,9 @@
         "normalize-path": "~3.0.0",
         "readdirp": "~3.5.0"
       },
+      "optionalDependencies": {
+        "fsevents": "~2.1.2"
+      },
       "engines": {
         "node": ">= 8.10.0"
       }
@@ -46092,6 +46095,9 @@
         "path-is-absolute": "^1.0.0",
         "readdirp": "^2.2.1",
         "upath": "^1.1.1"
+      },
+      "optionalDependencies": {
+        "fsevents": "^1.2.7"
       }
     },
     "node_modules/watchpack-chokidar2/node_modules/glob-parent": {
```

Also, it looks like your peer deps are showing some conflicts on a fresh install that aren't properly addressed by setting `--force`, even after removing the pinned deps on 0.0.0 versions of react and react-dom, so I'll take a look into that.

**Comment by davidje13** [comment]
Is this actually resolved? I don't have a Windows OS available but it looks connected to #1886 / #2203 / #724 — `optionalDependencies` get copied as `dependencies` in the package.json file itself when running `npm install`.

Edit: ah, I looked at the [package.json](https://github.com/DimensionDev/Maskbook/blob/master/package.json) for the linked project and I see that the problem here isn't with optionalDependencies in the current project, but in a sub dependency, so I guess the issues I linked to don't apply in this case.

**Comment by mpereira** [comment]
I was also seeing this. I develop on macOS and have a project that builds in two other places: GitHub actions and Netlify.

GitHub actions uses npm 6.14.11 and builds fine, while Netlify uses npm 7.4.3 and was failing to build with the exact output in this issue's first message.

I don't have fsevents as an explicit dependency in my `package.json`:
```
$ npm ls fsevents
<...>
├─┬ depcheck@1.4.0
│ └─┬ sass@1.32.8
│   └─┬ chokidar@3.5.1
│     └── fsevents@2.3.2 deduped
└─┬ react-scripts@4.0.1
  ├─┬ babel-jest@26.6.3
  │ └─┬ @jest/transform@26.6.2
  │   └─┬ jest-haste-map@26.6.2
  │     └── fsevents@2.3.2 deduped
  ├── fsevents@2.3.2
  ├─┬ webpack-dev-server@3.11.0
  │ └─┬ chokidar@2.1.8
  │   └── fsevents@1.2.13
  └─┬ webpack@4.44.2
    └─┬ watchpack@1.7.5
      └─┬ watchpack-chokidar2@2.0.1
        └─┬ chokidar@2.1.8
          └── fsevents@1.2.13
```

After an hour of hitting my head on the wall, I tried removing node_modules and `package-lock.json`, re-running `npm install`  and triggering another build on Netlify. That worked for some reason, and the Netlify build is succeeding again. Hopefully it stays that way...

**Comment by TurtleWolfe** [comment]
I deleted all my node modules and the package-lock.json then the new install automatically replaced all of my node modules
