### ISSUE TITLE
[BUG] npm prune --production removes packages referenced by url instead of version

### ISSUE THREAD

**Issue by pkuczynski** [npm/cli#2296]
### Current Behavior:

My `package.json` looks like this:

```json
  "dependencies": {
    "my-package": "git+https://...",
  }
```

After running `npm prune --production` this package gets deleted.

### Expected Behavior:

Package from `dependencies` should not be deleted.

### Steps To Reproduce:

1. `node:12-alpine` image
2. With above `package.json` (and equivalent `package-lock.json`)
3. Run `npm prune --production`
4. Package `my-package` is gone from `node_modules`

### Environment:

- OS: Alpine
- Node: 12.20.0
- npm: 6.14.8

**Comment by pkuczynski** [comment]
This seems to be similar to issue reported here https://npm.community/t/npm-prune-production-after-npm-ci-only-erroneously-uninstalls-regular-dependency/5055. Not sure if it was fixed or not...

**Comment by pkuczynski** [comment]
As a workaround, I can call `npm install --production` after running prune, and it will bring back deleted packages. This however confirms the issue with `npm prune` :/

**Comment by kumarrishav** [comment]
I am also facing the same issue. 

if I tag a module `foo` as dist-tags version `7.2.1-ubds` as `userread_ca_ubds`  while publishing it and in my package.json of my app if i use `userread_ca_ubds` instead of `7.2.1-ubds` ( i.e `"foo": "userread_ca_ubds"`), then upon running npm prune --production (after running `npm ci`), it deletes the dependency. No issue if I run npm prune --production  after npm i

https://npm.community/t/npm-prune-production-after-npm-ci-only-erroneously-uninstalls-regular-dependency/5055/7

node -v
v10.22.1
npm -v
6.14.9

**Comment by pkuczynski** [comment]
@darcyclarke has this been fixed if you closed it?
