### ISSUE TITLE
[BUG] <err>npm ERR! cb() never called!

### ISSUE THREAD

**Issue by vikas17d** [npm/cli#2298]

**Comment by typno8-nEbtos-hibmik** [comment]
[]()

**Comment by jonnhanks** [comment]
I'm getting the same when running create-react-app. 
npm -v = 6.14.8
nodejs -v = 14.15.1

Log:
[2020-12-08T21_13_51_657Z-debug.log](https://github.com/npm/cli/files/5661988/2020-12-08T21_13_51_657Z-debug.log)

**Comment by Sid-Sun** [comment]
+1 - When installing dependencies after ng new 
npm -v = 6.14.8
[2020-12-09T19_34_26_169Z-debug.log](https://github.com/npm/cli/files/5668255/2020-12-09T19_34_26_169Z-debug.log)

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
