### ISSUE TITLE
[BUG] npm 7 destroys itself if update is cancelled early

### ISSUE THREAD

**Issue by targos** [npm/cli#2312]
### Current Behavior:

Because npm 7 is not latest yet, I have to remember to add the version number in my command to update it: `npm i -g npm@7`.
If I forget to do it, realize that shortly after launching the command, and stop the update with CTRL+C, npm doesn't work anymore (it cannot be found in the PATH). This is annoying because the only way to fix the broken state in my case is to switch to another Node.js version, and to delete and reinstall the broken one.
I know there has to be a moment during which the old version is actually replaced by the newly installed one, but the window can probably be made much shorter. npm 6 is not affected by this issue.

### Expected Behavior:

I expect npm to wait as long as possible before removing itself, so cancelling installation is less likely to break it.

### Steps To Reproduce:

1. `npm i -g npm`
2. after ~1s: CTRL+C

### Environment:

- OS: Windows 10 / Linux
- Node: 15
- npm: 7.1.0

**Comment by targos** [comment]
This still seems to be the case with npm 7.4.0.

**Comment by isaacs** [comment]
So, the reason for this is that npm v7 uses a different way to stage and unpack package contents.  This means that the rollback logic can be more robust, and less vulnerable to crashing with "directory not empty" errors, especially on Windows.

However, it also means that we start making changes to the target location right away (because we have to move the current package out of the way _before_ unpacking in place).  So if you ^C during the install, it's borked, during a much larger window.

Easiest solution is probably to just have Arborist.reify() listen for terminal process signals, and rollback during the installation process if any are encountered (and then, post-rollback, maybe self-terminate with the signal we saw, so that when you ^C you get a proper `{signal:'SIGTERM', code: null}` exit status).

I think the best approach will be to only do this the _first_ time the signal is encountered, just in case the rollback locks up or something else weird happens, so you can mash `^C^C^C...` to make it end _right now_ rather than staying locked up.  And of course, `SIGKILL` and a few others are uncatchable, so they'll always leave the install in a broken state.  But we should do what we can, I agree.
