### ISSUE TITLE
[BUG] npm i add invalid version to package.json

### ISSUE THREAD

**Issue by Jack-Works** [npm/cli#2320]
### Steps To Reproduce:

> /package.json

```json
{ "workspaces": [ "sub" ] }
```

> /sub/package.json

```json
{ "name": "sub" }
```

Run `npm i sub` in `/`. Sub package will be linked (that is correct). But wrong item is added to `/package.json` `"sub": "^"`, which should be `"sub": "*"` because sub doesn't have a version field.

### Environment:

- Node: 14
- npm: 7.1.1

**Comment by ljharb** [comment]
cc @ruyadorno

**Comment by isaacs** [comment]
Maybe `^` _should_ be a valid range?  `^*` is valid, and `''` is equivalent to `'*'`, after all.  🤔

**Comment by ljharb** [comment]
eesh, that seems too magic to me. `~` would be, would `>=` and `<` etc all be also?

**Comment by isaacs** [comment]
`>*` and `<*` are both null sets (since they're "less than everything" or "greater than everything").  But `>=`, `<=`, `^`, `=`, and `~` would all become synonyms for `*` if we did that.

Kind of off-topic, sorry.  Bottom line, we shouldn't be saving a dep range with a prefix attached to an empty version field 😅

**Comment by Jack-Works** [comment]
> Maybe `^` _should_ be a valid range? `^*` is valid, and `''` is equivalent to `'*'`, after all. 🤔

So it's a dependabot bug? 🤔 (See https://github.com/DimensionDev/Maskbook/issues/2073)

**Comment by isaacs** [comment]
> So it's a dependabot bug? 🤔 (See DimensionDev/Maskbook#2073)

I think I'm suggesting a SemVer feature request, actually.  Dependabot is fine 😅
