### ISSUE TITLE
npm uninstall adds devDependencies

### ISSUE THREAD

**Issue by hk185104** [npm/cli#2321]
### Current Behavior:
I have a list of dependencies and devDependencies in `package.json`. Using `npm install --production` works as expected, none of the devDependencies are installed. However, if I ever uninstall one of the dependencies, it installs the devDependencies along with it.

### Expected Behavior:
Uninstalling a package should not install the devDependencies

### Steps To Reproduce:
1. Create package.json with dependencies and devDependencies
2. Run `npm install --production`
3. Run `npm ls <package>` (Choose any package from devDependencies to ensure it isn't there)
4. Run `npm uninstall <package>` (Choose any package from dependencies)
5. Run `npm ls <package>` (Choose the package from step 3 to see the devDependencies have been installed)

### Environment:
- OS: MacOS 10.15.7
- Node: 14.13
- npm: 6.14.8

**Comment by ljharb** [comment]
What happens with npm v7.1.1?

**Comment by hk185104** [comment]
> What happens with npm v7.1.1?

The same behavior is seen in 7.1.1.

**Comment by isaacs** [comment]
This has been the case for quite some time.  Both `install` and `uninstall` work in a similar fashion:

- add/remove the arguments to/from the list of dependencies in `package.json`
- build the ideal tree with those changes to the dependency list
- reify that ideal tree onto disk

So, the first `install` is done with `--production`, but the `uninstall` needs to _also_ be done with `--production`.

This can lead to some surprising behavior (though technically correct, and required by the dependency contracts!)  For example, if you install a package `foo` and `bar`, where `foo` depends on `bar`, you'll get one copy of each.  If you then `rm -rf node_modules/bar`, and then `npm uninstall bar`, then npm will _put it back_, because it'll note the missing dependency for the `foo` package.  (It will also remove it from package.json, however.)

I am open to exploring a change to this (maybe some kind of option we could pass to Arborist to tell it not to ever add missing dependencies in some cases).  But, it would almost certainly be a breaking change and should go through our [rfc process](/npm/rfcs)
