### ISSUE TITLE
<BUG> cb() never called!

### ISSUE THREAD

**Issue by Tajmirul** [npm/cli#2365]
I was trying to create a new react app by the command:
`npx install create-react-app my-app`

After a few minutes, I give an error.
`npm ERR! cb() never called!`

### Environment:

- OS: Windows 10 pro
- Node: 14.15.0
- npm: 6.14.8

![image](https://user-images.githubusercontent.com/62275307/102423233-c1dd9980-4032-11eb-9b4d-d998b339f299.png)

**Comment by Tomato6966** [comment]
First use this:     `npm cache clean --force`

Then it should work!

**Comment by rak10** [comment]
I tried using `npm cache clean --force` but it did not work. 

![react-bug](https://user-images.githubusercontent.com/18660838/103457755-5407c200-4d02-11eb-8f0b-748ff2c5c749.JPG)

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
