### ISSUE TITLE
[BUG] npm uninstall doesn't always remove the package from package-lock

### ISSUE THREAD

**Issue by rafgraph** [npm/cli#2391]
### Current Behavior:
`npm uninstall --save <package>` doesn't remove the package version listed in `package.json` from `package-lock.json` when another version exists.

### Expected Behavior:
For the package version listed in `package.json` to be removed from `package-lock.json`. Essentially running `npm install --save <package> && npm uninstall --save <package>` should leave `package-lock.json` unchanged.

### Steps To Reproduce:
```zsh
npm init --yes
npm i --save-dev rollpkg
# rollpkg has a dependency of jest ^26.6.3, which is now in the top level node_modules
npm i --save-dev jest@26.0.0
# jest is added to package.json and
# jest 26.0.0 is now in top level node_modules, 26.6.3 is moved to node_mod/rollpkg/node_mod
npm uninstall --save-dev jest
# jest is removed from package.json
# but node_modules is unchanged
```
### Environment:

- OS: MacOS 10.15.7
- Node: 14.15.0
- npm: 7.3.0

Thanks for all the great work on npm v7, I'm really enjoying using it!

**Comment by isaacs** [comment]
The issue is that rollpkg is not the _only_ thing depending on jest, and the other dependents accept jest 26.0.0.  Once they are depending on it, it's not obvious that moving the nested `jest@26.6.3` up to the top level is the right thing to do.

Initial install, you get this:

```
└─┬ rollpkg@0.3.0
  ├─┬ jest-watch-typeahead@0.6.1
  │ └── jest@26.6.3 deduped
  ├── jest@26.6.3
  └─┬ ts-jest@26.5.0
    └── jest@26.6.3 deduped
```

So, `rollpkg`, `jest-watch-typeahead`, and `ts-jest` all are sharing the same `jest@26.6.3` in the root `node_modules` folder.  (Note that `npm ls` shows the logical dep graph, which will not typically match the `node_modules` layout on disk.)

Then we install `jest@26.0.0`, which is not acceptable for `rollpkg`, but _is_ acceptable for `jest-watch-typeahead` and `ts-jest`, resulting in this:

```
├── jest@26.0.0
└─┬ rollpkg@0.3.0
  ├─┬ jest-watch-typeahead@0.6.1
  │ └── jest@26.0.0 deduped
  ├── jest@26.6.3
  └─┬ ts-jest@26.5.0
    └── jest@26.0.0 deduped
```

Next, we `npm rm jest`, removing the top-level dependency.  However, the package at `node_modules/jest` is still an acceptable resolution for `ts-jest` and `jest-watch-typeahead`.  Because the package still has dependents in the tree, it doesn't get removed from disk.

```
└─┬ rollpkg@0.3.0
  ├─┬ jest-watch-typeahead@0.6.1
  │ └── jest@26.0.0
  ├── jest@26.6.3
  └─┬ ts-jest@26.5.0
    └── jest@26.0.0 deduped
```

In order to make the guarantee in the expected behavior, any uninstallation would have to dedupe the tree (at least, for the package names being removed).  And this could, in fact, have even _more_ changes than one might expect.

Consider if you had run `npm install ts-jest jest-watch-typeahead jest@26.0.0`, and then later did `npm install rollpkg@0.3.0`, creating the duplicate.  Then, you find you don't need jest directly, and run `npm rm jest`.  It would be surprising if doing that caused the `jest` in use by `ts-jest` and `jest-watch-typeahead` to be upgraded to `rollpkg`'s `jest@26.6.3`.  ("I ran `npm uninstall jest` and it installed the new version of jest!? I specifically requested the opposite of this!")

The simplest answer is to just say, look, if you want your package tree to be deduped, there is an `npm dedupe` command to do exactly that.  Running `npm dedupe jest` or `npm update jest` will get the tree to your desired state.  Or you could install jest@26.6.3, which will dedupe rollpkg's, and then uninstall it to remove the top-level dependency, leaving it in place.  There's quite a few paths out of this maze, in fact 😅 

There is no guarantee that running an install and then an uninstall will leave the tree in exactly the same state it was before.  Even if we wanted to make this guarantee, we don't track the past states of the tree, and so we have no information about how you got into the current state.  All we have is the current state, and the requested change.  npm guarantees that it will not leave extraneous or incorrect dependencies behind, and is satisfying that contract.

It would be worth discussing, imo, to look for deduplications in the explicitly removed packages when constructing the ideal tree, but that will mean that uninstalls might take longer, and even require that new things be installed, which tends to be a bit of a `WAT` moment for most people.  If you would like to explore that, probably it should be a conversation on https://github.com/npm/rfcs

**Comment by xenoterracide** [comment]
I have to disagree, my case I removed one of our internal dependency, I tried dedupe, remove, uninstall, --save, --save-dev, update, and it still exists in the package-lock.json

❯ rg -l onemonitoring
back-end/package-lock.json

**Comment by xenoterracide** [comment]
and it doesn't exist as a dependency anywhere else in the tree

**Comment by ljharb** [comment]
@xenoterracide what does `npm explain onemonitoring` print out? (assuming that's the package name)

**Comment by xenoterracide** [comment]
```
❯ rg -l onemonitoring
back-end/package-lock.json
❯ npm explain -ws @onemonitoring/express-chassisjs-testing-lib
npm ERR! No dependencies found matching @onemonitoring/express-chassisjs-testing-lib

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nqy642/.npm/_logs/2022-03-09T17_16_50_225Z-debug-0.log

❯ npm explain  @onemonitoring/express-chassisjs-testing-lib
npm ERR! No dependencies found matching @onemonitoring/express-chassisjs-testing-lib

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nqy642/.npm/_logs/2022-03-09T17_18_32_925Z-debug-0.log

❯ npm explain --also=dev  @onemonitoring/express-chassisjs-testing-lib
npm ERR! No dependencies found matching @onemonitoring/express-chassisjs-testing-lib

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nqy642/.npm/_logs/2022-03-09T17_19_17_874Z-debug-0.log


```
as a note, uninstall seems to be working for dependencies that aren't internal, not certain why that would make a difference

**Comment by ljharb** [comment]
it's confusing there's a lockfile inside `back-end`; can you cd into that directory and run the same `npm explain` command? (probably after `npm install`)

**Comment by xenoterracide** [comment]
oh, I did that for the last 2, I thought I copied my cd in my output, oops

**Comment by xenoterracide** [comment]
should there only be one lockfile for workspaces, btw?

**Comment by ljharb** [comment]
Yes, there should only be a lockfile at the root.

**Comment by xenoterracide** [comment]
I wonder if that's the source of the issue

**Comment by xenoterracide** [comment]
looks like, but it not removing it when it's run in the `back-end` directory seems like a bug, especially if install works
