### ISSUE TITLE
[BUG] `npm ci` doesn't respect "lockfileVersion" field

### ISSUE THREAD

**Issue by mwf** [npm/cli#2396]
### Current Behavior:

We had a developer, who used `npm 7.x` by mistake in a project with 6.x in production. 
Npm 7.x generated `package-lock.json` with `"lockfileVersion": 2` and new lockfile structure.

But `npm ci` didn't even notice it and produced the build.
Without even a Warning.

Interesting that `npm install` produces such warning:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

Even more, I tried setting `"lockfileVersion": 20` some non-existent and non-supported version, and nothing changed :)
I don't expect such behaviour from a tool, created with intent to make builds **safe and reproducible**.

### Expected Behavior:

`npm ci` should check `lockfileVersion` and exit with some meaningful error, if the version is not supported.

### Steps To Reproduce:

1. Set `"lockfileVersion"` to any >1 in `package-lock.json`
2. Run `npm ci`

### Environment:
- Node: 14.12.0
- npm: 6.14.8

**Comment by mwf** [comment]
@darcyclarke Hi!

Finally, I see some activity from npm member :)

Could you please leasve some feedback on my issue? 
Is it going to be fixed?
Do you need any additional info from me? :)

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
