### ISSUE TITLE
[BUG] NPM is not downloading whole package

### ISSUE THREAD

**Issue by GeekCornerGH** [npm/cli#2399]
### Current Behavior:

NPM is only downloading readme.md and package.json from [Androz2091/discord-temp-channels](https://www.npmjs.com/package/discord-temp-channels)

### Expected Behavior:

It should download the whole package

### Steps To Reproduce:

1. Create any npm package (`npm init -y` is your friend)
2. Execute `npm install --save discord-temp-channels`
3. Go to the `node_modules/discord-temp-channels` folder
4. See what files are in this folder

### Environment:

- [x] OS: Raspberry Pi OS 10 armv71
- [x] Node: v14.15.1
- [x] NPM: v6.14.10

Thanks in advance for help

**Comment by ljharb** [comment]
That’s because that’s the only filed that are in it: https://unpkg.com/browse/discord-temp-channels@1.0.4/

Likely whoever published it forgot to run the build process (I’d suggest adding that to a “prepublish” or “prepare” script so it can’t be forgotten). You’ll want to file an issue on that repo.

**Comment by GeekCornerGH** [comment]
> That’s because that’s the only filed that are in it: https://unpkg.com/browse/discord-temp-channels@1.0.4/
> 
> Likely whoever published it forgot to run the build process (I’d suggest adding that to a “prepublish” or “prepare” script so it can’t be forgotten). You’ll want to file an issue on that repo.

Hello @androz2091, you have something to do ^^

**Comment by Androz2091** [comment]
Fixed, thank you
