### ISSUE TITLE
[BUG] Comments Inside Dependencies don't work when using npm ci

### ISSUE THREAD

**Issue by rafaelcalpena** [npm/cli#2402]
### Current Behavior:

Comments inside `dependencies` property are allowed by `npm i`. 
Here's an example of `package.json` with the comments feature:

```
"dependencies": {
  "/": "",
  "// 1": "first line of comments",
  "// 2": "second",
  "// 3": "third",
  "/ ": "",  
  ...list of dependencies
}
```

However, when using `npm ci` the installation gives an error:

```
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "/": name can only contain URL-friendly characters
```

### Expected Behavior:
Both `npm i` and `npm ci` should work with comments inside the `dependencies` property

### Steps To Reproduce:
1. Copy comments from example inside some package.json file
2. Run `npm i` and `npm ci` for comparison

### Environment:
- OS: MacOS Big Sur 11.1
- Node: 14.15.1
- npm: 6.14.10

**Comment by ljharb** [comment]
To be honest, I'm shocked this works with `npm install`, and I'd consider _that_ a bug. The only kind of comments that JSON has are as follows:
```json
{
  "x": "this is a field about x's!",
  "x": "this is the real value of x"
}
```

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
