### ISSUE TITLE
npm ERR! 404 Not Found - GET http://registry.npmjs.org/asb - Not found. Getting this error while compiling

### ISSUE THREAD

**Issue by sourabupadhya123** [npm/cli#2421]
root@localhost:/home/sourab/near# npx asb
npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/asb - Not found
npm ERR! 404 
npm ERR! 404  'asb@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-29T10_17_44_349Z-debug.log
Install for [ 'asb@latest' ] failed with code 1

**Comment by pankaj-aggarwal** [comment]
I Have found the solution for the error given above

Just go to your project location and open the terminal and simply write `npm i `

Happy Hacking!

**Comment by sourabupadhya123** [comment]
still getting same error

**Comment by unknown08032017** [comment]
Hello! Have you solved the error? I got it.

**Comment by unknown08032017** [comment]
> все еще получаю ту же ошибку
Hi!
Have you solved the error? need help me.

**Comment by unknown08032017** [comment]
Привет!
Вы устранили ошибку? нужна мне помощь.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
