### ISSUE TITLE
npm ERR! cb() never called! when installing npm

### ISSUE THREAD

**Issue by varundev465** [npm/cli#2426]
Hi Team, 
While installing NPM package into my project I did encountered the below issue.

npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

![image](https://user-images.githubusercontent.com/76736702/103288228-7059e500-4a0a-11eb-9eb0-be40167eefc5.png)

### Environment:
- OS: Windows 10
- Node: 13.14.0
- npm: 6.4.12

**Comment by rak10** [comment]
I have the same problem, I tired to create a new project with "npx create-react-app".

OS: Windows 10 64bit

{
  **npm: '6.14.10',**
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  **node: '14.15.3',**
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.17',
  zlib: '1.2.11'
}

**Comment by rak10** [comment]
Update: I changed the folder where I was trying to create the react app and it worked! Check the second last reply in the issue below:
[https://github.com/npm/cli/issues/2352](url)

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
