### ISSUE TITLE
[BUG] [DOC] git aliases

### ISSUE THREAD

**Issue by xloem** [npm/cli#2427]
The `npm install` documentation for aliases states git repositories are supported but misses the line saying how.  It seems the user would be told to either remove or change the term `npm:` in the parameter such that it represents the git host, when doing this.  Additionally, the error message states the feature is not supported, when it actually works.  See https://github.com/nodejs/node/issues/36687 for system details and terminal output.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
