### ISSUE TITLE
[BUG] ERR! cb() never called! 

### ISSUE THREAD

**Issue by lcrumling** [npm/cli#2431]
### Current Behavior:
used command:  sudo npm install -g n

### Expected Behavior:
globally installs n

### Steps To Reproduce:
ex. steps to reproduce the behavior:
1. In this environment...(see below)
2. With this config...(not sure what this means)
3. Run 'sudo npm install -g n'
4. Get error:
lindseycrumling@Lindseys-MBP hybrid_app % sudo npm install -g n
Unhandled rejection Error: EISDIR: illegal operation on a directory, open '/Users/lindseycrumling/.npm/_cacache/content-v2/sha512/a3/01'
    at Error (native)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lindseycrumling/.npm/_logs/2020-12-31T17_26_55_875Z-debug.log

### Environment:
- OS: macOS Catalina 10.15.7
- Node: v6.13.1
- npm: v6.9.0

**Comment by Blue-Heaven** [comment]
I now get this error whilst trying to run 'npx create-react-app' 

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

**Comment by rak10** [comment]
[https://github.com/npm/cli/issues/2352](url)

I tried this and it worked for me. Just change the folder if you are using Windows 10.

**Comment by mushonnip** [comment]
I got same error when installing some package
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'vue-tailwind-picker' ]
2 info using npm@6.14.10
3 info using node@v15.3.0
4 verbose npm-session 8957f417fec9c221
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 timing npm Completed in 6915ms
8 error cb() never called!
9 error This is an error with npm itself. Please report this error at:
10 error <https://npm.community>

```

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
