### ISSUE TITLE
[BUG] `npm owner add` command and web UI appears to not be working

### ISSUE THREAD

**Issue by jescalan** [npm/cli#2449]
### Current Behavior:
I am the owner of the package `next-mdx-remote`, and am trying to add a coworker, `bkalow`, so he is able to publish. I added his handle on the npm website, and you can see he [appears as a maintainer](https://www.npmjs.com/package/next-mdx-remote).

However, when he tries to publish, he gets "access denied". Additionally, if I run `npm owner ls next-mdx-remote` on the command line, he does not show up. I tried also running `npm owner add bkalow next-mdx-remote` on the command line as well, and while it confirmed success, another `npm owner ls` run confirmed that he still does not have access, and is still not able to publish. This leads me to believe that something is wrong with the process of adding owners to a package, perhaps?

### Expected Behavior:
When a owner/maintainer is added to a package via web UI or command line, they are allowed to publish the package.

### Steps To Reproduce:
- Add a new owner to a package
- Run `npm owner ls <owner> <package>`, and note that the recently added owner does not appear

### Environment:
- OS: OSX Catalina
- Node: 12.13.0
- npm: 6.14.10

**Comment by jescalan** [comment]
*Update:* When I check now several minutes later, he is appearing as an owner. I'm guessing this is an eventual consistency issue? If so, it would be nice to have a note appear after adding a new owner that you may have to wait a few minutes before they are able to publish. I just expected it to work right away since the interfaces gave me this impression.

Would be happy to try to put in a PR to add a note along these lines if that would be appreciated!

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
