### ISSUE TITLE
[BUG] Version resolution in a monorepo

### ISSUE THREAD

**Issue by seebees** [npm/cli#2450]
### Current Behavior:
This was found in https://github.com/aws/aws-sdk-js-crypto-helpers/pull/189

For any package `@aws-sdk/*`.
The version rang requested was `^3.0.0`.
The most recent published version was `3.1.0`.

When I removed `package-lock.json` and `npm install` the resolved versions did not make sense.
The first package would get a dependency of `3.1.0`.
But all other packages got `3.0.0`.

A concrete example.

Both [@aws-crypto/random-source-browser](https://github.com/seebees/aws-sdk-js-crypto-helpers-1/blob/f44ddc48e7635d9f8936b39017b59fc2d21a5acb/packages/random-source-browser/package.json#L22) and [@aws-crypto/sha256-browser](https://github.com/seebees/aws-sdk-js-crypto-helpers-1/blob/f44ddc48e7635d9f8936b39017b59fc2d21a5acb/packages/sha256-browser/package.json#L23)
take a dependencey on @aws-sdk/util-locate-window
The package.json lines are the same `"@aws-sdk/util-locate-window": "^3.0.0",`

These should both resolve to `@aws-sdk/util-locate-window@3.1.0`.
However
```
$ npm ls @aws-sdk/util-locate-window
aws-javascript-crypto-helpers@0.0.1 aws-sdk-js-crypto-helpers
├─┬ @aws-crypto/random-source-browser@1.0.0 -> aws-sdk-js-crypto-helpers/packages/random-source-browser
│ └── @aws-sdk/util-locate-window@3.1.0 
└─┬ @aws-crypto/sha256-browser@1.0.0 -> aws-sdk-js-crypto-helpers/packages/sha256-browser
  └── @aws-sdk/util-locate-window@3.0.0 
```

Very strange to me.
This seems to have made it better https://github.com/aws/aws-sdk-js-crypto-helpers/pull/189/commits/745181d761d690853eec622e281e27953d486a17

### Expected Behavior:

I would expect that the same semver range
for different packages
would result in the same version getting installed.

### Steps To Reproduce:

git clone git@github.com:seebees/aws-sdk-js-crypto-helpers-1.git
cd aws-sdk-js-crypto-helpers-1
git checkout f44ddc48e7635d9f8936b39017b59fc2d21a5acb
npm ci
rm -rf node_modules
rm package-lock.json
npm install
npm ls @aws-sdk/util-locate-window

### Environment:
- OS: OSX 10.14.6
- Node: 14.13.0
- npm: 6.14.10

I also tried npm: 7.3.0 and got similar results.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
