### ISSUE TITLE
unable to update the npm version

### ISSUE THREAD

**Issue by oddyrather** [npm/cli#2451]
Hi Team,

currently i am having 
node -v -v10.10.0
npm -v- 6.4.1

i am trying to upgarde to node version to v14.15.4 using the 
wget http://nodejs.org/dist/v14.15.4/node-v14.15.4-linux-x64.tar.gz
sudo tar -C /usr/local --strip-components 1 -xzf node-v14.15.4-linux-x64.tar.gz
Infact after upgrading also the versions are showing same.
after this when i am trying to execute the below command
install -g @angular/cli
getting error as 
"Unhandled rejection Error: EACCES: permission denied, mkdir '/.npm'
npm ERR! cb() never called!"
npm ERR! This is an error with npm itself. Please report this error at:
 npm ERR!     <https://npm.community>

tried adding permissons and given root access nothing is working out .
Could you please check and help me with this error.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
