### ISSUE TITLE
[BUG] <error Installing dependencies into a bare React Native project>

### ISSUE THREAD

**Issue by PriFerreira** [npm/cli#2477]
C:\Users\HP\Desktop\React_pri>npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade 
your dependencies to the actual version of core-js@3.
npm WARN tar EPERM: operation not permitted, open 'C:\Users\HP\Desktop\React_pri\node_modules\.staging\setimmediate-f9927936\LICENSE.txt'
npm WARN tar EPERM: operation not permitted, open 'C:\Users\HP\Desktop\React_pri\node_modules\.staging\node-fetch-a1fde7f1\test\dummy.txt'        
npm WARN tar EPERM: operation not permitted, open 'C:\Users\HP\Desktop\React_pri\node_modules\.staging\@react-native-community\masked-view-5dba3428\android\src\main\ic_launcher-web.png'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2021-01-12T14_03_07_836Z-debug.log

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
