### ISSUE TITLE
[BUG] "npm audit fix" replaces direct dependencies without considering semantic version compatible

### ISSUE THREAD

**Issue by lcwj3** [npm/cli#2478]
### Current Behavior & Steps To Reproduce:

I am trying to remediate vulnerabilities in dependencies via "npm audit fix", and find several cases of incompatible remediation, here is one case:
1. Here I use `dthree/cash` as example, `git clone https://github.com/dthree/cash`
2. `npm install` to install dependencies
3. `npm ls`, and can find `gulp@3.9.1` and `xo@0.12.1` is installed as direct dependency, this is because `"gulp": "^3.9.0"` and `"xo": "^0.12.1"`  are defined in [`package.json`](https://github.com/dthree/cash/blob/master/package.json#L44)
4. Then I run `npm audit fix` to handle vulnerable dependencies.
5. `npm ls` again to check the changes, and I find `gulp@4.0.2` and `xo@0.37.1` are installed as direct dependencies.

### Expected Behavior:
The installed `gulp@4.0.2` and `xo@0.37.1`violate user defined dependencies. `^3.9.0` presents `>=3.9.0 & < 4.0.0`, and `^0.12.1` presents `>=0.12.1 & < 0.13.0` according to [NPM semantic version](https://semver.npmjs.com/).

Besides, I also find several other cases, and they can also be reproduced based on the steps above. Here I list all the cases I found.
github repos | direct dependency in `package.json` | installed before `npm audit fix` | installed after `npm audit fix`
---- | ---- | ---- | ----
https://github.com/nuysoft/Mock | gulp-mocha-phantomjs@^0.10.1 | gulp-mocha-phantomjs:0.10.1 | gulp-mocha-phantomjs@0.12.2
https://github.com/kriskowal/q | jshint@~2.1.9 | jshint@jshint:2.1.11 | jshint@2.12.0
https://github.com/afaqurk/linux-dash | angular@1.3.4 | angular@1.3.4 | angular@1.8.2
https://github.com/jacomyal/sigma.js | http-server@~0.9.0 | http-server@0.9.0 | http-server@0.12.3

### Environment:

- OS: Ubuntu 18.04
- Node: v14.15.3
- npm: 6.14.9

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
