### ISSUE TITLE
[BUG] <npm install steam-user gave an error>

### ISSUE THREAD

**Issue by nknownhacker** [npm/cli#2507]
When I tried to steam-user it gave an error and told me to open up an issue which so I did
File is linked along with this
The platform is linux xfce4

[npm-debug.log](https://github.com/npm/cli/files/5833138/npm-debug.log)

**Comment by nlf** [comment]
based on your log, you appear to be using npm 3.5.2, this is a very very old version that we no longer support.

i would try updating to the latest version of npm 6 with `npm i -g npm@6` since you're using node 8 and that's the latest version compatible. if you're able to update your node to at least 10, you can also try `npm i -g npm@7`.

after updating, feel free to open a new issue if your problem continues
