### ISSUE TITLE
[BUG] npm ignores  --package-lock-only flag

### ISSUE THREAD

**Issue by stereobooster** [npm/cli#2538]
### Current Behavior:
When I run `npm install --package-lock-only immer` it updates both `package.json` and `package-lock.json`

### Expected Behavior:
When I run `npm install --package-lock-only immer` it updates only `package-lock.json`

### Steps To Reproduce:

1. `npm install --package-lock-only immer`

### Environment:

- OS: MacOS version 10.15.7 
- Node: v14.15.1
- npm: 6.14.11

**Comment by rvillane** [comment]
I'm also experiencing this same issue in NPM 7

`npm install --package-lock-only commander`

is updating both package-lock and package.json

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
