### ISSUE TITLE
[BUG] On Linux latest npm hangs

### ISSUE THREAD

**Issue by crystalfp** [npm/cli#2575]
### Current Behavior:
On linux even a simple `$ npm` hangs for ~ 70 sec with no sign where it is hanging:
```
$ npm --verbose
npm verb cli [
npm verb cli   '/home/mvalle/node-v15.7.0-linux-x64/bin/node',
npm verb cli   '/home/mvalle/bin/npm',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.4.3
npm info using node@v15.7.0
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:/home/mvalle/node-v15.7.0-linux-x64/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/home/mvalle/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/home/mvalle/node-v15.7.0-linux-x64/etc/npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 8ms
npm verb npm-session 633bd37ff6877cf5
npm timing npm:load Completed in 19ms <<<--- here it hangs

Usage: npm <command>
...
```

I aborted a `npm i` with no `node_modules` and no `.npmrc` after 10 minutes showing:
 `idealTree:AMDIdeaIgniterEnvironment: sill idealTree buildDeps`

### Expected Behavior:
That it works, as was doing with node 14 and node 15.5.1. Or at least offer some more precise debug message. Could be that something has changed in the network configuration, but have no way to see what or where is hanging.

### Steps To Reproduce:
1. from the prompt run npm
2. wait

### Environment:
- OS: Ubuntu 20.04.2 LTS 
- Node: 15.7.0
- npm: 7.4.3

**Comment by crystalfp** [comment]
Solved by defining in `.npmrc`
```
registry = http://registry.npmjs.org
```
Why is this value needed to show npm help?

**Comment by lubomirblazekcz** [comment]
I had similar issue on Ubuntu 20.10, in my case every HTTP fetch hanged, so simple install that should took 4s took 2m. In my case it was caused by docker. After uninstalling docker snap and removing docker bridge adapter with `sudo ip link del docker0` everything started working correctly again. `sudo lshw -class network -short && nmcli device status` shouldn't show docker adapter here.

This drived me nuts, I had no idea what was causing it, propably wasn't even problem with npm, but with network in ubuntu. Maybe some kind of combination of docker, ubuntu, vmware - I don't really know. This had to happen with some update (ubuntu, docker, node - who knows), because I don't remember having these issues few months ago.

So if anyone faced this issue, when npm totally unexplainly hangs on network during install. This was it!

EDIT: installing docker again fixed the issue for me
