### ISSUE TITLE
[BUG] Difficulty setting NPM_CONFIG_ environment variable for scoped registry 

### ISSUE THREAD

**Issue by robross0606** [npm/cli#2576]
### Current Behavior:
I have need to use a scoped registry set in an environment variable for a CI pipeline.  The problem is that scoped registries use special characters `@` and `:` in the variable name.  
```
NPM_CONFIG_@namedscope:registry=...
```

This is problematic, especially when attempting to pass that variable on to a Docker `build-arg`.

Is there an alternate syntax or a way to escape the scoped registry variable name so it can be passed as an environment variable?

### Expected Behavior:
There should be an effective way to specify scoped registries as an `NPM_CONFIG_` environment variable.

### Steps To Reproduce:
Attempt to set up an `NPM_CONFIG_` environment variable specifying a scoped registry.

### Environment:
All.  Problematic in Windows and Linux and especially dockerconfig.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
