### ISSUE TITLE
INIT_CWD does not get reset if `npm install` is invoked by another npm script

### ISSUE THREAD

**Issue by jsg2021** [npm/cli#2578]
> @Geod24 The tests are in https://github.com/npm/config/commit/707088535f66c63e39dde7544b8f0dc7194e51a5  This is a bug in @npmcli/config, not in the cli itself.

_Originally posted by @isaacs in https://github.com/npm/cli/issues/2033#issuecomment-745434656_

This is maybe more of a question. But I was surprised by the fact INIT_CWD retained the parent process's value when a post-install script installed a child-directory project...

**Comment by isaacs** [comment]
Hm, yes, it appears that I misread the npm v6 behavior.

**Comment by mathiaswillburger** [comment]
How is INIT_CWD accessed now? I used it in my scripts on Windows like this, which always worked in version 6, but now doesn't anymore:

```
"scripts": {
    "format": "prettier-eslint --write %INIT_CWD%/src/**/*.{js,jsx}",
  },
```

I am using npm v7.5.3

**Comment by jsg2021** [comment]
> How is INIT_CWD accessed now? I used it in my scripts on Windows like this, which always worked in version 6, but now doesn't anymore:
> 
> 
> 
> ```
> 
> "scripts": {
> 
>     "format": "prettier-eslint --write %INIT_CWD%/src/**/*.{js,jsx}",
> 
>   },
> 
> ```
> 
> 
> 
> I am using npm v7.5.3

If your shell is bash for windows:

```
"scripts": {
    "format": "prettier-eslint --write $INIT_DIR/src/**/*.{js,jsx}",
 },
```

But you shouldn't need that, just use "./src..."

**Comment by mathiaswillburger** [comment]
Thanks @jsg2021 for the fast response.

You are obviously right that the easiest solution would be to use `./src`. Unfortunately, `prettier-eslint-cli` requires an absolute path as parameter and does not accept relative paths to initialize it via npm scripts. Otherwise, it throws the error `[ERR_ASSERTION]: 'basePath' should be an absolute path.`

Using `$INIT_DIR` also does not work in version 7.5.3. For some reason, it does not get resolved. Neither do any of the other options like `%INIT_CWD% $INIT_CWD $INIT_DIR %INIT_DIR% $PWD %PWD%`

However, I finally found a workaround using `cross-env-shell` which resolves the paths correctly:

```
"scripts": {
    "format": "cross-env-shell prettier-eslint --write  %INIT_CWD%/src/**/*.{js,jsx}",
 },
```
