### ISSUE TITLE
[BUG] ENOENT: no such file or directory, open

### ISSUE THREAD

**Issue by maksimr** [npm/cli#2590]
```
node --version  
v14.15.3
npm --version  
6.14.9
```

STR:

```sh
mkdir -p /tmp/p/zoo && cd  /tmp/p/zoo && npm init -y \
&& mkdir -p /tmp/p/bar && cd  /tmp/p/bar && npm init -y && npm install ../zoo \
&& mkdir -p /tmp/p/foo && cd  /tmp/p/foo && npm init -y && npm install ../zoo ../bar
```

```sh
 cd  /tmp/p/foo && npm ci
```

```
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /private/tmp/p/foo/node_modules/bar/node_modules/zoo/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/private/tmp/p/foo/node_modules/bar/node_modules/zoo/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Maybe relates to https://github.com/npm/cli/issues/529

**Comment by maksimr** [comment]
The problem with local packages. When you try to install local package `bar` which has as a dependency another  local package `zoo` inside package `foo` you would get an error. If open `node_modules` you can see that `npm ci` create broken symlink  `/private/zoo` but should be `/private/tmp/p/zoo`

![image](https://user-images.githubusercontent.com/616193/106513199-adbb0200-64e3-11eb-8330-21cbb4984b3a.png)

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
