### ISSUE TITLE
[BUG] fresh npm install is stuck

### ISSUE THREAD

**Issue by sancelot** [npm/cli#2594]
i setted up npm from node binary in linux system running in virtualbox environment.

I can run node -v, but any npm command does not return.
I can sea the right npm command using which npm

it looks like a kernel bug is generated each time I am running it :
![image](https://user-images.githubusercontent.com/122811/106610261-d59f7980-6566-11eb-9475-2b9e3b6aa19f.png)

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
