### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by alizadeh-mohsen** [npm/cli#2604]
just installed angular and tried to create my first new app but faced errors during project preparation 
I've attached log file for your review 
AND I WAS TOO SAD WHEN I FOUND OUT THAT IRAN IS RESTRICTED  BY YOUR WEBISTE, I HAD TO USE A VPN.

**Comment by ljharb** [comment]
There's no log file attached. Note, though, that if the `npm install` completes, everything after that is typically related to your project, and not to npm.

#417.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
