### ISSUE TITLE
[BUG] team rm/destroy: Unexpected end of JSON input while parsing near ''

### ISSUE THREAD

**Issue by stoneman** [npm/cli#2605]
### Current Behavior:
The `npm team rm` and `npm team destroy` error with `Unexpected end of JSON input while parsing near ''`. They do however remove the user or destroy the team successfully.

Full output of a `destroy` command (`rm` is the same):
```
npm ERR! Unexpected end of JSON input while parsing near ''

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonathan/.npm/_logs/2021-02-03T08_37_55_762Z-debug.log
```

### Expected Behavior:
They don't print an error.

### Steps To Reproduce:
1. `npm team create <my-org>:<my-team>`
1. `npm team add <my-org>:<my-team> <my-user>`
1. `npm team ls <my-org>:<my-team>` - shows that team contains user
1. `npm team rm <my-org>:<my-team> <my-user>`
1. `npm team ls <my-org>:<my-team>` - shows that team does not contain user
1. `npm team destroy <my-org>:<my-team>`
1. `npm team ls <my-org>:<my-team>` - 404 error shows team was destroyed

### Environment:
OS: MacOS 10.15.7 
Node: 8.17.0 & 12.20.0
npm 6.14.8

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
