### ISSUE TITLE
Dependencies of package published to Github Package Registry are not loaded from npmjs

### ISSUE THREAD

**Issue by chriskinsman** [npm/cli#2617]
### Current Behavior:
I have a scoped package published to GitHub Package registry with a package.json that contains two dependencies.  When I attempt to install it I get an error about not being able to load one of the dependencies of the scoped package.  npm is attempting to load the dependency which has no scope from the same registry that the containing package is loaded from.

### Expected Behavior:
I would expect npm to load @chriskinsman/mypackage from npm.pkg.github.com and to load the non-scoped dependencies inside mypackage from registry.npmjs.org

### Steps To Reproduce:
Create a project with package.json:
```
"dependencies": {
  "aws-sdk": "^2.0.0-rc11",
  "async": "^0.2.10",
  "lodash": "^4.17.5"
}
```
Publish the package as @owner/package name to github package registry

Create a consuming project with a scoped .npmrc:
```
//npm.pkg.github.com/:_authToken=XXXXXXXXXXXXXXXXXX
scope=@owner
@owner=https://npm.pkg.github.com/
registry=https://registry.npmjs.org/
always-auth=true
```

npm i @owner/mypackage

Get the following error:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.pkg.github.com/async
npm ERR! 404 
npm ERR! 404  'async@^0.2.10' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@owner/mypackage'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

### Environment:
- OS: MacOs 11.x
- Node: 14.15.4
- npm: 6.14.11

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
