### ISSUE TITLE
[BUG] npm installs old versions of eslint-plugin-vue

### ISSUE THREAD

**Issue by TheDutchCoder** [npm/cli#2621]
### Current Behavior:

npm install with the following configuration, installs a random old version of the plugin:
`"eslint-plugin-vue": "^7.0.0-0",`
npm install either `7.4.1` (standard) or `7.2.0`(cache cleared)

Neither is right (7.5.0 should be installed)

### Expected Behavior:

The correct plugin to be installed

### Steps To Reproduce:
Add the dependency and run `npm install`

### Environment:

MacOS 11.1
Node: 12.19.0
npm: 6.14.10

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
