### ISSUE TITLE
[BUG] invalid version when set version as dist-tag in package-lock file 

### ISSUE THREAD

**Issue by zWingz** [npm/cli#2629]
### Current Behavior:

i set version as dist-tag in `package.json` and `package-lock.json`
```json

"my-package": {
      "version": "beta",
      "requires": {
        "qs": "^6.9.1"
      },
}
```

and then `npm ci`

it throw error
![image](https://user-images.githubusercontent.com/13031838/107021570-4355da80-67df-11eb-9365-8cc55dd82508.png)

### Expected Behavior:

install it

it work in npm@6

### Environment:

macOS 11.2
npm 7.5.2

**Comment by darcyclarke** [comment]
@zWingz hmm, I don't know how this might have happened since it seems like you'd have to hand-edit the `package-lock.json` to get into this state, as `version` as a `dist-tag` value works if it's just the root `package.json` value; That said, you should always be using a valid `semver` value as your `version`, so a recommendation here might be `0.0.1-beta` or anything akin to that.

**Comment by zWingz** [comment]
hi @darcyclarke 
i install the dependence by `npm install file://../path/to/dep` in development,
and i will replace `file://../path/to/dep` to `beta` in `package.json` to install `dep@beta`

```bash
sed -i "s/file:..\/dep/beta/g" package.json
sed -i "s/file:..\/dep/beta/g" package-lock.json
```

so i need to install dep use `dist-tag` and it work in `npm@6`

**Comment by zWingz** [comment]
@darcyclarke 
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies
![image](https://user-images.githubusercontent.com/13031838/109099860-c45d1d80-775e-11eb-951a-0e86c3b25bf0.png)
