### ISSUE TITLE
[BUG] Installing a package from a tarball from GitHub does not respect the `files` property in `package.json`

### ISSUE THREAD

**Issue by papb** [npm/cli#2648]
### Current Behavior:
Installing a package from a tarball from GitHub does not respect the `files` property in `package.json`

### Expected Behavior:
The `files` property should be respected

### Steps To Reproduce:
1. `npm init -y`
2. `npm i https://github.com/sequelize/sequelize/tarball/main`
3. `ls node_modules/sequelize`
4. See that all files were installed, instead of respecting [the `files` option within `package.json`](https://github.com/sequelize/sequelize/blob/main/package.json#L26-L31)

### Environment:

- OS: Windows
- Node: 12.14.1
- npm: 6.14.11

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
