### ISSUE TITLE
[BUG] --only=dev misbehaving; installing all deps

### ISSUE THREAD

**Issue by Fyko** [npm/cli#2671]
### Current Behavior:
When running `npm install --only=dev`, it installs all dependencies.

### Expected Behavior:
Only dev dependencies should be installed.

### Steps To Reproduce:
1. Run `npm i --only=dev`
2. Observe the `node_modules` folder seeing all dependencies have been installed.

### Environment:
- OS: Ubuntu 20.04
- Node: 15.8.0
- npm: 7.5.3

**Comment by isaacs** [comment]
This is tricky to do, and was dropped from v7, but there's no real fundamental reason why it can't be brought back.

It's tricky because we don't track in the lockfile (or anywhere else at this time) whether a production dependency is required as a dependency of some devDependencies.  For example, you might have this dependency graph:

```
root -> (a@1) DEV(b@1)
b@1 -> (a@1)
```

In the tree, we lay it out like this:

```
root
+-- a (dev=false)
+-- b (dev=true)
```

If we install "only the deps with dev=true", then `b` will not function, because it needs `a`.  We don't track a flag to indicate that something is not dev dep, but a dependency of dev deps.

If we want to support `npm install --only=dev` (as well as `npm prune --only=dev` and friends), then there are two basic approaches:

1. Build out the tree, and then walk over it multiple times to create a list of all the non-dev deps that do not have any incoming dependencies from dev deps.
2. Add a new field `devMeta`, which we calculate in the current single-pass calcDepFlags step.

(2) is hard, because it means that we'll have to bloat the package-lock.json, and also will have to know to walk over existing lockfiles to calculate that field.

(1) is just slow, but at least it's only slow in the rare situations where you _don't_ want production dependencies to be installed.
