### ISSUE TITLE
[BUG] npm i webpack-cli / npm ERR! cb() never called!

### ISSUE THREAD

**Issue by asamir2007** [npm/cli#2680]
### Current Behavior:
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-02-11T20_18_01_929Z-debug.log

### Steps To Reproduce:
in phpstorm terminal run:
H:\dev_php\OSPanel\domains\localhost\ct\prod-example\working\wireframe>npm i webpack-cli

### Environment:
- OS: WIndows 8.1
  npm: '6.14.11',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.15.5',

[2021-02-11T20_18_01_929Z-debug.log](https://github.com/npm/cli/files/5968339/2021-02-11T20_18_01_929Z-debug.log)

**Comment by getsetgopi** [comment]
I'm also getting the same error.
OS: Windows 10
Node: 14.15.4
NPM: 6.14.10
[2021-02-22T18_04_17_803Z-debug.log](https://github.com/npm/cli/files/6024911/2021-02-22T18_04_17_803Z-debug.log)

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
