### ISSUE TITLE
[BUG] Package named `@scope/authentication` cannot add/rm dist-tag

### ISSUE THREAD

**Issue by hansl** [npm/cli#2686]
Note: Unsure if this is a CLI bug or a registry bug.

### Current Behavior:
We have a `@dfinity/authentication` package published publicly on NPM and we cannot remove or add dist tags to its versions. The return is 400 Bad Request. Other packages in `@dfinity` scope work fine.

Logs:

```
$ npm --verbose dist-tag add @dfinity/authentication@0.6.23 latest
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/Users/hansl/.nvm/versions/node/v12.18.3/bin/node',
npm verb cli   '/Users/hansl/.nvm/versions/node/v12.18.3/bin/npm',
npm verb cli   '--verbose',
npm verb cli   'dist-tag',
npm verb cli   'add',
npm verb cli   '@dfinity/authentication@0.6.23',
npm verb cli   'latest'
npm verb cli ]
npm info using npm@6.14.11
npm info using node@v12.18.3
npm verb npm-session 24af3c5099475576
npm verb dist-tag add latest to @dfinity/authentication@0.6.23
npm http fetch GET 200 https://registry.npmjs.org/-/package/@dfinity%2fauthentication/dist-tags 318ms
npm http fetch PUT 400 https://registry.npmjs.org/-/package/@dfinity%2fauthentication/dist-tags/latest 178ms
npm verb stack Error: 400 Bad Request - PUT https://registry.npmjs.org/-/package/@dfinity%2fauthentication/dist-tags/latest
npm verb stack     at /Users/hansl/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:117:15
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm verb statusCode 400
npm verb pkgid @dfinity/authentication@0.6.23
npm verb cwd /Users/hansl/Sources/dfinity/agent-js
npm verb Darwin 20.3.0
npm verb argv "/Users/hansl/.nvm/versions/node/v12.18.3/bin/node" "/Users/hansl/.nvm/versions/node/v12.18.3/bin/npm" "--verbose" "dist-tag" "add" "@dfinity/authentication@0.6.23" "latest"
npm verb node v12.18.3
npm verb npm  v6.14.11
npm ERR! code E400
npm ERR! 400 Bad Request - PUT https://registry.npmjs.org/-/package/@dfinity%2fauthentication/dist-tags/latest
npm verb exit [ 1, true ]
npm timing npm Completed in 778ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hansl/.npm/_logs/2021-02-12T20_06_22_095Z-debug.log
```

### Expected Behavior:
This should update the dist-tag to the proper version.

### Steps To Reproduce:
```
npm --verbose dist-tag add @dfinity/authentication@0.6.23 latest
```

### Environment:
`uname -a`: Darwin iMac-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

`node --version`: v12.18.3 (note: was also reproduced on 14)

`npm -v`: 6.14.11

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
