### ISSUE TITLE
[BUG] Hook Scripts Not Run on `npm install`

### ISSUE THREAD

**Issue by karlhorky** [npm/cli#2692]
First of all, thanks for all of the work being done on the npm CLI and the ecosystem! Tons of new amazing things in v7.

### Current Behavior:

Hook scripts (documented [in the docs here](https://docs.npmjs.com/cli/v7/using-npm/scripts#hook-scripts)) seem to no longer get run for npm v7.

For example, an executable file at `node_modules/.hooks/postinstall` with the following contents not get run:

```js
#!/usr/bin/env node
console.log('ran hook');
```

I also tried this:

```sh
#!/usr/bin/env bash
echo 'ran hook'
```

This will not get run during `npm install` or `npm install <pkg name>`

### Expected Behavior:

The hook scripts should be run

### Steps To Reproduce:

1. Create a new package with one of the file contents above in an executable file under `node_modules/.hooks/postinstall`
2. Run `npm install`
3. Hook script does not get run

### Environment:

- OS: macOS 11.2.1
- Node: 15.8.0
- npm: 7.5.4

### Alternatives considered

Maybe Hook Scripts are no longer supported? In this case, they should be removed from the documentation.

**Comment by Goobles** [comment]
`npm install` has become more "[silent](https://github.com/npm/rfcs/blob/latest/implemented/0022-quieter-install-scripts.md)" and doesn't output the stdout of your scripts during installation.
Your hook script might or might not be executing without you knowing it. Verify by writing something to a logfile in your script instead of using `echo`

**Comment by augustobmoura** [comment]
I can confirm that lifecycle hooks do not run, this is probably a regression and is impacting our users in [asdf-nodejs](//github.com/asdf-vm/asdf-nodejs). There's any work on going to fix this?

**Comment by RussCoder** [comment]
In my case `install` and `postinstall` hooks work, but no logs are printed to the console. I use npm 7.11.1
But `preuinstall` and `uninstall` hooks don't work at all. 

Actually, it would be nice if logs were printed to the console, because there can be useful messages for the user. Especially, the messages which are printed by the `postinstall` script.

npm can be silent in case of its own logs, but I think it's logical to print all messages from user-defined scripts.

**Comment by ljharb** [comment]
@RussCoder the entire reason npm 7 changed this was to prevent user-defined scripts from injecting ads into people's terminals.

**Comment by augustobmoura** [comment]
`install` and `postinstall` script fields in package.json still works, the issue is with `postinstall` script files in the directory `node_modules/.hooks` that should run for every package. Still not working in the latest version. @ljharb do you think this is a issue that needs of arborist or the npm cli? I'm thinking about giving a try in solving it, I saw that arborist has some code for hooks but I didn't went too deep

**Comment by wraithgar** [comment]
`node_modules/.hooks` was removed from the docs in the cli repo, and the docs site will reflect when it next rebuilds and deploys.

**Comment by karlhorky** [comment]
Ok thanks @wraithgar !
