### ISSUE TITLE
[BUG] Wrong dependency resolution failure in clean install

### ISSUE THREAD

**Issue by falsandtru** [npm/cli#2695]
typescript@">= 2.8" must match typescript@4.3.0-dev.20210213, right? This error doesn't appear on npm6. Additionally, npm7 can't run `npm r` to remove unresolvable dependencies.

### Current Behavior:
```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: spica@0.0.433
npm ERR! Found: typescript@4.3.0-dev.20210213
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"4.3.0-dev.20210213" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@">= 2.8" from tsify@5.0.2
npm ERR! node_modules/tsify
npm ERR!   dev tsify@"^5.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Expected Behavior:
no error

### Steps To Reproduce:
1. Checkout https://github.com/falsandtru/spica v0.0.434
2. Run npm i 

### Environment:
- OS: Win10
- Node: 15.8.0
- npm: 7.5.4

**Comment by falsandtru** [comment]
.npmrc

```
package-lock = false
```

**Comment by nlf** [comment]
your dependency `tsify` has a peer dependency on `typescript@">= 2.8"` however your package is directly depending on `typescript@4.3.0-dev.20210213` which is a conflict.

to get around this, you can either run `npm i --force` to ignore the conflicts and install anyway, update your `tsify` dependency to one that has a peerDependency on a matching version of typescript, or change your top level typescript dependency to one that is compatibly with `tsify`

the reason you don't see this problem in npm 6 is because installing peerDependencies by default is new in npm 7

**Comment by falsandtru** [comment]
Ah, thanks...
