### ISSUE TITLE
[BUG] --prefix glob paths not expanded on Windows

### ISSUE THREAD

**Issue by achingbrain** [npm/cli#2734]
### Current Behavior:

Glob paths passed as the `--prefix` argument to `npm run-script` are not expanded on Windows.

I have a project that uses workspaces.  I have a script `npm test --prefix packages/*`.  This works on Linux/Mac OS.  On Windows I get:

```
> my-project@1.0.0 test
> npm test --prefix packages/*

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\alex\Documents\Workspaces\achingbrain\my-project\packages\*/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\alex\Documents\Workspaces\achingbrain\my-project\packages\*\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Maybe the shell is doing the expansion on Linux/Mac OS?  It should use some sort of glob library really.

### Expected Behavior:

It should work cross-platform.

### Steps To Reproduce:

Use glob paths as the `--prefix` argument to `npm run-script` on the Windows platform.

### Environment:

- OS: Windows 10
- Node: 15.9.0
- npm: 7.5.4

**Comment by nlf** [comment]
we don't do glob expansion of the prefix anywhere. it works in linux and mac os because, as you noted, the shell does the expansion for you. the `prefix` config is only intended to have one value, so accepting a glob there doesn't make much sense. in addition to that, our workspace support is evolving and this will be done in a much more deliberate way in the future (i.e. a workspace specific config rather than using `prefix`).

you should try updating to the latest npm (7.9.0) and check out the docs for `npm run-script` as i think the workspace support will address this problem for you nicely. if you have problems after that, please open a new issue!

**Comment by achingbrain** [comment]
> i think the workspace support will address this problem for you nicely

Do you mean this? https://docs.npmjs.com/cli/v7/commands/npm-run-script#filtering-workspaces

I can’t see anything in there about wildcard support, did I miss something?

**Comment by nlf** [comment]
We apparently didn't document it, but yes, it accepts a glob and will match on it

**Comment by achingbrain** [comment]
Great, I’ll give that a go - thanks!
