### ISSUE TITLE
[BUG] cb error, dependency issue

### ISSUE THREAD

**Issue by Iril** [npm/cli#2738]
### Current Behavior:
When building a npm project in Jenkins using an Artifactory Repository getting a cb () never called error.
npm info using npm@6.14.11
npm info using node@v14.15.5

After upgrading to npm v7 now causes a dependency issue. 
npm info using npm@7.5.3
npm info using node@v15.9.0

When using the npm. registry this issue does not appear. 

### Expected Behavior:
Build should complete normally as the build is used repeatedly externally without issue

### Steps To Reproduce:
1. Download the source from github / bitbucket
2. Run the npm install for this project in Jenkins
3. Build fails with the following error at the end of the build
4. npm timing npm Completed in 529602ms
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     Y:\Jenkins\cache\npm-cache\_logs\2021-02-19T03_22_33_566Z-debug.log

### Environment:
Windows Jenkins Master ( WIndows 2008 )
Windows Jenkins Slave ( Windows 2016 )
JFrog Artifactory Pro ( registry ) running version 6.21.0 ( No anonymous access )

Failing with cb error : 
npm info using npm@6.14.11
npm info using node@v14.15.5

Failing with Dependency Error
npm info using npm@7.5.3
npm info using node@v15.9.0

LogFile 1 - CB Error
LogFile 2 - Dependency Error

[LogFile.1.zip](https://github.com/npm/cli/files/6013798/LogFile.1.zip)
[LogFile.2.zip](https://github.com/npm/cli/files/6013799/LogFile.2.zip)

npmrc

#
# This file should be installed on all Windows Nodes on Startup in Jenkins in Production
#

cafile=Y:\Jenkins\tools\NodeJS\certs\Private.crt
#prefix=X:\npm
cache=Y:\Jenkins\cache\npm-cache
# globalignorefile=Y:\Jenkins\tools\NodeJS\npmignore
# init-module=Y:\Jenkins\tools\NodeJS\.npm-init.js
tmp=C:\Windows\Temp
registry=https://artifactory/api/npm/npm/
auth-type=sso
always-auth=true
_auth="An Awesome Secret Password"
loglevel=info

**Comment by wraithgar** [comment]
https://github.com/npm/cli/issues/417

**Comment by nlf** [comment]
the dependency error you got, is this (copy/paste from logs)

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: dotstatsuite-data-explorer@7.0.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.11.0" from the root project
npm ERR!   peer react@"^16.0.0 || ^15.0.1 || ^0.14" from @blueprintjs/core@1.40.0
npm ERR!   node_modules/@blueprintjs/core
npm ERR!     @blueprintjs/core@"^1.35.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.4.2" from react-addons-css-transition-group@15.6.2
npm ERR! node_modules/react-addons-css-transition-group
npm ERR!   react-addons-css-transition-group@"^15.6.2" from the root project
npm ERR!   peer react-addons-css-transition-group@"^15.0.1 || ^0.14" from @blueprintjs/core@1.40.0
npm ERR!   node_modules/@blueprintjs/core
npm ERR!     @blueprintjs/core@"^1.35.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See Y:\Jenkins\cache\npm-cache\eresolve-report.txt for a full report.
```

this is caused because you have `react-addons-css-transition-group@15.6.2` in your tree, which depends on `react@"^15.4.2"` while at the root of your project you have installed `react@"^16.11.0"` which is incompatible.

to resolve that you'd either have to update to a version of react-addons-css-transition-group that has a peerDependency on a compatible range of react, or follow the suggestion at the bottom of the error message and try the command again with either `--force` or `--legacy-peer-deps`.

the cb not called issue is generally a transient failure of some kind, but if it's consistently reproducible in the latest npm (7.9.0 as of this moment) then definitely open a new issue specifically for that with as much information as you can give us to reproduce it. an example repo that exhibits the broken behavior would be ideal.
