### ISSUE TITLE
Documentation Style

### ISSUE THREAD

**Issue by MrBrain295** [npm/cli#2767]
Is there any specific style in place for the npm documentation? If not wouldn’t it help to have one?

**Comment by darcyclarke** [comment]
Not sure what you mean by "style" but we do have some basic styling applied to the docs that ship with the CLI itself (ref. https://github.com/npm/cli/blob/latest/docs/template.html). The docs.npmjs.com website isn't public/OSS *yet* but once it is you can open issues/PRs to update it's styling as well. In general, the content of the CLI-specific command docs (found here: https://github.com/npm/cli/blob/latest/docs/content/commands/) follow `man`-doc style so that we can generate `man`-docs from them as well as HTML docs (see https://www.npmjs.com/package/marked-man - the package we use). 

If you have any feedback or ideas on changes to the project (docs, website, registry etc.), definitely feel free to add them here: https://github.com/npm/feedback
