### ISSUE TITLE
npm ERR! prepareGitDep 

### ISSUE THREAD

**Issue by Quintis1212** [npm/cli#2769]
Hello ) I installed fedora and node but cant install node_modules to work with the gutenberg plugin -https: //github.com/WordPress/gutenberg
npm 6.14.11
node 14.16.0
package.json says that npm <7 version should be
Is there anyone who runs gutenberg on fedora? help me please
package.json - https://jsfiddle.net/x72dv0yt/

![Снимок экрана от 2021-02-24 11-56-10](https://user-images.githubusercontent.com/34488718/108989943-daa3a480-769e-11eb-9dd2-cf946ec3591c.png)
![Снимок экрана от 2021-02-24 11-56-35](https://user-images.githubusercontent.com/34488718/108989960-e000ef00-769e-11eb-8b5f-64c988957e0a.png)
![Снимок экрана от 2021-02-24 11-56-56](https://user-images.githubusercontent.com/34488718/108989969-e42d0c80-769e-11eb-9558-a53be899e410.png)

**Comment by Quintis1212** [comment]
git version 2.29.2

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
