### ISSUE TITLE
[BUG] npm resolves the wrong dist-tag of a package dependency

### ISSUE THREAD

**Issue by ktalebian** [npm/cli#2794]
### Current Behavior:

I have a package `flex-plugin-scripts` that currently has a `beta` dist build (as well as a `nightly` dist):

```
➜ npm info flex-plugin-scripts
...
dist-tags:
alpha: 4.4.1-alpha.2             dev: 4.4.0-dev.202102270122      next: 4.8.1-alpha.0
beta: 4.4.0-beta.0               latest: 3.14.5                   nightly: 4.4.0-nightly.20210227
```

This package depends on another package called `flex-plugin` which is part of a monorepo of the same version https://github.com/twilio/flex-plugin-builder/blob/v4-beta/packages/flex-plugin-scripts/package.json#L52. This package too, has the same dist-tags:

```
➜ npm info flex-plugin
...
dist-tags:
alpha: 4.4.1-alpha.2             canary: 0.1.2-alpha.0            latest: 3.14.2                   nightly: 4.4.0-nightly.20210227
beta: 4.4.0-beta.0               dev: 4.4.0-dev.202102270122      next: 4.6.2-alpha.0
```

When I `npm install flex-plugin-scripts@beta` I expect the latest of the `beta` dist tag of both packages `flex-plugin-scripts` and `flex-plugin` to be installed, but the latest dist tag by date published (which is the nightly build) is installed. 

I installed `npm install flex-plugin-scripts@beta` and then I did:

```
➜ grep version node_modules/flex-plugin/package.json
  "version": "4.4.0-nightly.20210227"
```

Why is npm resolving the nightly build here and not the `beta` of this child package? I reckon this is because both the `beta` and `nightly` are of version `4.4.0` and so npm is resolving by date published? 

### Environment:
- Mac: 10.15.7
- Node: 12.18.3
- npm: 7.6.0

**Comment by nlf** [comment]
we resolve the dependencies based on what's in the package.json of the dependency, not what you specified when installing.

when you `npm install flex-plugin-scripts@beta` we read the package and determine the version tagged `beta`, which at the time of writing is now `4.6.0-beta.0`. we then fetch that package and inspect its dependencies, you can do this yourself by running `npm show flex-plugin-scripts@beta --json` where you'll see that particular version of flex-plugin-scripts depends on `flex-plugin@^4.6.0-beta.0` so that's the version we install.

circling back to your version of flex-plugin-scripts, which at the time resolved to `4.4.0-beta.0` if you run `npm show flex-plugin-scripts@4.4.0-beta.0 --json` you'll see it depends on `flex-plugin@^4.4.0-beta.0`

semantic versioning tells us that the pre-release field (i.e. the `-nightly.20210227` and the `-beta.0`) is used as an indicator that we should use the same major, minor and patch, but allow for the newest pre-release. if you run `npm show flex-plugin@^4.4.0-beta.0 version` you'll see a list of versions matching that range. we resolved the request to the latest one, which is the nightly release you ended up getting installed.

this is very much working as intended, and i hope the explanation was helpful.

**Comment by ktalebian** [comment]
@nlf thank you for the information. 

But what if I want to have completely separate pre-releases tags?  i.e. have `nightly` and `beta`, but if I specify a `*-beta` pre-release, it should only resolve packages that are of the same pre-release tag. 

Is there a different way to publish these packages to npmjs or is this feature not supported? Does this effectively mean you can only have one pre-release tag at any point?

**Comment by nlf** [comment]
this is done in the dependencies field of the package that consumes the others.

so let's say you have package A and it depends on package B, you've release 1.0.0 of each and that is tagged as `latest` and now you want to start working on a `beta` of 2.0.0 for each.

you would publish B@2.0.0-beta.0 and tag that as `beta`

then you would change the package.json for A so that the dependency looks like `"B": "beta"`, and now publish. when you install A we will look up the dist-tag of the dependency and retrieve the appropriate version.

there is no way to tell npm to install a package and all of its dependencies using a given tag because we use the dependencies stated in the package.json for everything we install as a dependency of a package.
