### ISSUE TITLE
[BUG] NPM completion not working on Git Bash shell using Windows Terminal (MSYSTEM different)

### ISSUE THREAD

**Issue by ciarancourtney** [npm/cli#2797]
### Current Behavior:
Open a git-for-windows bash shell in Windows Terminal (wt) and run `npm completion`

### Expected Behavior:
Bash completion is output to stdout

### Steps To Reproduce:
1. Install git for windows and Windows Terminal
2. Add a config in json as per https://stackoverflow.com/questions/56839307/adding-git-bash-to-the-new-windows-terminal
3. Open 'git bash' shell and try  `npm completion`

From looking at code, npm checks `MSYSTEM`, which in native 'git bash' begins `MINGW`, but in wt its `MSYS`.

This may be a problem with wt's integration with git bash, but worth adding as a case, since msys2 could be another valid shell on Windows that supports GNU Bash. 

### Environment:

- OS: Windows 10
- Node: 14lts
- npm: 7.6.0

**Comment by nlf** [comment]
there's an answer in the linked stackoverflow page that mentions this, but there are a couple of `bash.exe` files included with git bash, some will set MSYSTEM to the correct MINGW value, some do not

> Something to note is that I have run into issues using Git\usr\bin\bash.exe. It seems that the one in the usr folder is missing some environment variables. In my case, I was having issues with git-upload-pack, required for the deploy command for gh-pages on NPM. Instead, using Git\bin\bash.exe fixed all my $PATH related issues. – matthew-e-brown Jun 23 '20 at 15:05

my advice would be to edit your settings and change your profile in windows terminal so that instead of

```
"commandline": "%PROGRAMFILES%/git/usr/bin/bash.exe -i -l",
```

you have (note the removal of `/usr`)

```
"commandline": "%PROGRAMFILES%/git/bin/bash.exe -i -l",
```

which i can confirm sets the appropriate environment variables and allows things to work as you'd expect.
