### ISSUE TITLE
'eval' is not recognized as an internal or external command, operable program or batch file on windows npm script

### ISSUE THREAD

**Issue by s1mrankaur** [npm/cli#2953]
```
   $ npm run deploy:local
    
    > backend@0.1.0 deploy:local
    > eval "`aws-auth-helper vn-sandbox` lerna run deploy:sandbox --stream"
    
    'eval' is not recognized as an internal or external command,
    operable program or batch file.
```

Node version:

```
$ node --version
v15.11.0
NPM version:

$ npm --version
7.6.0
```

I am using VSCode Bash terminal. It had been working just fine but then I started getting this error. Have tried both the bash terminal and javascript terminal.

If I just type "eval" in the bash terminal, it works okay. While running through npm script it does not.

**Comment by nlf** [comment]
if you're running in Windows, the default shell we use to run scripts with is `cmd.exe` which does not have an `eval`. you can override this to use `bash` by running `npm config set script-shell=bash`

let me know if that works for you. admittedly there's an opportunity for a bit of enhancement here where we could potentially default to the currently running shell instead of an operating system specific one, but that's something we would have to take through our RFC process detailed here: https://github.com/npm/rfcs

**Comment by s1mrankaur** [comment]
That really worked! THANK YOU!!
