### ISSUE TITLE
[BUG] On npm init, the name of the folder from which the function is called only the first space gets replaced by a space

### ISSUE THREAD

**Issue by TopchetoEU** [npm/cli#2996]
### Current Behavior:
When I do `npm init` in a folder with spaces, for example `test foo bar`, only the first space gets replaced by a dash in the proposed name

### Expected Behavior:
All the spaces in the name of the folder should get replaced by a dash

### Steps To Reproduce:
1. Make a folder with more than one space in it's name
2. Do `npm init` in it

### Environment:
- OS: Windows 10 Build 19041.804
- Node: 12.18.2
- NPM: 7.7.6

**Comment by snitin315** [comment]
Hi, I would like to work on this issue if there are no objections.

**Comment by nickfryar** [comment]
@snitin315, I didn't seen your comment and had already started working on this. Sorry! :/

I've linked a pull request here: https://github.com/npm/cli/pull/3092

**Comment by snitin315** [comment]
No worries 😄

**Comment by DevanshGoswami** [comment]
@TopchetoEU I want to contribute on this and take it up as my first open source contribution. 😄

**Comment by TopchetoEU** [comment]
@DevanshGoswami im not the one responsible, but if you want, you could make a pull request with the fix. still, i think the issue is already fixed :/

**Comment by wyckster** [comment]
I observe this to be fixed in the wild in 7.20.6.  So I'm surprised this issue is still open. (Sorry, @DevanshGoswami)

<pre>
F:\repro>npm --version
7.20.6

F:\repro>mkdir "test foo bar"

F:\repro>cd "test foo bar"

F:\repro\test foo bar>npm init -y
Wrote to F:\repro\test foo bar\package.json:

{
  "name": "test-foo-bar",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
</pre>

Note the `name` written into package.json is `test-foo-bar` with dashes for all spaces.

**Comment by wraithgar** [comment]
I was also not able to replicate this in the latest npm.
