### ISSUE TITLE
Questions about `Email: (this IS public)`

### ISSUE THREAD

**Issue by wenfangdu** [npm/cli#3009]
I've configured the email address on `npmjs.com`, why does the cli keep prompting me to enter email?
```bash
$ npm login
npm notice Log in on https://registry.npmjs.org/
Username: wenfangdu
Password:
Email: (this IS public)
```
Even if I enter a wrong email that is different from the one I set on `npmjs.com`, I can still log in.

Questions:
- What's the point of entering this email? 
- Can it default to the email address I set on `npmjs.com` if I don't enter this field?

**Comment by lorenzogrv** [comment]
As you can see on [`npm-adduser` docs](https://docs.npmjs.com/cli/v7/commands/npm-adduser#description), `npm login` is just an alias for `npm adduser`

**Comment by wenfangdu** [comment]
@LocutusOfBorg Yes, but I didn't see the answer from the doc, could you please point it out?

**Comment by LocutusOfBorg** [comment]
-EWRONGUSER?

**Comment by nlf** [comment]
this is an artifact of a time when logging in and creating a user were the same request. that's no longer the case, so the email field is ignored unless logging in as the given user with the given password fails with an error indicating that user does not exist. if that happens we instead send a request to create the given user and associate it with the given email.

it's technical debt that we're aware of, as mentioned it's due to `login` actually being an alias for `adduser`. unfortunately changing this behavior would be a breaking change and require a semver-major version bump, so you won't see this until npm 8.
