### ISSUE TITLE
[BUG] `npm audit fix` does not fix as well as installing proper dependency directly

### ISSUE THREAD

**Issue by noneedinmagic** [npm/cli#3170]
### Current Behavior:
When I install package with vulnerable version of dependency it is impossible to fix it by audit or installing proper dependency directly.

### Expected Behavior:
Possibility to  install latest version of the vulnerable dependency to fix the issues.

### Steps To Reproduce:
1. Create a new pkg via `npm init`.
2. `npm i deep-email-validator`
3. After installing it you have a message about vulnerabilities. Double-check it by running `npm audit`.
```
# npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
No fix available
node_modules/axios
  deep-email-validator  *
  Depends on vulnerable versions of axios
  node_modules/deep-email-validator

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```
4. Double-check manually that in `node_modules/deep-email-validator/package.json` in dependencies section there is "^0.19.2" version for the axios dependency.
5. Run `npm audit fix`.
6. Nothing fixed.
7. Run `npm i axios@latest`.
8. Still having 2 high severity vulnerabilities.
9. ???????????
10. Still having no clue about how to fix the problem.

### Environment:

- OS: Windows 10 @latest
- Node: 12.18.0
- npm: 7.11.1

**Comment by nlf** [comment]
this is an interesting one and a bit of a nuance of semver, but the issue is that deep-email-validator needs to publish an update. i'll break it down a little bit here.

by looking at the advisory linked above (found here https://www.npmjs.com/advisories/1594) we can see that the remediation suggestion is
> Upgrade to 0.21.1 or later.

the dependency in deep-email-validator of `^0.19.2` looks like it would accept this, but this is where the nuances of semver come into play. there's some in depth explanation here https://github.com/npm/node-semver#caret-ranges-123-025-004

the example of
> ^0.2.3 := >=0.2.3 <0.3.0-0

in particular is of interest to us, as we can see here that the dependency of `^0.19.0` actually means `>= 0.19.0 < 0.20.0-0` which does not include the patched version. installing `axios@latest` as a top level package does not resolve this, because the conflicting semver ranges mean that we will now move `axios@^0.19.0` to be nested underneath deep-email-validator, keeping it in your tree.

the only way to fix this is to update to a version of deep-email-validator that depends on `axios@^0.21.1`, which at the time of this writing does not exist. you would need to open an issue with deep-email-validator and ask them to publish a new version that accepts the fixed version of axios, you can find where to open that issue by running `npm bugs deep-email-validator`
