### ISSUE TITLE
[BUG] npm publish --tag doesn't accept version

### ISSUE THREAD

**Issue by dcustodio** [npm/cli#3172]
### Current Behavior:

When publishing a new package passing the `--tag` flag and using a version like "1.0.0-pr-001"  I get the following error:

`npm ERR! Tag name must not be a valid SemVer range: 1.0.0-pr-001`

### Expected Behavior:

I would expect the publish to be successful as the version [is valid according to this regex](https://regex101.com/r/vkijKf/1/) 

### Steps To Reproduce:

1. `npm publish --tag 1.0.0-pr-001` 
### Environment:

- OS: mac bigSur
- Node: 15.13.0
- npm: 7.7.6

**Comment by nlf** [comment]
the `tag` is not a semver version, it's a simple string intended to allow the user to select a package based on a friendly string like `"latest"` or `"beta"`

because when we resolve packages we determine if you're asking for a version or a tag based on that string, it cannot be something that parses as semver because then we wouldn't know if we should use the tag, or use it as a semver range.

it sounds like perhaps what you want is to set your `"version"` in your package.json to `"1.0.0-pr-001"` (you can do this by running `npm version 1.0.0-pr-001`) and then run `npm publish` without the `--tag 1.0.0-pr-001`. if you do not specify a tag, we use the string `"latest"`.

**Comment by dcustodio** [comment]
Hi @nlf thank you so much for the input. I had already looked into the solution you propose as a workaround and know I know it's the way to go. 
The weird thing here is that the `npm publish --tag 1.0.0-pr-001` was working up until some weeks ago, could it be the case that something changed in the meanwhile?
