### ISSUE TITLE
npm lifecycle scripts such as 'prepare' not run when install from git repo

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#321]
Original bug ticket: [https://npm.community/t/10253](https://npm.community/t/10253)
      Originally filed: 2019-09-26T03:07:35.218Z

**Comment by ghost** [comment]
We had the same problem but it was caused by a missing `.npmignore`. We have a `.gitignore` file which excludes `dist` from Git (So that transpiled files are not included). Adding a blank `.npmignore` file made the files created by prepare remain, because [NPM uses .gitignore when .npmignore is missing](https://docs.npmjs.com/configuring-npm/package-json.html#files).
