### ISSUE TITLE
[BUG] Publish fails with HPE_INVALID_VERSION

### ISSUE THREAD

**Issue by futurethang** [npm/cli#3264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am attempting to publish a package using the `npm publish` command. Historically this has had no issues, but I am now unable to get past this error:
```bash
npm notice === Tarball Details === 
npm notice name:          @cjaas/common-components                
npm notice version:       2.2.0                                   
npm notice package size:  8.7 MB                                  
npm notice unpacked size: 23.6 MB                                 
npm notice shasum:        8eb9bc0fb7af60ee38625e3a2ab05f4ed7656e23
npm notice integrity:     sha512-VBvclEsvn9MCh[...]o03VZaTdxxN+g==
npm notice total files:   159                                     
npm notice 
npm ERR! code HPE_INVALID_VERSION
npm ERR! errno HPE_INVALID_VERSION
npm ERR! request to http://registry.npmjs.org/@cjaas%2fcommon-components failed, reason: Parse Error: Invalid major version
```

### Expected Behavior

Since no other changes have been made, I expect the package to publish as normal. Otherwise, I would hope for a more helpful error message that can help me find a solution. I have experimented with changing Node and NPM versions on my machine without luck

### Environment

- OS: MacOS 11.3.1
- Node: 12.16.3
- npm: 6.13.4

**Comment by ljharb** [comment]
Try npm 7?

**Comment by futurethang** [comment]
@ljharb interesting, that changes the error to 
```
npm ERR! code E400
npm ERR! 400 Bad Request - PUT http://registry.npmjs.org/@cjaas%2fcommon-components
```
I'm kinda learning as I go and this error so far has not led me to more answers.

**Comment by ljharb** [comment]
Are you logged in (`npm whoami`), and is this a package that already exists, and does it have `publishConfig` set properly in its package.json?

**Comment by futurethang** [comment]
I'm logged in correctly. I have tried troubleshooting publishConfig, but am unsure how to find the proper registry setting. I think this is something that may have had a change somewhere that I am unable to track down clearly.

**Comment by darcyclarke** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)
