### ISSUE TITLE
[BUG] npm publish errors with EISDIR

### ISSUE THREAD

**Issue by ida** [npm/cli#3283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm publish errors with EISDIR

### Expected Behavior

Publish package to npmjs.com.

### Steps To Reproduce

Run `npm publish`, make sure a directory named '.gitignore' is present.
Removing the '.gitignore'-directory makes the error disappear.
Thanks to https://github.com/npm/npm/issues/8095#issuecomment-97065101 for making me check newly added directories.
Here it is mentioned that deleting '.git'-directory worked: https://github.com/npm/npm/issues/15316#issuecomment-359096280
That issue was auto-closed because of inactivity and freshly created here: https://github.com/npm/npm/issues/19650

### Environment

- OS: Ubuntu 20.04
- Node: 16.1.0
- npm: 7.11.2

**Comment by ljharb** [comment]
Why would `.gitignore` be a directory and not a file? (like, when would anyone create that in the first place, and why?)

**Comment by ida** [comment]
> Why would `.gitignore` be a directory and not a file? (like, when would anyone create that in the first place, and why?)

Github did that for me when creating a repo and selecting "Add gitignore". I also wondered why it's a directory and not a file.

**Comment by ljharb** [comment]
Which gitignore template did you select?

(tbh this seems like a bug in github itself, not in npm - altho npm's error message could be clearer)

**Comment by ida** [comment]
There was only one selection: "Include gitignore".

**Comment by ruyadorno** [comment]
Thanks for bringing it up to our attention @ida. Handling `.gitignore` as a dir rather than a file looks outside of the scope of `npm publish` in its current design/implementation. If there are ecosystems or templates that make use of that, let's make sure to bring it up over the [RFC repo](https://github.com/npm/rfcs) (in the form of an RRFC issue or Discussion) so that we can have more discussions in order to make a more informed decision on whether is worth supporting that usecase.
