### ISSUE TITLE
[BUG] spawn git EMFILE

### ISSUE THREAD

**Issue by happydude** [npm/cli#3343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Intermittent failure to clone internal repos using git+ssh after upgrading to npm@7 , if I revert back to npm@6 the problem goes away.

### Steps To Reproduce

1. Linux
2. "devDependencies": {
        "thing-one": "git+ssh://git@gitlab.example:node/thing-one.git#semver:^4.1.0",
        "thing-two": "git+ssh://git@gitlab.example:node/thing-two.git#semver:^2.0.0"
    }
3. Run 'npm ci'
4. See error...
```
npm ERR! code EMFILE
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -24
npm ERR! spawn git EMFILE
npm ERR! command git --no-replace-objects clone -b v4.1.0 git+ssh://git@gitlab.example:node/thing-one.git /home/xyz/.npm/_cacache/tmp/git-clone-cc6d2b3b --recurse-submodules
```

if I copy and paste the git command
```
git --no-replace-objects clone -b v4.1.0 git+ssh://git@gitlab.example:node/thing-one.git /home/xyz/.npm/_cacache/tmp/git-clone-cc6d2b3b --recurse-submodules
```
and run ```npm ci``` again it works. Sometimes it's one internal git repo that fails, and sometimes its the other. We've tried playing with ~~ulimit -n but setting it very high hasn't helped~~ Setting ulimit -n to 18432 has mostly resolved the problem

### Environment

- OS: RHEL 7.9
- Node: v14.16.1
- npm: 7.15.1

**Comment by ruyadorno** [comment]
hi @happydude thanks for taking the time to report this issue. I believe this is a system limitation rather than a bug in the **npm cli**, like you pointed in your description raising the limit of the number of open file descriptors using `ulimit -n` resolves the problem.

That said, I have the impression that these dependencies you're trying to install might be really large git repos (by number of files) and given how git-repo-based dependencies work (we clone the repo, install their dependencies: `npm install`, and run their prepare scripts: `npm run prepare`) that is probably exhausting the system resources. This would explain why simply cloning the repo works, mind that `npm` will run all these operations under a single process that in itself also has many open file descriptors already opened.

With that in mind I would suggest trying to find alternatives to that setup, such as:
- Is it possible to break this dependencies into multiple dependencies? 
- Is it possible to publish them to a registry (public or private) and install from the registry instead?

Hope that helps and if you still find problems please feel free to open a new issue.
