### ISSUE TITLE
[BUG] global npm update from 7.13.0 to 7.16.0 in some configuration changes ownership of all files in /usr/local/bin

### ISSUE THREAD

**Issue by AyanamiAkaha** [npm/cli#3375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running `sudo npm i -g npm` changes the ownership on entire /usr/local/bin infrastructure to the logged in user. Reproduced the behavior on the backup of my system, transcript below - note how /usr/bin/sudo changed ownership and permissions. The transcript is from a system restored from backup, no other thing was run on it.

```
frater260@frater260 ~ 00:32:04$ ls -l /usr/bin/sudo
-rws--x--x 1 root root 163808 Jan 27 05:10 /usr/bin/sudo*
frater260@frater260 ~ 00:36:06$ sudo npm i -g npm
Password:

removed 1 package, changed 14 packages, and audited 256 packages in 5s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 7.13.0 -> 7.16.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.16.0
npm notice Run npm install -g npm@7.16.0 to update!
npm notice
frater260@frater260 ~ 00:36:45$ ls -l /usr/bin/sudo
-rwx--x--x 1 frater260 users 163808 Jan 27 05:10 /usr/bin/sudo*
```

(note in my legacy dev system I have symlinked /usr/local/ to /usr)

### Expected Behavior

npm will not change permissions or ownership of files it does not install itself (or straight out will refuse to run as root, explaining how to change from legacy setup)

### Steps To Reproduce

there is a transcript above, although I was *not* able to reproduce it on a clean ubuntu system with a similar setup. I believe I have not modified config files. If I know where to search I can try to find more details (have a backup of a system just before the problem).

### Environment

- OS: Slackware 14.2
- Node: 14.16.1
- npm: 7.13.0

- /usr/local is a symlink to /usr
- `n` installed, version 2.1.0
- 3 versions of node installed:     node/10.21.0, node/12.18.1, node/14.15.1

(Only now noticed, `node --version` says 14.16.1, but `n` shows 14.15.1 as installed. Seems npm is a symlink as it should be, but node itself is not)

**Comment by ruyadorno** [comment]
Hi @AyanamiSan thanks for taking the time to report this issue.

I opened a space for the team to track and talk about file ownership issues and find ways to improve the user experience, you can keep an eye here if you're interested: https://github.com/npm/cli/issues/3375

Given that this issue does not have an actionable reproduction I'm going to go ahead and close it since there's not much we can do about it from a bugfix perspective. Feel free to open a new issue providing more info in case you (or anyone else reading this at a later time) stumble upon file ownership problems again to which you manage to reproduce consistently. Thansk again!
