### ISSUE TITLE
[BUG] npm install not working/will get error or it will hang the terminal

### ISSUE THREAD

**Issue by jermainemercado** [npm/cli#3391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to deploy web application on Vultr VPS running Ubuntu 21.04, back-end npm installs correctly however front-end built with create-react-app doesn't not install node_modules correctly. Will get various issues, this is the output of the rare time it gives me an error. Sometimes it just hangs up on `sill audit bulk request`. I've tried clearing cache, deleting package.json + package-lock.json + node_modules folder but nothing seems to work. 

Error log: [2021-06-09T14_51_55_048Z-debug.log](https://github.com/npm/cli/files/6625852/2021-06-09T14_51_55_048Z-debug.log)

### Expected Behavior

npm install should install node modules required to run the React front-end properly.

It works fine on 3 different environments. Mac OSX, Windows, and WSL Ubuntu 18.04.

### Steps To Reproduce

1. ssh onto Ubuntu 21.04 Vultr VPS.
3. Run 'npm install'
4. See error or terminal will hang at some arbitrary part of the npm installation for > 30 min then I have to kill it.

### Environment

- OS: Ubuntu 21.04
- Node: v16.3.0
- npm: v7.16.0

**Comment by wraithgar** [comment]
It looks like the problem here is with `node-sass`.   Your project uses `node-sass@4` and also `node@16`.  You will need to either update your dependencies to something that uses the newest `node-sass` or downgrade your build environment to `node@14`

See this comment thread for more info: https://github.com/npm/cli/issues/2306#issuecomment-862779613
