### ISSUE TITLE
[BUG] binary entrypoint is not being added to ./node_modules/.bin

### ISSUE THREAD

**Issue by JakeChampion** [npm/cli#3446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running `npm i "@financial-times/sass@latest" --save` will install the package but will not add the binary entrypoint `sass` to `node_modules/.bin`.

This works in npm 6, I'm not sure why it does not in npm 7

### Expected Behavior

The `sass` binary entrypoint should be added to `node_modules/.bin`

### Steps To Reproduce

1. Any version of npm 7 - I tried all the minor versions including `7.18.1`
2. The default npm config
3. `npm init -y && npm i "@financial-times/sass@latest" --save`
4. `ls ./node_modules/.bin` will not contain any binaries when it should contain one named `sass`

### Environment

- OS: macOS Catalina
- Node: I tried Node 14 and Node 16
- npm: I tried all npm 7 minor versions including `7.18.1`

**Comment by chee** [comment]
I can reproduce this on 64-bit Linux

**Comment by robin-drexler** [comment]
I tried to dig a bit into this and I think I have an idea, why it doesn't work (anymore). 
First, the good news. This should only affect a _very_ low number of packages, but here we go.

`sass` installs `optionalDependencies`. Like https://github.com/Financial-Times/sass/tree/master/sass-macos-x64 for Mac or https://github.com/Financial-Times/sass/tree/master/sass-windows-x64 for windows. 

All of those packages also contain a `bin` entry named `sass`. I assume that is so that you can install those packages directly without relying on the main package to ship/use the correct version.

When you run `npm install`, npm installs `sass` and its optional dependencies.
But after doing that, it goes through all the `optionalDependencies` that were *not* installed/used. (e.g. because the `cpu` or `os` field didn’t match like here https://github.com/Financial-Times/sass/blob/master/sass-windows-x64/package.json#L13) and cleans those up aka deletes them from node_modules. 

However, it also deletes the `bin` entry file of those unused packages. Unfortunately in the `sass` case, all of them share the *same name* with the main package, so that gets wiped. 😬 

I think this got introduced when `@npmcli/arborist` [was added](https://github.com/npm/cli/commit/edfc8167dfb5c797d73cae87c6a333275d3e8ed5).

- [Docs on how it handles optional dependencies](https://github.com/npm/arborist/blob/73a7b001b3dfa682e18fd8e5dfeecfd05f8db20a/notes/optional-deps.md#handling-optional-dependencies-failures)
- [Code that cleans up "trash"](https://github.com/npm/arborist/blob/d3077cff5dcfc419d9717c32b77fcf055541f827/lib/arborist/reify.js#L909)

Tbh, I'm not sure what the right solution is here. Maybe `arborist` could check if another package, that is not supposed to be deleted has a `bin` entry with the same name and then don't flag it for deletion?

I'm not sure if packages being able to shadow/reuse `bin` entries of other packages should be a thing. 😬

**Comment by ljharb** [comment]
It’s always been a thing and can’t stop being one now; this seems like a clear bug to me.

**Comment by isaacs** [comment]
> I'm not sure if packages being able to shadow/reuse bin entries of other packages should be a thing. 😬

Oof.

> It’s always been a thing and can’t stop being one now; this seems like a clear bug to me.

Well... it's always been unsafe at any speed.  Even in npm v6, if someone installed `@financial-times/sass`, but had a conflicting version of the optional dep, it could have ended up getting its bin clobbered in a few other ways.  We _don't_ allow conflicting binaries to be installed in the global space, for somewhat obvious security reasons, but when we looked into doing that with local deps, we flinched from it, figuring it's been this way for this long, and the security impacts in that case are basically nil, so better to not take on the disruptive change.

A band-aid approach that might solve this in this specific case would be to not delete failed optional dependencies' bin scripts if we didn't actually reify that package.  Right now, Arborist has a pretty simple approach of just throwing the Node and everything associated with it in a trash list, along with other stuff that we remove in the process of installing, and then deleting everything in the trash at the end of the reify process.  This has the other handy property of letting us look in the trash list and avoid reifying any Node that we already know we don't want.

A maybe better (but costlier) approach, if we want to discourage people relying on conflicting bins, would be:

- track which executable comes from which package
- warn the user when something is colliding
- maybe even prompt them to choose which one they want the bin from
- track that choice so that we don't let it be overwritten or removed.

If we want to go the full route of saying "avoid building the tree in such a way that >1 package with the same binary gets put in the same level in the tree", then that's potentially an entire new class of `ERESOLVE`-style conflicts we might be taking on.  We could get around _that_ issue by changing where we link bins to, such that they're _only_ linked into the nodes that depend on them.

That is, if you have `root -> (a, b), a -> (c), b -> (c)`, then we'd build the tree like this:

```
root
+-- node_modules
    +-- .bin
    |   +-- a -> ../a/bin.js
    |   +-- b -> ../b/bin.js
    +-- a
    |   +-- node_modules
    |   |   +-- .bin
    |   |       +-- c -> ../../../c/bin.js
    |   +-- bin.js
    +-- b
    |   +-- node_modules
    |   |   +-- .bin
    |   |       +-- c -> ../../../c/bin.js
    |   +-- bin.js
    +-- c
        +-- bin.js
```

So, the `c` binary would _only_ be linked into the `a` and `b` exec path, even though the dependency is shared.

That would mean some refactoring of the `bin-links` module, which right now is very pleasingly simple.  Today, it just links anything in `path/to/node_modules/foo` into `path/to/node_modules/.bin`, and then trusts that the `node_modules` hierarchy adequately satisfies whatever dependency relationships might exist.
