### ISSUE TITLE
[BUG] Upgrade node-gyp to ^8.1.2 version

### ISSUE THREAD

**Issue by altro3** [npm/cli#3525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run `yarn install`, see these warnings
```
warning npm > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning npm > node-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.
  See https://v8.dev/blog/math-random for details.
warning npm > node-gyp > request > har-validator@5.1.5: this library is no longer supported
```

### Expected Behavior

Need to upgrade dependency `"node-gyp": "^7.1.2"` to `"node-gyp": "^8.1.2"` - it already uses node-fetch (see pull request https://github.com/nodejs/node-gyp/pull/2220)

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS: Windows 10
- Node: 16.4.2
- npm:  7.19.1

**Comment by wraithgar** [comment]
Updating node-gyp is on our roadmap, but it may not be able to happen until npm@8 because it is a breaking change and is not supported in node versions 10.0.0 through 10.11.0, which npm@7 has to support.  It also drops support for some python versions, and we are discussing whether or not that also prevents us from updating in this npm version.

You can see the ongoing discussion here https://github.com/nodejs/node-gyp/issues/2392

The bug that prevents users from specifying their own node-gyp version is being tracked here https://github.com/npm/cli/issues/2839
