### ISSUE TITLE
[BUG] npm audit fix could not resolve dependency but it states that dependency found

### ISSUE THREAD

**Issue by zfeher** [npm/cli#3566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm audit fix fails with `Could not resolve dependency` error but above it states that the dependency found

[npm debug.log](https://github.com/npm/cli/files/6854049/debug.log)

### Expected Behavior

npm audit fix should be able to resolve the deduped peer dependency

### Steps To Reproduce

1. In this environment: Ubuntu 20.04, Node 14.17.3, npm 7.20.0

2. With this config:
```JSON
{
  "devDependencies": {
    "@storybook/builder-webpack4": "6.3.4",
    "css-loader": "5.2.6",
    "webpack": "4.46.0"
  }
}
```

3. Run `npm i` then run `npm audit fix`

4. See error: `Could not resolve dependency...`

### Environment

- OS: Ubuntu 20.04
- Node: 14.17.3
- npm: 7.20.0

**Comment by nlf** [comment]
i'm not able to reproduce this one on the latest npm (8.5.3 at the time of writing). can you try updating and see if it resolves your issue?

**Comment by zfeher** [comment]
Hi' Tried this again with node v14.19.0 and npm v8.5.3. Now it seems it is able to print the audit report. But it starts with some warnings at the top like `ERESOLVE overriding peer dependency`, `Could not resolve dependency:`, `Conflicting peer dependency: webpack@5.70.0`. Don't understand why we have conflicting peer dep here because only webpack 4 is installed (`npm list webpack displays only webpack 4`). 

[npm-debug.log](https://github.com/npm/cli/files/8223712/npm-debug.log)

**Comment by ljharb** [comment]
@zfeher the implication is that you have something in your deps that requires webpack 5, which is thus invalid with the rest of your graph.

**Comment by wraithgar** [comment]
The erroneous `ERESOLVE` errors are a separate bug https://github.com/npm/cli/issues/4270, the logging is just happening too early, it's not actually a failure.

Running `npm audit fix` fails because `webpack@5` is required to clear all the current advisories.  `npm audit fix --force` leaves devDependencies in this range

```
~/D/n/scratch $ npm pkg get devDependencies
{
  "@storybook/builder-webpack4": "^6.4.19",
  "css-loader": "5.2.6",
  "webpack": "^5.70.0"
}
```

However because `@storybook/builder-webpack4` still has `webpack: '4'` for its dependency on webpack, it gets that version in its own tree, and there is still a single audit warning for one of its deeper subdependencies.

The commands work as intended, and there is a separate tracking issue for that erroneous log warning.
