### ISSUE TITLE
[BUG] npm >=7.20.3 freezes on npm up command

### ISSUE THREAD

**Issue by zdm** [npm/cli#3616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run `npm up` it freezes at some point with the high CPU load.

```
[##................] | idealTree:cliui: timing idealTree:node_modules/cliui Completed in 10ms
```

Always on `cliui`.

### Expected Behavior

You know what I am expecting )))

### Steps To Reproduce

My list of dependencies:
```
"peerDependencies": {
        "@softvisio/core": "^4.0.0",
        "@softvisio/vuex": "^4.0.0",
        "@vue/cli-service": "^5.0.0-beta.2",
        "@vue/compiler-sfc": "^3.1.2",
        "vue": "^3.1.2",
        "vue-cli-plugin-webpack-bundle-analyzer": "^4.0.0",
        "webpack-bundle-analyzer": "^4.4.2",
        "worker-loader": "^3.0.8"
}
```

1. run `npm up`;
2. see, that it stuck;

### Environment

- OS: windows, linux
- Node: 16.6.1
- npm: from 7.20.3 to 7.20.5, <=7.20.2 - works

**Comment by ivomurrell** [comment]
I've been getting the same issue when running any installation command in npm versions >=7.20.3. It seems like a peer dependency conflict is causing npm to get stuck in an infinite loop rather than printing a warning and completing resolution with nested dependencies like it did in 7.20.2.

I created a minimal example to show the issue, using `stylelint`, plus the `stylelint-scss` and `stylelint-order` plugins which depend on `stylelint` as a peer dependency. We ask for `stylelint@10` and the version of `stylelint-order` also expects `^10` but `stylelint-scss` wants `stylelint@9`. This installs fine when run with the `--legacy-peer-deps` flag and fails without it as expected. However, if you then depend on this package in another package we'll run into an infinite loop when we install with the default behaviour of massaging nested peer dependency conflicts (but will return an error as expected when using the `--strict-peer-deps` flag.)

### Steps to reproduce
We define a package `foo` as
```json
{
  "name": "foo",
  "version": "1.0.0",
  "dependencies": {
    "stylelint": "^10.1.0",
    "stylelint-order": "^3.1.1",
    "stylelint-scss": "^2.5.0"
  }
}
```
and the minimal example will hoist the `foo` dependencies:
```json
{
  "name": "minimal-loop",
  "version": "1.0.0",
  "dependencies": {
    "foo": "./foo"
  }
}
```
Now, when we run `npm install` in the `minimal-loop` directory it will freeze at
```
⸨#######⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠧ idealTree:stylelint: timing idealTree:node_modules/stylelint Completed in 8ms
```
If we instead run `npm install --verbose` we can see the npm command is stuck in a loop, printing
```
npm timing idealTree:node_modules/stylelint-scss Completed in 4ms
npm timing idealTree:node_modules/stylelint Completed in 4ms
npm timing idealTree:node_modules/stylelint-order Completed in 3ms
npm timing idealTree:node_modules/stylelint Completed in 8ms
npm timing idealTree:node_modules/@stylelint/postcss-css-in-js Completed in 0ms
npm timing idealTree:node_modules/@stylelint/postcss-markdown Completed in 1ms
npm timing idealTree:node_modules/fastest-levenshtein Completed in 0ms
npm timing idealTree:node_modules/stylelint-scss Completed in 7ms
npm timing idealTree:node_modules/stylelint Completed in 7ms
npm timing idealTree:node_modules/stylelint-order Completed in 6ms
npm timing idealTree:node_modules/stylelint Completed in 52ms
npm timing idealTree:node_modules/@stylelint/postcss-css-in-js Completed in 0ms
npm timing idealTree:node_modules/@stylelint/postcss-markdown Completed in 0ms
npm timing idealTree:node_modules/fastest-levenshtein Completed in 0ms
npm timing idealTree:node_modules/stylelint-scss Completed in 4ms
```
ad infinitum.

If we instead run `npm i` with npm 7.20.2 we get a warning
```
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: stylelint@10.1.0
npm WARN node_modules/stylelint
npm WARN   stylelint@"^10.1.0" from foo@1.0.0
npm WARN   foo
npm WARN     foo@1.0.0
npm WARN     node_modules/foo
npm WARN   1 more (stylelint-order)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer stylelint@"^8.0.0 || ^9.0.0" from stylelint-scss@2.5.0
npm WARN node_modules/stylelint-scss
npm WARN   stylelint-scss@"^2.5.0" from foo@1.0.0
npm WARN   foo
```
but `stylelint@9` is installed locally for `stylelint-scss` and the install completes successfully.

Ideally this is the behaviour we would like to see with newer versions of npm 7 too.

**Comment by zdm** [comment]
In my case I have no peer deps conflicts.

**Comment by zdm** [comment]
Maybe me deps has peer deps conflicts.
In any case thank you for your investigation, hope this issue will be fixed soon.

**Comment by zdm** [comment]
Does anybody seen this issue?
Just curious, because malfunctional npm 7.20.3 now is shipped with the node 16.6.0.

**Comment by ljharb** [comment]
A later version ships with node v16.7; do you still have problems with that?

**Comment by zdm** [comment]
Yes, `npm up` command is not works for my packages.
I need to downgrade npm, but this is the bad solution.

**Comment by ljharb** [comment]
From your peer dep warning above, the underlying issue seems to be that `stylelint-scss@2.5.0` is incompatible with stylelint 10, so while it's still a bug that npm is hanging here, it should never work because that's an invalid dependency graph.

**Comment by ivomurrell** [comment]
Yes @ljharb, you are right that the inner `foo` package in my example project is misconfigured, and ideally you'd just update to a newer version with that fixed. Unfortunately, that kind of misconfiguration was obscured in npm 6 when peer dependencies weren't automatically installed and so some older packages will have this as latent issue (hence the utility of `--legacy-peer-deps`.) The workaround behaviour exhibited in `npm@7.20.2` is what you'd typically want when migrating from npm 6 to 7, especially when you don't have control over the dependency with the invalid graph, so I think the fact that it instead gets stuck in a loop is a problem a few people will run into.

(And yeah, it looks like the bug is still happening for my minimal example when using npm 7.21.0)

**Comment by zdm** [comment]
Do we have any chances that this will be fixed? 
`npm` not works. 
Can I help somehow?

**Comment by zdm** [comment]
Guys, how I can fix it?
I don;t have any conflicting dependencies and npm doesn't shows any errors, it just freezes.
I need to downgrade it everywhere to version 7.20.3. This is the hell, too much stupid work.

**Comment by zdm** [comment]
If it is unable to install something due to the conflicts it must show error message, so we can understand, what should be fixed.

**Comment by lukekarrys** [comment]
I think this is the same bug as #3787 (and https://github.com/npm/arborist/issues/325). I'm going to keep this open to confirm that both of these cases are fixed also once https://github.com/npm/arborist/pull/326 lands.

I confirmed @ivomurrell's finding that the following package.json produces the infinite loop when installed:

```
{
  "name": "foo",
  "version": "1.0.0",
  "dependencies": {
    "stylelint": "^10.1.0",
    "stylelint-order": "^3.1.1",
    "stylelint-scss": "^2.5.0"
  }
}
```

I also reduced the original example report to:

```
{
  "name": "foo",
  "version": "1.0.0",
  "peerDependencies": {
    "@vue/cli-service": "^5.0.0-beta.2"
  }
}
```

**Comment by lukekarrys** [comment]
I tested both these cases on https://github.com/npm/arborist/commit/cb623a27fd327b63cd21a4cf96f892d39d1dd308 and both now install correctly. This fix will go out on `2021-09-30`.
