### ISSUE TITLE
[BUG] `package.json#/config/*: Array` changed behaviour to joining items with double new-line

### ISSUE THREAD

**Issue by askirmas** [npm/cli#3775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[package.json](https://github.com/askirmas/npm7-bug-package_config/blob/main/package.json#L15-L18)

```json
{
"config": {
    "array": [
      "item1",
      "item2", "item3"
    ]
}}
```
[`process.env`](https://github.com/askirmas/npm7-bug-package_config/blob/main/index.js#L11)
```json
{
  "npm_package_config_array": "item1\n\nitem2\n\nitem3"
}
```

### Expected Behavior

[`process.env`](https://github.com/askirmas/npm7-bug-package_config/blob/main/index.js#L8-L10) (Like it was at v6):
```json
{
  "npm_package_config_array_0": "item1",
  "npm_package_config_array_1": "item2",
  "npm_package_config_array_2": "item3"
}
```

### Steps To Reproduce

1. In this environment...
2. Clone bug repo - https://github.com/askirmas/npm7-bug-package_config/
3. Change npm version to 7
3. Run `npm start`
4. See error...
  ```bash
$ npm start 

> npm-bug-config@1.0.0 start
> node index.js

node:assert:123
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  {
+   npm_package_config_array: 'item1\n\nitem2\n\nitem3'
-   npm_package_config_array_0: 'item1',
-   npm_package_config_array_1: 'item2',
-   npm_package_config_array_2: 'item3'
  }
    at Object.<anonymous> (/Users/kirmasy/code/npm-bug-config/index.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: { npm_package_config_array: 'item1\n\nitem2\n\nitem3' },
  expected: {
    npm_package_config_array_0: 'item1',
    npm_package_config_array_1: 'item2',
    npm_package_config_array_2: 'item3'
  },
  operator: 'deepStrictEqual'
}

  ```

### Environment

- OS: MacOS 11.5.2
- Node: 16.9.1
- npm: 7.21.1

**Comment by askirmas** [comment]
Same for npm v7.24.0

Nothing in docs https://docs.npmjs.com/cli/v7/configuring-npm/package-json#config

**Comment by siemhesda** [comment]
Hi @askirmas, After looking deeply into this issue here's a few things I found out...

### Findings

The **v7** changes to the `config` have actually been mentioned on the **release/v7** changelog under the [All Lifecycle Scripts](https://github.com/npm/cli/blob/release/v7/CHANGELOG.md#all-lifecycle-scripts) section.

The section references [RFC 21 (Reduce the environment variables provided to lifecycle scripts)](https://github.com/npm/rfcs/blob/main/implemented/0021-reduce-lifecycle-script-environment.md) which talks about the changes and the motivation behind them.

### Workaround

For your case, you can achieve the `config` you are trying to by having the values as suggested below:

#### 1. Previously:

```json
{
  "config": {
    "array": ["item1", "item2", "item3"]
  }
}
```

`process.env`

```json
{
  "npm_package_config_array": "item1\n\nitem2\n\nitem3"
}
```

#### 2. Equivalent (solution)

```json
{
  "config": {
    "array": {
      "0": "item1",
      "1": "item2",
      "2": "item3"
    }
  }
}
```

`process.env` (desired)

```json
{
  "npm_package_config_array_0": "item1",
  "npm_package_config_array_1": "item2",
  "npm_package_config_array_2": "item3"
}
```

### Progress

There's however need to have these changes reflected on the documentation (still exploring the justification for the change), or revert the part that causes the double new-line. I'm currently actively working on this issue and these are currently in progress.
