### ISSUE TITLE
[BUG]  When installing a git dependency, prepare script not running

### ISSUE THREAD

**Issue by OmgImAlexis** [npm/cli#3800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Package is installed and no `dist` directory is created.

### Expected Behavior

* Package is installed, prepare script is run and `dist` directory is created.

### Steps To Reproduce

This should show `dist` missing in the `ls` even though it has a `prepare` script.
* `mkdir x && cd x && npm init -y`
* `npm i github:omgimalexis/interval-to-human`
* `ls node_modules/interval-to-human/`

If you then run ` cd node_modules/interval-to-human/ && npm i && npm run prepare && cd ../../` you'll see the `dist` directory now exists.

### Environment

- OS: Windows/macOS/linux
- Node: v14.15.3
- npm: 6.14.5 - 7.24.1

**Comment by OmgImAlexis** [comment]
Related issues:

#321
#459
#1229
#1287
#1390

**Comment by Raynos** [comment]
Ran into this today.

**Comment by ghost** [comment]
It might be related to #2890

**Comment by OmgImAlexis** [comment]
@gms-ta-koge doubt it since it also happens in 6 and they state they can downgrade to fix it.

**Comment by OmgImAlexis** [comment]
So...

`v14` - the prepare isn't called.
`v15` - the dev deps aren't installed.
`v16` - the dev deps aren't installed.
`v17` - fails with `path null/package.json`

**Comment by OmgImAlexis** [comment]
Does any version of node have a copy of `npm` that works with git and global packages?

**Comment by ruyadorno** [comment]
Thank you for the report @OmgImAlexis, after debugging the reproduction steps provided I noticed that the error you're finding is due to the fact that your `dist/` folder is in fact ignored via `.gitignore` file.

In order to be able to properly prepare a git repo `npm` will run the extracted files through [npm-packlist](https://github.com/npm/npm-packlist) in order to get the expected files that are going to be placed in your `node_modules` folder.

To fix it either add a `.npmignore` file that ignores all the files that you don't want to end up in your tarball (but make sure to not add `dist` to the list) OR instead use the package.json `files` property to define all files that should be included (including `dist`).

Thanks again and hope this helps 😊

**Comment by OmgImAlexis** [comment]
Time to add a warning to all my repos that're missing the `files` field. This fixed the issue.

**Comment by ljharb** [comment]
Or .npmignore; omission from “files” means your consumers break; omission from npmignore means an extra thing gets published.
