### ISSUE TITLE
[BUG] npm undeprecate still not working

### ISSUE THREAD

**Issue by globules-io** [npm/cli#3838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

npm ERR! code E400
npm ERR! 400 Bad Request - PUT https://registry.npmjs.org/@globules-io%2fogx.js - deprecations must be strings

28 verbose stack HttpErrorGeneral: 400 Bad Request - PUT https://registry.npmjs.org/@globules-io%2fogx.js - deprecations must be strings

### Expected Behavior

undeprecate a package

### Steps To Reproduce

npm deprecate @globules-io/ogx.js@1.8.6 ""

### Environment

- OS: Windows 10 x64
- Node: 16.10.0
- npm: 7.24.2

**Comment by sandersn** [comment]
I'm not sure I have exactly the same problem, but I temporarily edited `deprecate.js` to remove the `msg` check at the start of `deprecate`:

```js
async deprecate([pkg, msg]) {
  if (!pkg) //    <---- this used to read `if (!pkg || !msg)`
```

But this means if you forget the message it will always undeprecate, which doesn't seem right. The correct fix is probably to have a separate flag or a special message that causes undeprecation, since `""` is ambiguous with not passing the flag at all, apparently.

**Comment by globules-io** [comment]
I totally agree, `undeprecate` should be its own command, or maybe even something more eloquant such as `restore`

**Comment by wraithgar** [comment]
This appears to have been fixed since this issue was created.  There was a PR that fixed the regression here: https://github.com/npm/cli/pull/3484.

I was able to deprecate and un-deprecate two test packages, one with only one version and one with multiple versions.

`undeprecate` would be a handy command to have, and that is in our [backlog](https://github.com/npm/statusboard/issues/376) of things to do.
