### ISSUE TITLE
when using: npm i bunion --no-cache I get a folder called "false" in the dir

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#390]
Original bug ticket: [https://npm.community/t/9693](https://npm.community/t/9693)
      Originally filed: 2019-08-25T22:06:28.510Z

**Comment by isaacs** [comment]
That's because `--cache` is how you specify the cache _folder_ and `--no-whatever` is a shorthand for `--whatever=false`, and since `'false'` is a valid folder name, it creates a cache folder called `'false'` in your current working directory.

Working as designed, but I'm guessing your intent was `--prefer-online` or something?
