### ISSUE TITLE
cygpath not found on windows with MINGW shell

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#396]
Original bug ticket: [https://npm.community/t/9889](https://npm.community/t/9889)
      Originally filed: 2019-09-05T05:51:24.095Z

**Comment by sapphi-red** [comment]
This happens also like the environment below.

- Windows
- Using GitHub Desktop (GitHub Desktop uses the git command which is included)
- a npm package which uses git hooks

https://github.com/npm/cmd-shim/blob/92c0a16d3c8a8c53ade76b5eae8efae01dd7f41f/index.js#L155
Changing this line to `*CYGWIN*) basedir=`cygpath -w "$basedir"`;;\n'` fixed for me.

refs npm/cmd-shim#30 

May be this happens when using git bash (which is based on mingw).
