### ISSUE TITLE
[BUG] npm error when downloading whatsapp-web.js on termux

### ISSUE THREAD

**Issue by 1rens1** [npm/cli#3961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I'm downloading whatsapp-web.js on my phone with termux but it seems to catch an error.
When I `npm i whatsapp-web.js`, npm yells at me "Exit handler never called!"
But it works fine for other packages

![image](https://user-images.githubusercontent.com/78131273/139381130-ab23bcc0-7d23-4bd2-a02d-965940adb8eb.png)

Complete log: https://bin.horizn.xyz/QPM4i

### Expected Behavior

npm would install whatsapp-web.js and my life would be easier.

### Steps To Reproduce

`npm i whatsapp-web.js`

### Environment

- OS: Android 11
- Termux: v0.117
- Node: v17.0.1
- npm: v8.1.1

**Comment by wraithgar** [comment]
Typically this is due to termux's severly limited resources.  We are constantly working on making npm work in these environments but it's not a guarantee.  See this [wiki entry](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more info.

**Comment by 1rens1** [comment]
Thanks.
wow 6 months, I assume this is "lag"
