### ISSUE TITLE
Use the full name of a scoped package for its binary

### ISSUE THREAD

**Issue by aminnairi** [npm/cli#3966]
A package can have a binary that has by default the name of the package as the name of the binary. This works well for packages that are not scoped.

However, when a package is scoped, the scope name is discarded when creating a binary. This can lead to potential conflict. For instance, if one publishes a package named `@organization/eslint` and a package `eslint` already exist, the two would have the same name.

By default, binary that are scoped should have a binary name that also contain the scope name like `organization-eslint` for a scoped package named `@organization/eslint`. This would be great to have this being the default setting for scoped packages because it looks like this is a sensible default for most maintainer out there.

And if anything has to be changed, we can still use the alternative to override this behavior like `{"bin": {"other-organization-eslint": "index.js"}}`.

The only problem is that for now, and for scoped package, we always have to override this behavior which is tedious.

I hope this is clear for anyone peeking at this issue and if this is not, please let me know so that I can try to rephrase some parts.

**Comment by wraithgar** [comment]
A suggestion like this would need to go through the [rfc process](https://github.com/npm/rfcs).

However your idea just pushes the problem down the line because if someone published `organization-eslint` as a package the bin name would collide there.  This may be a documentation issue, where it would need to be suggested that you change your bin name in a scoped package because of this.
