### ISSUE TITLE
Windows npm install <folder> pointing to network drive

### ISSUE THREAD

**Issue by justtonytone** [npm/cli#3980]
Does npm install support pointing to a network drive? We have a virtualbox setup where the source code is shared via a network drive. When I run `npm install <folder>` on windows, it looks like it creates a directory junction, which fails because it does not support network drives. Is there anyway to have npm create a symbolic link (which does support remote paths)?

**Comment by darcyclarke** [comment]
Not on windows as far as I know. If you were on any other platform (ex. mac/linux) `npm` would create a symlink. That said, you might be able to use `npm link` (https://docs.npmjs.com/cli/v8/commands/npm-link) here instead of `install` to get the same desired effect but I'm not 100% sure that will work for your specific situation.
