### ISSUE TITLE
[BUG] workspaces: in

### ISSUE THREAD

**Issue by simoneb** [npm/cli#4008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Providing additional CLI args to `npm init -w` leads to inconsistent behavior. For example with the `--yes` or `-y` flag:

- `npm init -w -y <package name>` leads to an error and the creation of a folder named `-y`
- `npm init -wy <package name>` leads to an error and the creation of a folder named `--yes`
- `npm init -w <package name> -y` works as expected and creates a new workspace without prompting package.json information to the user

### Expected Behavior

All the three examples above should have the same behavior as the last case

### Steps To Reproduce

- Create a new package with a root package.json
- Execute the above commands to create a new workspace

### Environment

- npm: 8.1.3
- Node: v16.11.0
- OS: Windows 10
- platform: x86
- npm config: not relevant

**Comment by ruyadorno** [comment]
Hi @simoneb thanks for taking the time to reach out.

Unfortunately the only supported syntax is the one you described as working as expected, e.g: 

```
$ npm init -w <package name> -y
```

Trying `npm init -w -y` will not work since the argument `-w` expects a pathname right away and `npm init -wy <package name>` will not work since the npm cli does not support grouping shorthands together like that.

You can always propose new ideas in our https://github.com/npm/rfcs repo but in this particular case I'm afraid our current config management might limit the options we're able to support in the near future.
