### ISSUE TITLE
[BUG] Wrong behaviour of `npm version` inside workspaces

### ISSUE THREAD

**Issue by oleksiibatin-ne** [npm/cli#4017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

After running `npm version patch -m "chore: release %s " --workspaces --include-workspace-root` command in monorepo, npm doesn't add inner packages.json files into a generated commit. Thus, version commit only contains changes from the root package.json, updated package.json inside `workspace-a` and `workspace-b` haven’t been added to version commit by npm.

```
.
+-- package.json
`-- workspace-a
   `-- package.json
`-- workspace-b
   `-- package.json
```
### Expected Behavior

Version commit should contain changes that were made by `npm version patch -m "chore: release %s " --workspaces --include-workspace-root` command in monorepo.

### Steps To Reproduce

1. Create a folder with monorepo structure with two inner packages.
```
.
+-- package.json
`-- workspace-a
   `-- package.json
`-- workspace-b
   `-- package.json
 ```
2. Root package.json config. 
```{
  "name": "my-workspaces-powered-project",
  "version": 0.0.0,
  "workspaces": [
    "workspace-a",
    "workspace-b"
  ]
}
```
3.  package.json inside `workspace-a` folder.
```{
  "name": "package-a",
  "version": 0.0.0
}
```
3.  package.json inside `workspace-b` folder.
```{
  "name": "package-b",
  "version": 0.0.0
}
```
4. Run `npm version patch -m "chore: release %s " --workspaces --include-workspace-root` in root folder 

### Environment

- npm: 8.1.3
- Node: 16.13.0
- OS: MacOS Big Sur 11.6
- platform: Macbook Pro

**Comment by bigujun** [comment]
Waiting for that to be fixed, for now as a work around i'm using:
`npm version patch --workspaces && git add **/package.json; npm version patch --include-workspace-root --force`

**Comment by wraithgar** [comment]
Until we have a solution for git tagging of workspace version bumps this will always have to be at least two commands.  The core issue here is that `npm version -w x` does not generate a git commit.  The decision was made at the time of implementing `npm version` for workspaces to do this because the existing git tag config wasn't very conducive to workspaces.  `tag-version-prefix` defaults to `v`, and is not something that can be templated or otherwise changed per workspace in a single command.  Rather than block `npm version` for workspaces altogether it was implemented bypassing git tagging altogether.

If we come up with a git tagging strategy for workspaces this problem will be also fixed, as each workspace's version will get its own git commit, with an appropriate tag.  Until then you need to isolate the versioning of the root workspace with its versions.  If anyone has a solution for git tagging workspaces they feel would work, please sumbit an [rfc](https://github.com/npm/rfcs) so the rest of the npm community can approve it.

**Comment by ljharb** [comment]
Seems pretty straightforward - add `workspace-tag-version-prefix`, defaulting to `[$workspaceName] `, and ignored when workspaces is not enabled. I'll try to write an RRFC.

**Comment by ljharb** [comment]
https://github.com/npm/rfcs/issues/570

**Comment by christianidas** [comment]
You can work around this in one commit. Add this scrip to your package.json at the root:
`"version": "npm version $npm_package_version --workspaces && git add **/package.json"`
