### ISSUE TITLE
[BUG] npm view/show result is empty if "latest" tag does not exist

### ISSUE THREAD

**Issue by AlexanderSamoilov** [npm/cli#4029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm view/show works only if there is a version tagged "latest". It was always like this.
I don't like this behavior. I want "npm view" return the list in any case, regardless of whether "latest" exists or not.
(see console logs below)

### Expected Behavior

"npm view/show my_pkg versions" should return easily the version list in chronological order, regardless of what tags are.

### Steps To Reproduce

This console log shows an example of package which has only "next" and "master" tags, but no "latest". For this package "npm show" returns empty output and zero return code.

$ npm dist-tag ls @my_scope/my_pkg
master: 1.2.20220100-DEVBUILD.8
next: 1.2.20211200-RC.2

$ npm show @my_scope/my_pkg versions
$ echo $?
0

### Environment

- npm: 8.1.3 (reproduced 7.x, 6.x, 3.x as well)
- Node: 14.17.6 (reproduced with 12.x, 10.x as well)
- OS: Linux (Ubuntu 18.04)
- platform: x86_64
- npm config:
```
not relevant
```

**Comment by AlexanderSamoilov** [comment]
My argument to have it fixed is that URL https://nexus.mycompany.com/repository/my_registry/@my_scope%2fmy_pkg actually shows the json output with all versions.

Yes, there is no "latest" there, but even in this case the json data can be processed by npm. If there is no"latest" then just the largest number (according to semver) can be used as starting point.

**Comment by wraithgar** [comment]
Changing something like this would need to be done through the [rfc process](https://github.com/npm/rfcs)

The way that npm currently works is that if you refer to a package with no version, the `tag` config is used.  This defaults to `latest` so what is really happening is every time you tell npm to install `my_pkg` it is translating that to `my_pkg@latest`.  Changing that would affect more than just `npm view` it would also affect `npm install` and is a pretty big, breaking change.  It would mean that npm would be "guessing" what version to use instead of relying on a specific tag that the package publisher set.
