### ISSUE TITLE
[BUG] npm version should commit changes and tag *AFTER* the postversion hook

### ISSUE THREAD

**Issue by EvanCarroll** [npm/cli#4040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm version` commits a new tag to the repo before a `postversion` hook runs. The `postversion` hook should run **AFTER** the version is bumped but **BEFORE** the tag is created. This will allow you to add use the version to finalize the release.

### Expected Behavior

The `postversion` hook is a hook that can be used to prepare a release which should be captured by the version tag that `npm version` adds to git.

### Steps To Reproduce

Setup
----
1. Create a workspace
2. Create a `postversion` hook that copies the the version number from `./package.json` to `./packages/foo/package.json`

Execution
----
1. Use `npm version major` to bump the version number of the workspace
2. Your hook will run automatically, updating `./packages/foo/package.json`
3. Files in `./packages/foo/package.json` will remain un-commited
4. Now you will have to,
    1. manually commit files the hook has changed 
    2. update the git tag.

### Environment

❯ npm --version
8.1.0
❯ node --version
v17.0.1

**Comment by nlf** [comment]
the script you're looking for is `version` not `postversion`. when running `npm version` the order of operations looks like:


1. `preversion` script
2. update `package.json` and `package-lock.json`
3. `version` script
4. git commit and tag
5. `postversion` script

`postversion` runs when everything is finished, which is the intentional and correct behavior. i did notice, however, that the `npm version` command does not have its lifecycle scripts well documented so i'll get those docs written up.

**Comment by nlf** [comment]
this actually was documented here https://docs.npmjs.com/cli/v8/commands/npm-version#description (scroll down a bit to "The exact order of execution is as follows"
