### ISSUE TITLE
npm 7.5.2 does not create valid tarball for publish

### ISSUE THREAD

**Issue by seanmorris** [npm/cli#4063]
**Expected Behavior:**

NPM produces a valid tarball with no duplicated slashes on npm pack or npm publish.

**Actual Results**

I get a 415 - "no package.json found in tarball"

![image](https://user-images.githubusercontent.com/640101/142471757-9c540123-adf7-4475-8447-9a56cd55a395.png)

If I open the tarball in xarchiver I get a massive failure (application will crash ~15% of the time) but the CLI shows the issue.  There are double slashes after the "package" root directory name.

**WORKAROUND**

Opening the archive in file-roller and moving the files out of the dir with no name, into the "package" dir allows me to publish by specifying the archive explicitly.

**Comment by darcyclarke** [comment]
1. Please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
2. Please upgrade to the latest version of the `npm` CLI (ie. `npm i -g npm`) & try to replicate this issue
2. If you can replicate, please provide a reproduction case &/or the steps to reproduce this issue

I'm closing but will reopen if you update &/or are able to give more information on this issue.

**Comment by natevw** [comment]
@seanmorris I'm getting the same issue! Did you ever figure out what was going wrong?

**UPDATE**: I think the `npm@7.5.2` version (which is what I got via `apt install npm` on a Debian box) is simply broken. Running `npx npm publish` instead was an easy way to use a newer version `8.4.0` and with that the publish worked as expected.

**Comment by cameel** [comment]
I ran into the same problem recently and the cause turned out to be a bug in the `tar` package, or rather the version of it packaged on Debian 11 as `node-tar` 6.0.5. This package was patched to hotfix a security issue ([CVE-2021-37701.patch](https://salsa.debian.org/js-team/node-tar/-/blob/bullseye/debian/patches/CVE-2021-37701.patch)) but apparently this broke the logic for concatenating paths. The `package/` prefix gets concatenated with file names incorrectly, giving paths with double slashes (e.g. `package//package.json`) in the archive and the npm registry rejects such malformed archives.

The problem is that this is the up to date version of the `tar` package on stable Debian. To work around it, you need to get a newer version - there's one in backports. A quick and dirty workaround is also to install the latest version of npm via system npm (`npm install npm`) and use that to run `pack` through `npx` (i.e. `npx npm pack`).
