### ISSUE TITLE
[BUG] npm install does not install local package dependencies

### ISSUE THREAD

**Issue by xel23** [npm/cli#4130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If I have local package `"@mypackage/repo": "file:../repo"` and it has its own dependency, npm does not install `repo` dependencies

### Expected Behavior

npm install `repo` dependencies

### Steps To Reproduce

1. Have a monorepo with structure:
```
|-monorepo
|  |-foo
|  |-bar
```
2. `foo` has dependency:
```
"dependencies": {
    "@mymonorepo/bar": "file:../bar"
  }
```
3. `bar` has some another dependency:
```
"dependencies": {
    "@babel/core": "7.16.0"
  }
```
4. From `foo` run `npm install`

### Environment

- npm: 8.1.0
- Node: 16.13.0
- OS: macOS Monterey
- platform: Macbook Pro

**Comment by nlf** [comment]
the issue here is that since npm v7 when installing a directory like you are here, we don't actually install the package, we create a link to it. in order to actually install the dependency as though it were a package in the registry, you'd have to `npm pack` within that directory and then `npm install` the resulting tarball.

this is the intended behavior, so technically not a bug. i do agree this behavior isn't super intuitive, though. perhaps you'd be willing to [open an RRFC](https://github.com/npm/rfcs) to discuss changing this?

**Comment by andrewtran1995** [comment]
I've run into this issue as well, but am confused by what seems to be inconsistent behavior between:
1. Installing a local package that does _not_ have to navigate to parent directories (e.g., `file:./a-child-directory`).
2. Installing a local package that has to navigate to a parent directory (e.g., `file:../a-sibling-directory`).

In the first case, any dependencies of `a-child-directory` are still installed as if it were in the registry. In the second case, the same one described in the original comment, those dependencies are not installed.

Is this also intended behavior?
