### ISSUE TITLE
[BUG] `npm install --production` fails downloading devDependencies, installing nothing

### ISSUE THREAD

**Issue by Jimbly** [npm/cli#4132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running `npm install --production` seems to try to download devDependencies (maybe recursively? I can't find exactly where this dependency is being referenced), and when one of those fails (e.g. git URL package that doesn't exist anymore), it fails to install even the production dependencies.

### Expected Behavior

Npm should allow you to install a package's dependencies even if some devDependencies down the tree are no longer valid.

### Steps To Reproduce

1. Use a `package.json` like so:
```json
{
  "dependencies": {
    "isarray": "0.0.1"
  },
  "devDependencies": {
    "browserify": "~3.14.1"
  }
}
```
(I'm specifically trying to debug an issue with the package [stack-mapper](https://www.npmjs.com/package/stack-mapper) [(GitHub)](https://github.com/thlorenz/stack-mapper), which requires forking, npm installing, and npm linking, but this seems to be a general problem I didn't encounter before upgrading from Node 12 -> 16)
2. Run `npm install --production`
3. This pop-up keeps popping up (presumably from Git), pausing NPM:
![image](https://user-images.githubusercontent.com/774383/144891348-ad09f147-3fec-4b4c-b288-070d3218a25e.png)
4. Eventually fails with this error:
```
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/feross/base64-js.git
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
```

I would expect the result to be `isarray` is installed without error, but nothing ends up installed.

### Environment

- npm: 8.2.0
- Node: v16.13.0
- OS: Windows 10 x64
- npm config:
```ini
; "builtin" config from C:\Users\waste\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\waste\\AppData\\Roaming\\npm"

; "user" config from F:\Shared\home\.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\TEMP\temp
; HOME = F:\Shared\home
; Run `npm config ls -l` to show all defaults.
```

NPM debug log: 
[npm_debug.log](https://github.com/npm/cli/files/7662432/npm_debug.log)

**Comment by nlf** [comment]
this one is strange, but there's a few things going on here.

firstly, `npm install --production` will fetch package data for devDependencies as well as production dependencies. it does this because it wants to generate a consistent package-lock.json regardless of which portion of the deps you're actually installing. the difference is we won't actually download and extract the packages themselves, only their metadata.

this comes in to play because `browserify@3.14.1` depends on `native-buffer-browserify@1.2.4` which in turn depends on a git repository it expects to find at https://github.com/feross/base64-js, which indeed does not exist. the solution here is to update your dependencies. there's not a lot we can do about a package that depends on a git repository that doesn't exist.

**Comment by Jimbly** [comment]
It's tricky to "update my dependencies" when this is apparently a dependency of a dependency of a devDependency of a dependency of what I'm actually working on -_-.  I can hack around it by just removing the devDependencies block for now (or, I guess, just making my edits directly in node_modules/, though that's always risky!).

Running `npm i --production` using `npm@6` also works as a quick workaround for this error if anyone else stumbles upon this in the future.

Looking into this deeper, it seems this is only related to `package-lock.json`, if I place a "valid" package-lock.json in the folder, that also avoids this error.  As a test, I tried `npm install --production --no-package-lock`, however that *still* generates the modal pop-ups and error, I'd somewhat expect that to avoid the error, and not touch any devDependencies at all...

**Comment by ljharb** [comment]
cc @feross re https://github.com/feross/base64-js having disappeared, in case it can be restored

**Comment by bgrande12** [comment]
I also experienced this issue on Nodejs 16 w/ npm version 8.1.0. None of the dependencies had a dependency of a devDependency like what @Jimbly described. Once I specified to use Nodejs 14 w/ npm version 6, the `--production` worked as expected.

**Comment by Jimbly** [comment]
To be clear, the issue was with a (production) dependency of a devDependency of the package I was actually running `npm install` in (in my case, a package I was trying to `npm link` to test a bug fix with another package that depended on it) - this issue seems to only cause a fatal error in regards to the devDependencies of the package having `npm install` ran on it.  If one of the (non-dev) dependencies references an invalid package, than `npm installl --production` will fail on all NPM versions, of course.

**Comment by leolcao** [comment]
> this one is strange, but there's a few things going on here.
> 
> firstly, `npm install --production` will fetch package data for devDependencies as well as production dependencies. it does this because it wants to generate a consistent package-lock.json regardless of which portion of the deps you're actually installing. the difference is we won't actually download and extract the packages themselves, only their metadata.
> 
> this comes in to play because `browserify@3.14.1` depends on `native-buffer-browserify@1.2.4` which in turn depends on a git repository it expects to find at https://github.com/feross/base64-js, which indeed does not exist. the solution here is to update your dependencies. there's not a lot we can do about a package that depends on a git repository that doesn't exist.

Firstly thanks for the explanation about devDependencies and to keep consistent in package-lock.json. This solve my questions during my work.

And I found there are many empty folders in node_modules if I run the command `npm install --production`. The empty folders come from the npm packages in 'devDependencies'. This result is odd to me, compare to npm@6 which only include packages in the dependencies field. 

If I run the command `npm install --production --no-package-lock`, I find npm still check the packages in 'devDependencies', but the intention of this command is not to generate the package-lock.json file any more. So is this still right according to your explanation? Because I think it should not check packages in devDependencies if I set the argument '--no-package-lock'. 

Another question is about those empty folders in node_modules for the command `npm install --production`, is it a issue? Because I think they should not be there.

Thanks in advance~
