### ISSUE TITLE
[BUG] <error' with npm itself>

### ISSUE THREAD

**Issue by BlackMantana** [npm/cli#4176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Steps To Reproduce

1. In this environment termux
2. With this config npm install canvas
3. Run 'error'
/data/data/com.termux/files/home/.npm/_logs/2021-12-16T08_05_50_394Z-debug.log

### Environment

- npm:canvas
- Node:js
- OS: android
- platform: handphone
- npm config:/data/data/com.termux/files/home/.npm/_logs/2021-12-16T08_05_50_394Z-debug.log
```ini
; copy and paste output from `npm config ls` here
/data/data/com.termux/files/home/.npm/_logs/2021-12-16T08_05_50_394Z-debug.log

**Comment by nlf** [comment]
we're missing a lot of information from our template here.

that said, termux is an extremely limited platform and often problems like this are due to resource constraints that we can't do anything about. you can try running `npm i canvas --maxsockets=1` to reduce how many operations take place at once
