### ISSUE TITLE
cb() never called Error on npm install

### ISSUE THREAD

**Issue by darcyclarke** [npm/cli#418]
Original bug ticket: [https://npm.community/t/9557](https://npm.community/t/9557)
      Originally filed: 2019-08-19T14:54:09.391Z

**Comment by anitconsultantllc** [comment]
updated npm and still got error but this bug is still in open status....

PS D:\repos\cmp-deep-dive-01-creation-lifecycle> npm -v
6.12.1
PS D:\repos\cmp-deep-dive-01-creation-lifecycle> npm install npm@latest -g
C:\Users\Owner\AppData\Roaming\npm\npm -> C:\Users\Owner\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\Owner\AppData\Roaming\npm\npx -> C:\Users\Owner\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
+ npm@6.13.1
added 430 packages from 849 contributors in 9.549s
PS D:\repos\cmp-deep-dive-01-creation-lifecycle> npm install
npm WARN deprecated extract-text-webpack-plugin@3.0.0: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated sw-precache@5.2.1: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
npm WARN deprecated sw-toolbox@3.6.0: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-pkSsdH0X8m7FqbgDFCIZYwCUWu4yaJbIrCFDzQXsdVJv4QnlS30CMaJ6Hf7hxT1j4hqxoa315mhpeQ9imcM5iA== integrity checksum failed when using sha512: wanted sha512-pkSsdH0X8m7FqbgDFCIZYwCUWu4yaJbIrCFDzQXsdVJv4QnlS30CMaJ6Hf7hxT1j4hqxoa315mhpeQ9imcM5iA== but got sha512-0YUkSKNUB52dp+V7ah61teNY3XnivcHWCbDnaL7Mr1mmva1iZuwgx/Hbg61O753CHgJOKP44xMNx4NQXMMawHA==. (10248 bytes)        
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/math-expression-evaluator: Integrity verification failed for sha512-pkSsdH0X8m7FqbgDFCIZYwCUWu4yaJbIrCFDzQXsdVJv4QnlS30CMaJ6Hf7hxT1j4hqxoa315mhpeQ9imcM5iA== (C:\Users\Owner\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\a6\44\ac747d17f26ec5a9b8031422196300945aee326896c8ac2143cd05ec75526fe109e54b7d0231a27a1dfee1c53d63e21ab1a1adf5e66869790f6299c33988)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2019-11-21T07_48_54_765Z-debug.log
PS D:\repos\cmp-deep-dive-01-creation-lifecycle>

[2019-11-21T07_48_54_765Z-debug.log](https://github.com/npm/cli/files/3873432/2019-11-21T07_48_54_765Z-debug.log)

**Comment by mikemimik** [comment]
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.
