### ISSUE TITLE
[BUG] Overrides are not updating after running npm install

### ISSUE THREAD

**Issue by Exelord** [npm/cli#4232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

After updating the overrides, `npm install` is not updating the `package.lock` or `node_modules`.

To make it work I had to remove both `package.lock` and `node_modules`, then the overrides have been applied.

### Expected Behavior

Change in `overrides` should update `package.lock` and `node_modules` after running `npm install`

### Steps To Reproduce

1. Add a dependency
2. npm install
3. Add override
4. npm install

### Environment

- npm: >=8.3.0
- Node.js: 16.13.2
- OS Name: macOS 12
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by rushilsrivastava** [comment]
Also facing it on 8.3.2

**Comment by lautapercuspain** [comment]
It's reproducible on NPM v `8.1.2` as well.

- Node.js: 16.13.2
- MacOS Monterrey 12.0.1

**Comment by zzdjk6** [comment]
Same issue here.

OS: MacOS 11.3.1
Node: 16.13.2
NPM: 8.3.2

**Comment by shdb2** [comment]
Experiencing the same issue.
Node: 16.13.2
npm: 8.4.0

**Comment by koflin** [comment]
Same here:

- NPM: 8.4.1
- Node: 16.13.2
- OS: Windows 10

**Comment by dbjorge** [comment]
Wanted to clarify that for some variations of this scenario, the results are even worse than "`npm install` doesn't update `package-lock.json`". Below is a repro case where the results are "`npm install` *does* update `package-lock.json`, such that a reviewer looking quickily over a diff would think that the override has taken effect, but actually it has only *partially* updated `package-lock.json` and the version of the package in `node_modules` does not reflect the override".

```bash
# Baseline setup, all as expected
> node --version
v16.14.0
> npm --version
8.4.1
> mkdir npm-cli-4232-repro && cd npm-cli-4232-repro && git init && npm init -y
> npm install is-odd
> rg '\"version\"' ./node_modules
./node_modules\is-number\package.json
4:  "version": "6.0.0",

./node_modules\is-odd\package.json
4:  "version": "3.0.1",
> git add package*.json && git commit -m 'before override'

# Now edit package.json adding "overrides": { "is-number": "5.0.0" }

# Expected behavior: npm install should update the lockfile and installed versions such that the override to v5.0.0 is satisfied
> npm install
# Actual behavior: the installed version of is-number remains 6.0.0, not 5.0.0
> rg '\"version\"' ./node_modules
./node_modules\is-number\package.json
4:  "version": "6.0.0",

./node_modules\is-odd\package.json
4:  "version": "3.0.1",
# Actual behavior: package-lock.json is only partially updated.
# A reviewer skimming the most obvious version number change will see that the is-odd requires section correctly indicates 5.0.0
# However, the is-number entry in dependencies is incorrectly still referencing 6.0.0
> git diff package-lock.json
diff --git a/package-lock.json b/package-lock.json
index 894fae9..2b7850b 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -34,8 +34,7 @@
   },
   "dependencies": {
     "is-number": {
-      "version": "6.0.0",
-      "resolved": "https://registry.npmjs.org/is-number/-/is-number-6.0.0.tgz",
+      "version": "https://registry.npmjs.org/is-number/-/is-number-6.0.0.tgz",
       "integrity": "sha512-Wu1VHeILBK8KAWJUAiSZQX94GmOE45Rg6/538fKwiloUu21KncEkYGPqob2oSZ5mUT73vLGrHQjKw3KMPwfDzg=="
     },
     "is-odd": {
@@ -43,7 +42,7 @@
       "resolved": "https://registry.npmjs.org/is-odd/-/is-odd-3.0.1.tgz",
       "integrity": "sha512-CQpnWPrDwmP1+SMHXZhtLtJv90yiyVfluGsX5iNCVkrhQtU3TQHsUWPG9wkdk9Lgd5yNpAg9jQEo90CBaXgWMA==",
       "requires": {
-        "is-number": "^6.0.0"
+        "is-number": "5.0.0"
       }
     }
   }
```

Once the user is in this scenario, **both** `package-lock.json` **and** `/node_modules/` must be deleted in order to get the correct behavior from `npm install`; if you delete either one but not the other, `npm install` will return you to the unexpected state.

(Node 16.14.0, npm 8.4.1, Windows 11 21H2 22000.493)

**Comment by cristianoccazinsp** [comment]
Overrides not working at all with npm 8.4.1, e.g.:
```
  "overrides": {
    "react-native": {
      "hermes-engine": "~0.11.0"
    }
  },
```

**Comment by fexxdev** [comment]
npm@8.5.2, i can confirm it still doesn't work with this version

**Comment by grandsilence** [comment]
npm@8.1.2, node v16.13.2, Windows 10 21H2, same issue.

**Comment by AlanSl** [comment]
This issue is attracting some general "overrides don't work for me at all" comments in addition to the specific original reported issue, so it might be worth mentioning a couple of things to check for that can cause overrides to not work at all:

1. There's an [undocumented limitation of overrides in **monorepos with workspaces**](https://github.com/npm/cli/issues/4517): `overrides` are only read in the project root package.json; `overrides` in workspace package.json files are ignored by design.
2. [Overrides weren't released until **NPM version 8.3.0**](https://github.com/npm/cli/blob/latest/CHANGELOG.md#v830-2021-12-09) - @grandsilence overrides aren't working for you because you're on npm 8.1.2

---

So if it seems overrides don't work at all, and you think this issue might be related, do `npm install -g npm@latest` and check the overrides aren't in a workspace (and hoist them if they are). Then try the steps described above (e.g. deleting package-lock and node_modules, then looking at exactly what's being written to package-lock).

**Comment by niiick1** [comment]
I was also expecting it to work on npm 8.1.2. If it only works on 8.3.0 and above, the documentation should state that. Based on this, I assumed it works on any npm 8:

<img width="322" alt="image" src="https://user-images.githubusercontent.com/4442814/158177697-a29bde83-bc2d-4e97-8736-7407caa933e5.png">

**Comment by ljharb** [comment]
8.x is a range that resolves to the latest version only; iow, to 8.5.4 as of this writing.

**Comment by niiick1** [comment]
If that's the case, it should be written more clearly it's latest version only IMO

I was not the only one here that tested on 8.1.2. I think it would be beneficial having a _since 8.x.y_ written for each property in the documentation. It would be helpful folks like me that can't always use latest. 

There's no need to fish npm's changelog to check that :)

**Comment by ljharb** [comment]
That sounds like it’d be a great improvement; node’s docs tell you which versions each thing landed in and it’s very helpful.

**Comment by sirbarrence** [comment]
In case it helps anyone, running `npm update` instead of `npm install` will update the overrides in the lockfile without needing to delete the lockfile or node_modules. Unfortunately it also tries to update all other packages and takes forever, which you may not want.

Running `npm update <name-of-override-package>` just installs the latest default version that the other dependencies want rather than the override version. So that's no help.

**Comment by amerikan** [comment]
I'm on npm `8.4.0`.

I added:
```
"overrides": {
+    "google-calendar": {
+      "needle": "2.9.1"
+    }
+  },
```

Ran `npm install` and then the following lines were changed in package-lock.json.

![Screen Shot 2022-03-15 at 7 49 26 PM](https://user-images.githubusercontent.com/179356/158507017-75b255f2-dcf7-4264-a2a0-f250c7b892de.png)

**Comment by dios-david** [comment]
Same as @amerikan using npm 8.3.1 or latest (8.5.4) on osx arm64

**Comment by ljharb** [comment]
Can all of you try *latest* npm, 8.5.4 i think?

**Comment by craigjbass** [comment]
I am seeing this issue on npm 8.5.4

**Comment by jpveooys** [comment]
Can confirm I also seem to be seeing this and #4322 with npm 8.5.4 while investigating migrating from yarn v1 to npm v8.

My working branch is here if it helps: https://github.com/defencedigital/mod-uk-design-system/compare/spike/npm-v8-2

The project uses workspaces and the overrides are in the root `package.json`. (Note there is one peer dependency error you will need to bypass.)

In that example, `trim` stays on `0.0.1` after `npm install` (which `npm update` fixes), while `axe-core` ends up on mixed versions no matter what I do.

**Comment by craigjbass** [comment]
@ljharb I was reading through the Arborist code, and came across https://github.com/npm/cli/blob/d7265045730555c03b3142c004c7438e9577028c/workspaces/arborist/lib/node.js#L93 - my hypothesis is that some code that constructs Node or Link objects either doesn't pass `true` for this `loadOverrides` value when it should, or actually we want to be loading overrides in all cases.

**Comment by darcyclarke** [comment]
### Update
- we're looking into this & should have a fix in the next week or so (will circle back if there's any updates)

**Comment by zjullion** [comment]
If you need to fix security vulnerabilities right now and can't wait, try [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions)

**Comment by ljharb** [comment]
@zjullion npm has overrides, that shouldn't be needed anymore.

**Comment by Exelord** [comment]
I am on NPM 8.6 and still the same issue. The issue seams not fixed

**Comment by eliza3291** [comment]
As mentioned by @Exelord this issue is not fixed.

**Comment by dbjorge** [comment]
@Exelord and @eliza3291, can you give more specific repro steps (including exact Node and npm versions) for the case(s) you are seeing as still reproing? I just followed the exact steps I originally posted in [this comment](https://github.com/npm/cli/issues/4232#issuecomment-1034240038) against Node 16.14.2 / npm 8.6.0 and was *not* able to repro the issue anymore (ie, it appears fixed).

**Comment by solimant** [comment]
@darcyclarke - this is, unfortunately, not yet fixed as of 8.6.0. Initial `npm install` seems to honor the overrides, but any subsequent `npm install` will ignore and undo the fruits that were reaped the first time (please don't judge me for being on Next.js v10):
```
$ npm ls shell-quote
my-app@1.0.0 /Users/me/my-app
└─┬ next@10.0.8
  └─┬ @next/react-dev-overlay@10.0.8
    └── shell-quote@1.7.3 invalid: "1.7.2" from node_modules/@next/react-dev-overlay

$ npm install

$ npm ls shell-quote
my-app@1.0.0 /Users/me/my-app
└─┬ next@10.0.8
  └─┬ @next/react-dev-overlay@10.0.8
    └── shell-quote@1.7.2 invalid: "1.7.3" from node_modules/@next/react-dev-overlay
```

`package.json`:
```json
"overrides": {
  "shell-quote": "1.7.3"
},
```

`package-lock.json`:
```diff
- "node_modules/shell-quote": {
-   "version": "1.7.3",
-   "resolved": "https://registry.npmjs.org/shell-quote/-/shell-quote-1.7.3.tgz",
-   "integrity": "sha1-qkDtrBcERbmkMeF7tiwLiBucQSM=",
-   "license": "MIT"
- },

// ~ //

"@next/react-dev-overlay": {
  "version": "10.0.8",
  "resolved": "https://registry.npmjs.org/@next/react-dev-overlay/-/react-dev-overlay-10.0.8.tgz",
  "integrity": "sha1-qOhBZHt0+XIMxg0+O9PaIlrRJTM=",
  "requires": {
    "@babel/code-frame": "7.12.11",
    "anser": "1.4.9",
    "chalk": "4.0.0",
    "classnames": "2.2.6",
    "css.escape": "1.5.1",
    "data-uri-to-buffer": "3.0.1",
    "platform": "1.3.6",
-    "shell-quote": "1.7.3",
+    "shell-quote": "1.7.2",
    "source-map": "0.8.0-beta.0",
    "stacktrace-parser": "0.1.10",
    "strip-ansi": "6.0.0"
  },

// ~ //

"shell-quote": {
-  "version": "1.7.3",
+  "version": "1.7.2",
-  "resolved": "https://registry.npmjs.org/shell-quote/-/shell-quote-1.7.3.tgz",
+  "resolved": "https://registry.npmjs.org/shell-quote/-/shell-quote-1.7.2.tgz",
-  "integrity": "sha1-qkDtrBcERbmkMeF7tiwLiBucQSM=",
+  "integrity": "sha1-Z6fQLHbJ2iT5nSCAj8re0ODgS+I="
},
```

CC: @nlf

**Comment by Exelord** [comment]
@dbjorge I am following the exact steps as in the initial issue description and still getting the same result.

**Comment by melink14** [comment]
Some parts of this bug seem slightly different so opened new more specific bug at: https://github.com/npm/cli/issues/4727

**Comment by trusktr** [comment]
Still not fixed, and I may have reported a duplicate of #4727

**Comment by darcyclarke** [comment]
@nlf I'm reopening as there's been a few reports this is still a problem. Can you repro based on the above &/or give any updates as to why someone may still be seeing `npm install` not respecting an `override` after the first time they ran it?

**Comment by melink14** [comment]
FWIW, my repos are all fixed after 8.7.

**Comment by jpveooys** [comment]
Just tried 8.7.0 and still seem to be seeing problems, unfortunately.

To repro:

```
git clone https://github.com/defencedigital/mod-uk-design-system.git
cd mod-uk-design-system
git switch spike/npm-v8-2
npm install
npm ls axe-core
npm ls trim
```

It could be there is a further problem specific to workspaces.

**Comment by nlf** [comment]
this does look to be workspace specific, i wasn't able to reproduce the failed overrides you're seeing in this repo when the workspaces are removed.

i opened a new issue to track workspace issues here: https://github.com/npm/cli/issues/4834

**Comment by nguyenlam123** [comment]
For me, it works on 

```
OS: macOS Big Sur 11.3.1
node: 16.15.0
npm: 8.5.5
```

Does overrides work for anyone else using npm 8.5.5?

**Comment by Exelord** [comment]
I can still reproduce it (v8.8.0) as in the first post and Im not using any workspace

**Comment by jdhiro** [comment]
I was able to jump over to node18/npm8.8.0, run 'npm i', fix the package-lock.json, and go back to node16.

**Comment by brabenetz** [comment]
I use:
* Windows 10
* node 16.15.0
* npm 8.5.5

Example: I have "pdfmake" in my dependencies and overrides it with:
```js
    "overrides": {
        "ast-transform@0.0.0": {
            "escodegen": "1.14.3",
            "esprima": "4.0.1"
        }
    },
```

`npm update` worked fine, but after `npm install` the old dependency-versions of "ast-transform" where "restored" in package-lock.json:
![image](https://user-images.githubusercontent.com/1237858/170099214-4821cd08-7e18-4170-bb30-6e50ececde9c.png)

but no old version where downloaded or added to the package-lock.json, and the "npm list --depth=6" showed the right version:
![image](https://user-images.githubusercontent.com/1237858/170101975-167e73ba-0441-4587-8aca-2640e05dd0ad.png)


At the end the solution worked for me. Thanks.

**Comment by yoyo837** [comment]
Remove `package-lock.json` and `node_modules`, reinstall it, `overrides` maybe works well.

**Comment by mcdehaan** [comment]
> I was able to jump over to node18/npm8.8.0, run 'npm i', fix the package-lock.json, and go back to node16.

This worked for me as well 🥳

**Comment by BillyAleks** [comment]
> I was able to jump over to node18/npm8.8.0, run 'npm i', fix the package-lock.json, and go back to node16.

++ working solution

**Comment by nicolashenry** [comment]
I noticed that it worked only if I put exact version in overrides.

If I put something like the following, it does not work (but does not complain):
```json
"overrides": {
  "mylib": "~1.0.0"
}
```

But with the following, it works fine:
```json
"overrides": {
  "mylib": "1.0.0"
}
```

I put this here if it can help someone.

**Comment by engelmav** [comment]
Why is this closed? There is no definitive answer.

**Comment by bartvanremortele** [comment]
The "fixed by" claims that it was fixed in 8.6.0. However I am still facing this issue on 8.12.1 when using this in combination with workspaces. I added the overrides to the root package.json and the lockfile is not updating. I'm running into multiple issues with lockfile drift. The workaround for me is to run `npm update`. That updates the lockfile.

**Comment by paullewisn** [comment]
Same on 8.11.0. Changes to overrides are only applied if `node_modules` and `package-lock.json` are removed prior to `npm i`.

**Comment by jasoncarmona** [comment]
Tested on npm `8.14.0` and it's still an issue, you have to manually delete both `node_modules` and `package-lock.json` then install again so the right dependency will be selected.

If only one of those two is deleted, the process won't work and it will reconstruct the same faulty lock file.

**Comment by sbonami** [comment]
In case it helps, my specific scenario correctly sees the override applied to the first-level package. Where it fails is in the much-deeper instance. I'm not familiar with the internals of npm's tree generation, but this coincides with a working override for the dependency in the root of node_modules but not for the nested version.

OS: MacOS 12.3.1
Node: 16.14.2
NPM: 8.5.0

```
$ cat package.json

{
  ...
  "overrides": {
    "glob-parent": "^6.0.2"
  }
}
```

```
$ npm ls glob-parent

package-name@#.#.# /path/to/package
├─┬ @typescript-eslint/parser@5.27.1
│ └─┬ @typescript-eslint/typescript-estree@5.27.1
│   └─┬ globby@11.1.0
│     └─┬ fast-glob@3.2.11
│       └── glob-parent@5.1.2
└─┬ eslint@8.17.0
  └── glob-parent@6.0.2
  
$ npm ls fast-glob

package-name@#.#.# /path/to/package
├─┬ @typescript-eslint/parser@5.27.1
│ └─┬ @typescript-eslint/typescript-estree@5.27.1
│   └─┬ globby@11.1.0
│     └── fast-glob@3.2.11
```

```
/path/to/package/node_modules
├─┬ fast-glob/
│ └─┬ node_modules/
│   └── glob-parent@5.1.2
└── glob-parent@6.0.2
```

**Comment by patoncrispy** [comment]
If you're in a workspace, move the override to the root package.json. That works for me.

**Comment by Especially** [comment]
Note that the INITIAL install will abide by the override rules set, and the subsequent installs (e.g., run npm install twice) will ignore overrides.

**Comment by julian91** [comment]
This problem still exists for workspaces. We spent 2 weeks migrating a monorepo with ~30 microservices and ~50 modules to npm workspaces X turborepo. 
Now having to exclude 1 of our frontend projects from the workspace and having an entire CI/CD flow for one service seperately from the rest of the monorepo because it cant deal with vue3 (yet) is pretty frustrating.

Are there at least any updates IF or WHEN this will be fixed?

**Comment by surbhirverma** [comment]
Same, I was able to reproduce this issue

**Comment by xinhuan-myob** [comment]
> Same, I was able to reproduce this issue

Me too

**Comment by ForbiddenEra** [comment]
I'm seeing this issue on `8.5.5` currently; removing `node_modules` and `package-lock.json` and doing `npm install` does install the overridden dependencies, however, I'm also seeing a different, potentially related issue here.

When doing `npm ls --depth=10`, I get errors:
(any lines with `...` have been removed for brevity)
```
...
├── cookie@0.5.0
...
├─┬ socket.io@4.5.2
...
│ ├─┬ engine.io@6.2.0
...
│ │ ├── cookie@0.5.0 deduped invalid: "~0.4.1" from node_modules/engine.io
...
│ │ └── ws@8.8.1 deduped invalid: "~8.2.3" from node_modules/engine.io
...
├─┬ ws@8.8.1
│ ├── UNMET OPTIONAL DEPENDENCY bufferutil@^4.0.1
│ └── UNMET OPTIONAL DEPENDENCY utf-8-validate@^5.0.2

npm ERR! code ELSPROBLEMS
npm ERR! invalid: cookie@0.5.0 ~/example/node_modules/cookie
npm ERR! invalid: ws@8.8.1 ~/example/node_modules/ws
```
My `package.json` contains:
```
        "dependencies": {
...
                "cookie": "^0.5.0",
                "socket.io": "^4.5.2",
...
                "ws": "^8.8.1",
        },
        "overrides": {
                "ws": "$ws",
                "cookie": "$cookie"
        },
...
```
I've also tried:
```
        "overrides": {
                "socket.io": {
                       "ws": "$ws",
                       "cookie": "$cookie"
                }
        }
```
and,
```
        "overrides": {
                "socket.io": {
                        "engine.io": {
                                "ws": "$ws",
                                "cookie": "$cookie"
                        }
                },
        },
```
and even,
```
        "overrides": {
                "socket.io": {
                        "engine.io": {
                                "ws": "$ws",
                                "cookie": "$cookie"
                        }
                },
                "ws": "$ws",
                "cookie": "$cookie"
        },
```
with no difference.

Another oddity I noticed - if I edit `node_modules/engine.io/package.json` and make NO changes (so, basically just touching the file / updating it's last modified) the error disappears _without running anything_ between that and `npm ls --depth=10`. However, if I subsequently run `npm install` and then do `npm ls --depth=10`, the error comes back.

If I change `node_modules/engine.io/package.json` to use ^ instead of ~ for the packages and `remove package-lock.json` and run install, nothing changes and I still get the error - setting ^ _should_ allow the replacement versions (`8.8.1` for `ws` and `0.5.0` for `cookie`) to be allowed for that package. I suppose if I also removed the `node_modules` along with `package-lock.json` and then did `npm install`, that it might work, however then the changes made to that file would obviously be gone.

Potentially even worse than this (eg. other than the error on `npm ls` and the pain of having to force it to install the overrides by removing `node_modules` and `package-lock.json`) and possibly more frustrating/damaging is that running a `npm dedupe` actually replaces the overridden versions with the versions requested by the package instead! Basically `npm dedupe` in this situation is un-deduping! (But then, of course, the `npm ls --depth=10`  error is gone!)

```
# npm dedupe

added 2 packages, ...
# npm ls --depth=10
├─┬ cookie-parser@1.4.6
...
│ └── cookie@0.5.0 deduped
├── cookie@0.5.0
...
├─┬ socket.io@4.5.2
...
│ ├─┬ engine.io@6.2.0
...
│ │ ├── cookie@0.4.2
...
│ │ └─┬ ws@8.2.3
...
├─┬ ws@8.8.1
...
```

I may try updating (however this particular dev machine is on `Ubuntu 18.04.6 LTS` which has `npm 8.5.5` as it's latest packaged version) or attempting to reproduce on another machine with a later `npm` version but it's not a show-stopper right now so not a huge priority (unless someone can confirm at least the `dedupe` and `npm ls --depth=10` issues are fixed in a particular version, the not updating/installing the overridden version after adding an override in `package.json` is annoying but doesn't show errors or replace with the wrong version like the other issues so it's less of a concern).

**Comment by HomyeeKing** [comment]
so is there any solution here?
I think the npm docs should clarify what should  do to make `overrides` rules work

**Comment by samuliasmala** [comment]
> Note that the INITIAL install will abide by the override rules set, and the subsequent installs (e.g., run npm install twice) will ignore overrides.

I can confirm this is the behavior in the latest `npm@8.19.2`. This can be reproduced easily with the following `package.json`:

```json
{
  "name": "test",
  "version": "1.0.0",
  "engines": {
    "npm": ">=8.3.0"
  },
  "dependencies": {
    "json-server": "^0.17.0"
  },
  "overrides": {
    "json-server": {
      "package-json": "7.0.0"
    }
  }
}
```

1. `npm install` in the folder containing only the above `package.json` --> 0 vulnerabilities
2. Subsequent `npm install` right after the previous (so `node_modules` and `package-lock.json` exists) --> 5 vulnerabilities
3. `npm update` --> 0 vulnerabilities
4. `rm -rf node_modules/ && npm install` --> 5 vulnerabilities
5. `rm package-lock.json && npm install` --> 5 vulnerabilities
6. `rm -rf node_modules/ && rm package-lock.json && npm install` --> 0 vulnerabilities

From the above it can be concluded that **the `overrides` property is only honored when running `npm install` first time (i.e. without `package-lock.json` and `node_modules` present) and when running `npm update`**.

**Comment by lukekarrys** [comment]
I have not gone through all the reports in this thread since it was closed. But I did check https://github.com/npm/cli/issues/4232#issuecomment-1281801614 from @samuliasmala and I have confirmed that issue, so I opened a new issue for it here #5850.

If anyone else has a different issue than that, it's most helpful if you can open a new issue with your reproduction.

**Comment by rene-leanix** [comment]
> From the above it can be concluded that **the `overrides` property is only honored when running `npm install` first time (i.e. without `package-lock.json` and `node_modules` present) and when running `npm update`**.

Uninstalling and reinstalling just the package for which the override was defined seems to be sufficient:
```
npm uninstall json-server && npm install json-server
```
(With `--save-dev` for dev dependencies, of course.)

**Comment by KuSh** [comment]
Doesn't work with latest npm version for firebase-tools at all :

```sh
❯ npm --version
9.2.0
❯ jq .overrides package.json
{
  "express": "^4.17.3",
  "got": "^11.8.5"
}
❯ npm uninstall firebase-tools

removed 687 packages, and audited 872 packages in 6s

104 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
❯ npm install -D firebase-tools
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 687 packages, and audited 1559 packages in 9s

130 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (6 moderate, 4 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

I've tested many combinations without much luck :

```json
{
  "overrides": {
    "firebase-tools": {
      "express": "^4.17.3",
      "got": "^11.8.5"
    }
  }
}
```

```json
{
  "overrides": {
    "firebase-tools": {
      ".": "$firebase-tools",
      "express": "^4.17.3",
      "got": "^11.8.5"
    }
  }
}
```

```json
{
  "overrides": {
    "firebase-tools": {
      ".": "$firebase-tools",
      "express": "^4.17.3",
      "package-json": {
        "got": "^11.8.5"
      }
    }
  }
}
```

**Comment by amanda-eero** [comment]
> > From the above it can be concluded that **the `overrides` property is only honored when running `npm install` first time (i.e. without `package-lock.json` and `node_modules` present) and when running `npm update`**.
> 
> Uninstalling and reinstalling just the package for which the override was defined seems to be sufficient:
> 
> ```
> npm uninstall json-server && npm install json-server
> ```
> 
> (With `--save-dev` for dev dependencies, of course.)

This works for me, thank you very much for sharing!!! In this case I didn't need to remove the `node_modules` neither the `package-lock.json` to override correctly.

**Comment by KorayAydemir** [comment]
It never works for me. Trying to override `powerglitch` dependency of `react-powerglitch`:
package.json in project root:
```
"overrides":{
    "react-powerglitch":{"powerglitch":"2.3.0"}
},
```

In /node_modules/react-powerglitch/package.json, after trying everything above, like deleting both node_modules and package-lock.json
```
{
...
  "dependencies": {
    "powerglitch": "^2.2.0"
  },
...
}
```

**Comment by maximkoretskiy** [comment]
I spent a day on the issue and it feels like the bug only reveals when a dependency has its own `package-lock.json` or `npm-shrinkwrap.json`.

**Comment by bennycode** [comment]
I had to run `npm update` in order to make my existing `package-lock.json` file respect the `overrides` definition. Using Node.js v23.3.0.

**Comment by Tofandel** [comment]
npm does not install overrides at all after upgrading to npm@11, it's working fine on npm@10

```
sudo npm i -g npm@10
npm upgrade
# Overrides properly installed

sudo npm i -g npm@11
npm upgrade
# Overrides completely ignored and rolled back
```

**Comment by ShadSterling** [comment]
I'm trying to override npm's dependency on the vulnerable tar 7.5.4 with 7.5.7, and even with deleting package-lock.json and node_modules/ the override is not applied.  Rolling back to npm 10 also did not apply the override
