### ISSUE TITLE
[BUG] dist.tarball doesn't need to be changed to http:// anymore.

### ISSUE THREAD

**Issue by tolmasky** [npm/cli#4251]
# What / Why

[This line](https://github.com/npm/libnpmpublish/blame/latest/publish.js#L143) takes the "predicted" tarball URL and unconditionally downgrades it to `http://` from `https://`, even if you are using your own custom registry (as is my case and how I ran into this). The npm registry ignores this parameter now anyways (except apparently to check for its presence?), as you can actually send whatever you want and npm will just overwrite it on the server to the expected couchdb-style URL. As such, you'll find npm reports the dist.tarball to be an `https://` URL unconditionally, even if you for example visit `http://registry.npmjs.org/my-package/0.0.0` instead of `https://registry.npmjs.org/my-package/0.0.0`. Both say `https://registry.npmjs.org/my-package/-/my-package-0.0.0.tgz`.

All this to say, at least as far as the "official" npm registry is concerned, this is a completely ignored parameter and thus does not need to be manipulated. For my own use, it was unfortunate to discover that this URL had been manipulated in this way.

**Comment by ruyadorno** [comment]
Hi @tolmasky thanks for taking the time to bring this to our attention. This issue was migrated from the old `npm/libnpmpublish` repo and is now being tracked in the main cli repo since this package is managed as a workspace now.

I'm going to close this issue given that there seems to have no direct bug caused by the way it works as of today. I can also see how this metadata might be used by the official npmjs.org official registry in unexpected ways, so I would urge caution if we're even going to tweak it in the future.

That said, feel free to open a new issue following the provided template in this repository in case you find any bug with the npm cli or `libnpmpublish` that might be caused by this implementation detail.
