### ISSUE TITLE
Set readmeFilename field on root metadata

### ISSUE THREAD

**Issue by mojavelinux** [npm/cli#4252]
The publish command is currently only propagating the `readme` field from the version manifest to the metadata root. It should also propagate the `readmeFilename`. The Yarn package registry relies on both fields to be set. Otherwise, the contents of the README is not displayed.

```js
  const root = {
    _id: manifest.name,
    name: manifest.name,
    description: manifest.description,
    'dist-tags': {},
    versions: {},
    readme: manifest.readme || '',
    readmeFilename: manifest.readmeFilename || ''
  }
```

If there's agreement about this change, I will gladly send a PR.

**Comment by ruyadorno** [comment]
Hi @mojavelinux thanks for bringing this to our attention. I believe since this is effectively adding new info to that pushed data it might be better to open a discussion or issue in our [RFC repo](https://github.com/npm/rfcs). This way it may get more attention / traction in order to eventually be prioritized.

**Comment by mojavelinux** [comment]
I have good news for you. As far as I can tell, this has now been fixed.
Using the latest version of npm, I can now publish packages that rely on
this information to npm and yarn without patching any libraries.
