### ISSUE TITLE
[BUG](libnpmsearch) Search results for some packages don't contain the repository link, even though the entry on npm does

### ISSUE THREAD

**Issue by peey** [npm/cli#4255]
# What / Why / When / How / Who

```
const search = require("libnpmsearch")
search("anymatch").then(console.log)
```

### Current Behavior
![image](https://user-images.githubusercontent.com/4688870/88331648-ea46bd80-cd4a-11ea-8710-8b2343e72a01.png)

### Steps to Reproduce
Run the code

### Expected Behavior

Links listed on the npm pages should be listed 

![image](https://user-images.githubusercontent.com/4688870/88331745-16fad500-cd4b-11ea-97e1-a4caa6025c55.png)

**Comment by ruyadorno** [comment]
Hi @peey thanks for taking the time to report this issue.

I believe the expected behavior for `libnpmsearch` is to only list fields that are returned by the `/-/v1/search` of the configured registry. see: https://github.com/npm/cli/blob/2db3eff44d7bb86b956207cc63d279806fd14ed0/workspaces/libnpmsearch/lib/index.js#L48


Running the provided script yields the expected links these days so I assume if there was any mismatch between the search endpoint and the website, it might have been fixed by now (or maybe the example package`anymatch` added the missed metadata to their `package.json` file).
