### ISSUE TITLE
(libnpmsearch) Return the total number of results that match a search query

### ISSUE THREAD

**Issue by sketchbuch** [npm/cli#4256]
# What / Why

I would like to get the total number of matching packages so that I can page through the results.

I use libnpmsearch in this vscode extension: https://github.com/sketchbuch/vsc-packages

Currently I can only show a load more button and show a message if there are no more results after trying to search again at a different offset but it would be better if I could build a page browser. For that I need to know how many items there are in total matching the search term.

**Comment by ruyadorno** [comment]
@sketchbuch Thanks for taking the time to share your idea! While new ideas are always appreciated I would please ask you to open an [issue or discussion in our RFC repo](https://github.com/npm/rfcs) instead since that's the right place in order to get more attention from the rest of the team and the community.
