### ISSUE TITLE
[QUESTION](arborist) changelog after 2

### ISSUE THREAD

**Issue by gabrielcsapo** [npm/cli#4271]
# What / Why

Was there any major change after 2? I am trying to understand why tests are failing on my side for my usage of arborist.

**Comment by lukekarrys** [comment]
I believe the only breaking changes since v2 were:

- Renaming overridden prop to peerConflicted https://github.com/npm/arborist/commit/f9685ba96d41443a0401fa5df79061bddf01f294
- Dropping node 10 support https://github.com/npm/arborist/commit/852c6caab7c38f4f7f422aeecd78f5b99b7eb3b9

Can you share some details about how you're using arborist and what unexpected behavior you're seeing?

**Comment by gabrielcsapo** [comment]
This was a non-issue, sorry.
