### ISSUE TITLE
[BUG](arborist) Cannot read property 'extraneous' of undefined

### ISSUE THREAD

**Issue by wolfie** [npm/cli#4290]
# What / Why
It seems like with a certain setup using npm workspaces that has an internal dependency-tree (npm 7.5.1), running `npm install` causes this error:

```
% npm install
npm ERR! Cannot read property 'extraneous' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hpaul/.npm/_logs/2021-02-08T15_37_33_410Z-debug.log
```

the npm log includes this piece of snippet:

```
24 verbose stack TypeError: Cannot read property 'extraneous' of undefined
24 verbose stack     at Arborist.[loadVirtualLink] (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:268:30)
24 verbose stack     at Arborist.[resolveLinks] (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:195:34)
24 verbose stack     at async Arborist.[loadFromShrinkwrap] (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:88:5)
24 verbose stack     at async Arborist.loadVirtual (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:66:5)
24 verbose stack     at async Arborist.buildIdealTree (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:206:7)
24 verbose stack     at async Promise.all (index 1)
24 verbose stack     at async Arborist.reify (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:127:5)
24 verbose stack     at async install (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/lib/install.js:38:3)
```

## When
I'm unsure what exactly causes this. But basically when I run `npm install`

## Where
Private repository

I can answer further questions, but since our project is somewhat complex/big (and also private), it's hard for me to proactively guess what information might be interesting/relevant.

**Comment by ruyadorno** [comment]
It seems to me this thread has turned into multiple different reports to which the cli can eventually exit with a `Cannot read property 'extraneous' of undefined` type of error. I could not find a reliable way to reproduce the original problem with the current version of the **npm cli** (`npm@8.5.2` at the time of writing).

I'm going to close this one but please feel free to submit a new issue, with minimal reproduction scenarios in case you're still experiencing it with the more recent versions of the cli. Thanks!

**Comment by tswaters** [comment]
I hit this same error under npm@7.24.2

Our setup is a little "funny" - but seems to be functional under v6 of npm.  After trying to update to `npm@^7`, we started hitting this problem.  (specifically, using ci, "cant find package-lock" and, running with verbose, we see the `extraneous` TypeError)

So in our case, this is caused by our monorepo structure not being 100% mirrored the same way as it is when things get loaded into docker..... so on the filesystem, it looks something like this:

/node-lib/some-library
/some-application
/some-other-application
/some-grouping/some-special-application

So when `some-special-application` needs a `some-library` reference, it includes it with a file:// reference to, e.g., `file://../../node-lib/some-library`.... i.e., up 2 directories to find `node-lib/some-library`.  Running that on the local fs works.

However, we see this issue crop up when trying to build `some-special-application` in docker.  We use a common Dockerfile which mounts everything in `node-lib` to `/node-lib`, and the given application to `/app`.  

We'll load the same `package-lock.json`, which includes `../../node-lib` references.  If you were to "go up two directories to find node-lib", you'd hit the root fs, no further and ... still find it.  But with npm, it seems to get lost along the way, and arborist fails with that TypeError.

The way we've fixed it is to ensure the filesystem structure more closely matches between local + docker -- so instead of adding everything to `/app/`, anything under `special-grouping` now puts everything into  `/app/some-grouping/`

I'm... honestly not sure if you should try to fix this.  In my particular case, it's _completely_ operator error that causes this problem.  Posting this here in case anyone hits a similar issue.

**Comment by ljharb** [comment]
npm 7 is long since EOL; have you tried npm 8.5.4?

**Comment by tswaters** [comment]
I have not.. 1 thing at a time, getting off of npm 6 :smile:

**Comment by ljharb** [comment]
Easier to jump to 8 latest than to use 7, imo :-)

**Comment by hlolli** [comment]
super annoying, I have a felling it's trying to find file: paths, instead of just ignoring it it crashes like that. This is only happening on linux and not darwin.

```
npm verb loadVirtual TypeError: Cannot read properties of undefined (reading 'extraneous')
npm verb loadVirtual     at [loadVirtualLink] (/nix/store/njq5flksyp6aplbp1r1gqpvajch7fyrb-nodejs-18.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:316:30)
npm verb loadVirtual     at [resolveLinks] (/nix/store/njq5flksyp6aplbp1r1gqpvajch7fyrb-nodejs-18.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:223:34)
npm verb loadVirtual     at [loadFromShrinkwrap] (/nix/store/njq5flksyp6aplbp1r1gqpvajch7fyrb-nodejs-18.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:103:29)
npm verb loadVirtual     at Arborist.loadVirtual (/nix/store/njq5flksyp6aplbp1r1gqpvajch7fyrb-nodejs-18.3.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:75:35)
npm verb loadVirtual     at async CI.exec (/nix/store/njq5flksyp6aplbp1r1gqpvajch7fyrb-nodejs-18.3.0/lib/node_modules/npm/lib/commands/ci.js:40:5)
npm verb loadVirtual     at async module.exports (/nix/store/njq5flksyp6aplbp1r1gqpvajch7fyrb-nodejs-18.3.0/lib/node_modules/npm/lib/cli.js:78:5)
```

**Comment by minlare** [comment]
I experienced this issue today due to **only having** `devDependencies` in the `package.json` - changing these to `dependencies` fixed my issue.
