### ISSUE TITLE
Feature request: search for .npmrc upwards

### ISSUE THREAD

**Issue by thernstig** [npm/cli#4338]
Currently if I am adding a .npmrc upwards in my directory hierarchy, npm does not find it. It would be good if it could search upwards.
That would also help in situations like https://github.com/npm/rfcs/pull/343 where you migth have specified an .npmrc in the root but not in the workspace.

.npmrc files in a workspace then should take precedence.

**Comment by ruyadorno** [comment]
@thernstig Thanks for taking the time to share your idea! While new ideas are always appreciated I would please ask you to open an [issue or discussion in our RFC repo](https://github.com/npm/rfcs) instead since that's the right place for those in order to get more attention from the rest of the team and the community. 😊 

Thanks again and all the best!
