### ISSUE TITLE
[BUG] 8.5 runs scripts (e.g. postinstall) from package root

### ISSUE THREAD

**Issue by simllll** [npm/cli#4412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Since the latest release (8.5) when I run npm install in a monorepo, but not in the root, it installs all fine, but does run the scripts of the root package.json too.

### Expected Behavior

Should not execute the postinstall script of the package.json root.

### Steps To Reproduce

E.g. following imaginary setup
/package.json:
 * postinstall: "echo hello"
 * workspace: ["packages/*"]
 
packages/a/package.json
* dependencies: [...]

running npm install inside packages/a runs "echo hello". Which wasn't the case in <=8.4 and seems like a bug to me.

### Environment

- npm: 8.5 (does work with <8.5)
- Node.js: v16.11.1
- OS Name: Ubuntu 21.10
- System Model Name: Linux
- npm config:
```ini
; "user" config from /home/simon/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /usr/local/bin/node
; cwd = /home/simon
; HOME = /home/simon
; Run `npm config ls -l` to show all defaults.
```

**Comment by fritzy** [comment]
@simllll In 8.5, we autodetect the project root (--prefix), and set a --workspace config, if your cwd is in a workspace. Since `npm install` does not do workspace specific installs (they're global and hoisted by default), the postinstall script of a workspace will never be invoked, and the root one will.

We considered command behavior in the cwd of a workspace to be "undefined" before, and so this was a fix. If you'd like the old behavior, you can run `npm i --prefix=.` when your cwd is a workspace.

**Comment by ljharb** [comment]
@fritzy hopefully `--prefix` isn't the only solution, since use of "prefix" breaks nvm; I thought you can also add an `.npmrc` file to that directory, and commit it, containing something (i forget what the name of the config key is tho).

**Comment by simllll** [comment]
Alriht, I see.. what's the explanation for running the postinstalls but not doing the installs of the modules? I don't get this feature, in our setup with several different monorepos with 20 to over 100 packages each, this only causes troubles instead of solving something? What's the idea behind this, is there anything I can read upon to get the full picture? 
Thanks Simon
