### ISSUE TITLE
[BUG] npx opening the select menu instead instead of executing it.

### ISSUE THREAD

**Issue by OmgImAlexis** [npm/cli#4445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

In node 17 npx causes this dialog to open after running `npx tsconfig.json`. In node 14 this wasn't an issue.

![image](https://user-images.githubusercontent.com/6525926/154830418-2e0a0513-a3e0-49e1-a692-43c10d5d1ace.png)

### Expected Behavior

```
PS C:\Users\xo\code\OmgImAlexis\u-serve> npx tsconfig.json
npx: installed 35 in 7.799s
? Pick the technology you're using: (Use arrow keys)
> CLI
  nextjs
  node(Default)
  react-native
  react
  ```

### Steps To Reproduce

1. Install node 17
2. Run `npx tsconfig.json`
3. Profit?

### Environment

- npm: 8.4.1
- Node.js: v17.5.0
- OS Name: Windows 11
- System Model Name: Custom PC
- npm config: `;`

**Comment by fritzy** [comment]
Does this happen with other packages? Is this a bug with the package not working with newer versions of Node on Windows? All npx does is use `npm exec` to install and execute the package.

https://docs.npmjs.com/cli/v8/commands/npx

If the same behavior happens with

```
mkdir testtsconfig
cd testtsconfig
npm init -y
npm i tsconfig.json
node node_modules/.bin/tsconfig.json
```

Then it's not an npx/npm bug.

**Comment by OmgImAlexis** [comment]
> Then it's not an npx/npm bug.

The fact it works with the older node/npx shows it **IS** in fact a bug with this npx/npm.

```
❯ node node_modules/.bin/tsconfig.json
internal/modules/cjs/loader.js:1131
    throw err;
    ^

SyntaxError: C:\Users\xo\code\testtsconfig\node_modules\.bin\tsconfig.json: Unexpected token # in JSON at position 0
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1128:22)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

❯ ls .\node_modules\.bin\tsconfig.json*

    Directory: C:\Users\xo\code\testtsconfig\node_modules\.bin

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          25/02/2022  6:59 AM            338 tsconfig.json
-a---          25/02/2022  6:59 AM            286 tsconfig.json.cmd
-a---          25/02/2022  6:59 AM            508 tsconfig.json.ps1
```

**Comment by nlf** [comment]
this happens because we're running `cmd.exe /d /s /c tsconfig.json` and since `tsconfig.json` is a file with an extension, and windows doesn't support "shebangs" like osx/linux do, windows decides that the correct thing to do is open the `tsconfig.json` file rather than trying to append the `.cmd` to it and resolve it as a binary to be run.

we can't do much about how windows behaves here, and to be perfectly honest `tsconfig.json` is very much the wrong thing for that bin file to be named in the first place. file extensions exist for a reason, and this example shows what can happen if you disregard them.

the reason this worked in npm@6 is because npx at that time used an ugly hack to unload itself, require the bin file, and turn that into the foreground process. now that we don't do that any more, we're relying on the shell, and the shell isn't playing nicely with this use case in windows.

we have absolutely no intention of restoring the original behavior of npx, as it was very much a hack and caused a lot of potential for other problems. at some point we may be able to work around this issue, but unfortunately it would come with a performance cost as what we'll have to do is parse your command, look for things that appear to be commands, and search your path for each command with a `.cmd` extension. there's some ongoing work to address some parameter escaping issues in windows that would have to perform this same lookup, so when we eventually get around to it we can apply a fix for this at the same time.

i've opened this issue in the relevant repo to make sure we address it when this work continues https://github.com/npm/exec/issues/17

in the mean time, i'm closing this as there's nothing we can do about it until the escaping feature lands anyway.
