### ISSUE TITLE
[BUG] NPM publish strips ANSI characters from files

### ISSUE THREAD

**Issue by cuibonobo** [npm/cli#4489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running `npm pack` or `npm publish` will change the contents of my package if the file contains ANSI escape codes. All escape codes will be stripped from the files before the package is packed and published. As a result, the code published on NPM is different than what is expected.

Example file with ANSI escape codes: https://raw.githubusercontent.com/cuibonobo/npm_card/master/bin/output

The escape codes in the example file should change the color of the characters when printed to a terminal that supports ANSI colors. However, my published NPM package has been stripped of all color information.

### Expected Behavior

Files in the repository should not be modified before they are packaged into a tarball and published to NPM. 

### Steps To Reproduce

1. Clone this minimal NPM card repo to your development environment: https://github.com/cuibonobo/npm_card
2. Run `npm pack` in the NPM card repository to generate a package tarball
3. Run `git status` to verify that the `bin/output` file of the repository has been modified to strip out the ANSI escape codes

### Environment

- npm: 8.5.2
- Node.js: v16.13.2
- OS Name: Windows 10 19042.1526
- System Model Name: N/A. 64-bit system running AMD Ryzen 7 3700X
- npm config:
```ini
; "user" config from C:\Users\Jen\.npmrc

//registry.npmjs.org/:_authToken = (protected)
init-author-email = "jen@haverstack.com"
init-author-name = "Jen Garcia"
init-author-url = "https://haverstack.com/"
init-license = "CC0-1.0"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\Jen\Dev\npm_card
; HOME = C:\Users\Jen
; Run `npm config ls -l` to show all defaults.
```

**Comment by nlf** [comment]
as it turns out, this isn't a bug in `npm` so much as it is a feature in `chalk`.

`chalk` lists `Auto-detects color support` as a highlight of its features. what's happening here is npm is running your `prepare` script before packing the tarball, your `prepare` script is regenerating your output file by running `build.js`. however, because this is being run in a child process that doesn't have a tty, `chalk` is helpfully deciding that it doesn't have color support and is rewriting the file without colors.

the simplest solution to fix it is to adjust your `build` script in your `package.json` so it reads `"build": "node build.js --color"` which forces the color support in `chalk` to on and gives you the expected output.

**Comment by cuibonobo** [comment]
Holy crap. I had no idea that the `npm prepare` script would run during `pack` and `publish`. Thanks so much for tracking this down. 🙏
