### ISSUE TITLE
[BUG] `npm run` in a workspace attempt to run in other workspaces.

### ISSUE THREAD

**Issue by louis-bompart** [npm/cli#4518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Given this project hierarchy:
```
root
│   package.json
│
└───packages
    └───a
        │   package.json
        │
        └───b
                package.json
```

With root/package.json having:
```
  "workspaces": [
    "packages/a",
    "packages/a/b"
  ]
```

If I run `npm run myscript` with `packages/a` as my current directory, `npm` will try to run `myscript` in `package/a` and `packages/a/b`.

### Expected Behavior

Given the same project hierarchy I would expect:
 1. ❌  `npm run myscript` with the CWD being `packages/a` to run **only** `myscript` of `packages/a/package.json`
 2. ✔️  `npm run myscript --workspace=packages/a` to run both on `a` and `b` ([npm doc](https://docs.npmjs.com/cli/v8/commands/npm-run-script#workspace)):
  > * Path to a workspace directory
  > * Path to a parent workspace directory (will result in selecting all workspaces within that folder)
 3. ✔️   `npm run myscript --workspace=a` to run only on `a`. ([npm doc](https://docs.npmjs.com/cli/v8/commands/npm-run-script#workspace)):
 > Workspace names
 
 
 Note, 2&3 are working as expected on the latest version 

### Steps To Reproduce

1. Scaffold NPM project.
```sh
mkdir test-run-script
cd test-run-script
npm init -y
npm init -w packages/a -y
npm init -w packages/a/b -y
```

2. Add a dummy script in `packages/a/package.json` & `packages/b/package.json`, e.g. `"myscript": "echo hello"
3. Ensure your cwd is `packages/a` and run `npm run myscript`.
4. Assert that hello is printed twice.

### Environment

- npm: `8.5.0 - 8.5.3` (latest 
- Node.js: v16.14.0
- OS Name: W10
- System Model Name: N.A
- npm config: 
```ini
; "builtin" config from C:\Users\USER_NAME\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\USER_NAME\\AppData\\Roaming\\npm"

; "user" config from C:\Users\USER_NAME\.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\USER_NAME\Repos\runScriptWorkspace
; HOME = C:\Users\USER_NAME
; Run `npm config ls -l` to show all defaults.
```

**Comment by louis-bompart** [comment]
Also, ideally, from a documentation standpoint I would detail that:
 - When specifying a workspace by name (e.g. `workspace=b`), the 'root' package.json will be used for the workspace resolution
 - When specifying a workspace by path, the current working directory is used for the path resolution, meaning that:
   - `npm run myScripts --workspace=packages/a` will work from root, but not from `packages/a`

**Comment by nlf** [comment]
your package hierarchy isn't explicitly supported by npm. nesting a workspace within another workspace can create some strange issues. realistically we should throw an error when we detect this pattern, as it is a confusing one to debug. if your workspaces are neighbors, i.e. `packages/a` and `packages/b` things should behave more how you'd expect.

i'm going to leave this issue open so that we can clarify our workspaces documentation and make sure that these things are less surprising in the future.

**Comment by louis-bompart** [comment]
Thanks for the clarification, the thing that really made me raise an eyebrow was that it was working in 8.4.2, so that's why I reported this as a bug, given that a working behavior had stopped working.

Eager to read more about workspaces and overall guidelines/limitations 😄
Thanks!

**Comment by mdesousa** [comment]
Just wanted to add that this confused me as well. We had nested workspaces working in 8.3 and suddenly got this infinite loop in 8.4. I'd like to recommend that at minimum, the npm workspaces page should explicitly clarify that nested workspaces are not supported so other people don't run into this.
Otherwise, workspaces have been a very useful feature for us... thanks for all the hard work.
