### ISSUE TITLE
[Feature] add bash/zsh completion to npx

### ISSUE THREAD

**Issue by fleytman** [npm/cli#4577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Not tab completion for npx

### Expected Behavior

Working tab completion for npx

npx rea -> npx react-native

### Steps To Reproduce

1. npm completion >> ~/.zshrc 
2. restart terminal
3. write: npx rea
5. press tab

### Environment

- npm: 8.5.1
- npx: 8.5.1
- Node.js: 17.6.0
- OS Name: MacOs

**Comment by wraithgar** [comment]
@fleytman Thanks for taking the time to share your idea! While new ideas are always appreciated I would please ask you to open an [issue or discussion in our RFC repo](https://github.com/npm/rfcs) instead since that's the right place in order to get more attention from the rest of the team and the community.
