### ISSUE TITLE
[FEATURE] Add loading spinner to `npm fund`

### ISSUE THREAD

**Issue by JasonEtco** [npm/cli#466]
# What / Why

Heyo 👋 While running `npm fund` (which is awesome), it feels like it hangs while its collecting information. It'd be nice to add a spinner/loader to provide some feedback, maybe even print a message like `Collecting funding info...`. I know the CLI already has established methods of showing loading info, but if not, [Ora](https://github.com/sindresorhus/ora) is always a nice choice.

## When
* `npm fund`

## Example of load time:

![npm fund](https://user-images.githubusercontent.com/10660468/68550267-5bb62a00-03cf-11ea-8bd4-e0c240bc9c1b.gif)

cc @darcyclarke

**Comment by ruyadorno** [comment]
hi @JasonEtco is there a public repo that we could use to reproduce this long delay when running the fund command ?

~`npm fund` shouldn't be this slow at all, so we'll be treating this more as a bug that needs to be fixed than trying to add a new spinner to compensate~ 😅 it would be handy to have a reproducible setup in order to validate the fix 😊

**Comment by ruyadorno** [comment]
revisiting this, we might actually look into adding a spinner (or some sort of visual feedback) for now as it seems like it's not something we're going to be able to fix for v6, right now `npm fund` shares the same algorithm to `npm ls` that reads through all the dependencies into your `node_modules` and that is unfortunately, very slow 😞

**Comment by ruyadorno** [comment]
@isaacs did a bit more research into the details of it and apparently this is the biggest offender: https://github.com/npm/read-package-json/issues/82

**Comment by JasonEtco** [comment]
🆒 thanks for the investigation @ruyadorno! If it helps, [here's a Gist](https://gist.github.com/JasonEtco/a3d278342575069adbca482db6ec929c) that contains the `package{,-lock}.json` for the project in the above GIF.

**Comment by ruyadorno** [comment]
Forgot to circle back but we noticed it's quite easy to reproduce, basically any large front-end boilerplate has enough packages that it will hang both `npm ls` and `npm fund` for a while - that said the current plan is to change the mechanism for those so that it gets actually fast in `v7`.

Feel free to propose a PR if you really would like to see a loading indication of some sort in `v6` but otherwise we'll be waiting for `v7` and see how that's going to look like 😊 

Thanks again for taking the time to help us with that @JasonEtco ❤️
