### ISSUE TITLE
Automation token is gone after publishing one time

### ISSUE THREAD

**Issue by pfcstyle** [npm/cli#4686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I want to use automation token in my jenkins, and its progress is below:

```
1. Generate a automation token on my 'Access Tokens' page
2. Set the token into .npmrc file: `npm config set //registry.npmjs.org/:_authToken=npm_...`
3. Publish my package: `npm publish`, and it worked.
4. Patch and re-publish my package: `npm version patch && npm publish`, and it failed for 403.
```
I enter my 'Access Tokens' page again and found that the token is gone.

The 'npm publish' command will remove my automation token?

### Expected Behavior

Automation token should always keep valid.

### Steps To Reproduce

1. Generate a automation token on my 'Access Tokens' page
2. Set the token into .npmrc file: `npm config set //registry.npmjs.org/:_authToken=npm_...`
3. Publish my package: `npm publish`, and it worked.
4. Patch and re-publish my package: `npm version patch && npm publish`, and it failed for 404.

### Environment

- npm: 8.5.4
- Node.js: 16.14.0
- OS Name: MaxOS 11.6
- System Model Name: Macbook Pro
- npm config:
```ini
; "user" config from /Users/developer/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /Users/developer/.nvm/versions/node/v16.14.0/bin/node
; cwd = /Users/developer/Documents/work/spark-system/spark-sdk/spark-js-api
; HOME = /Users/developer
; Run `npm config ls -l` to show all defaults.

; "publishConfig" from /Users/developer/Documents/work/spark-system/spark-sdk/spark-js-api/package.json
; This set of config values will be used at publish-time.

will188:registry = "https://registry.npmjs.org"
```

**Comment by Joozty** [comment]
I experience similar behaviour. The difference is that also the first `npm publish` is not working for me. It used to work a few days ago... event when I regenerate an automation token it still fails. The only way I can publish right now is from my computer. I cannot use any CI/CD tool.

**Comment by iamweijun** [comment]
I have the same problem in my Jenkins task, it's ok for the first time, but failure in the second time.

**Comment by lukekarrys** [comment]
I'm not able to reproduce this with a fresh automation token. I tried several publishes and confirmed it was using the automation token from my npmrc since it stopped prompting for 2fa when that npmrc file was in place. My next hunch is that this is some sort of registry issue, only because of the lack of evidence I could find that it might be a cli issue.

Registry issues are outside the scope of this repo and are best handled by going to [npmjs.com/support](https://www.npmjs.com/support).

I am going to leave this open and also raise it internally to see if we can figure out what's going on.

**Comment by lukekarrys** [comment]
If you're affected by this issue, the best avenue is to file a support request at https://www.npmjs.com/support where we can take action specific to your user account to see what's going on. I'm going to close this for now since it might not be a cli issue, but please reopen if you don't think that's the case.

**Comment by pfcstyle** [comment]
Thanks @lukekarrys. It's my fault. I searched my email and noticed the tip: 
> You are receiving this security alert as the npm security team has taken action to secure your account. Either you (or somebody else) published an npm authentication token for your account to the public npm Registry. That authentication token has been revoked and can no longer be used to access your account.

I put the token into `package.json` as a script command.

**Comment by lukekarrys** [comment]
[The system works!](https://github.blog/2021-06-08-securing-open-source-supply-chain-scanning-package-registry-credentials/) 😄
