### ISSUE TITLE
npm ERR! code EISDIR

### ISSUE THREAD

**Issue by greenhandzdl** [npm/cli#4954]
Error code:
```
PS C:\Users\20292>  npm install -g npm
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code EISDIR
npm ERR! syscall link
npm ERR! path D:\nodejs\node_cache\_cacache\tmp\3901ef1e
npm ERR! dest D:\nodejs\node_cache\_cacache\content-v2\sha512\7f\ad\1393d1eea17e95723f7667f123c9c10375a3995fe7503b098da6bf67ba8cc681dbb49b7bf55f872eb7066367e85d50e334fa37dab4afb2dfc7ca7a89ba49
npm ERR! errno EISDIR
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/npm: EISDIR: illegal operation on a directory, link 'D:\nodejs\node_cache\_cacache\tmp\3901ef1e' -> 'D:\nodejs\node_cache\_cacache\content-v2\sha512\7f\ad\1393d1eea17e95723f7667f123c9c10375a3995fe7503b098da6bf67ba8cc681dbb49b7bf55f872eb7066367e85d50e334fa37dab4afb2dfc7ca7a89ba49'

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2022-05-29T09_56_07_365Z-debug-0.log
```
I've already try (this one)[https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0].

[2022-05-29T09_56_07_365Z-debug-0.log](https://github.com/npm/cli/files/8793083/2022-05-29T09_56_07_365Z-debug-0.log)

**Comment by greenhandzdl** [comment]
version:
```
PS C:\Users\20292> npm version
{
  npm: '8.11.0',
  node: '16.5.0',
  v8: '9.1.269.38-node.20',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
PS C:\Users\20292> node -v
v16.5.0
```

**Comment by sktm4a1** [comment]
me too ! when I run any command with "npm" ,there always is a warning
```sh
$ npm config ls -l
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
; "default" config from default values

_auth = (protected)
access = null
all = false
```

**Comment by ihab-haji** [comment]
Same issue

**Comment by RayOfArbor** [comment]
global `--global`, `--local` are deprecated. Use `--location=global` instead.
me too

**Comment by Alecto** [comment]
me too

**Comment by Mrlinjiapeng** [comment]
can someone helps us pls

**Comment by ChadDevOps** [comment]
Also encountering the issue with an invalid operation for using `link` on 8.11.0. Version 8.12.1 seems to have resolved this (at least I'm not seeing any `link` EISDIR or ENOTSUP issues installing packages). However that does not help in upgrading from 8.11.0 to 8.12.1 via command line. If you are using NodeJS 18.3.0 it comes with npm 8.11.0. May need to update npm manually or wait for a new nodejs version.

Also tried `--no-bin-links` and `-no-bin-links` without success. 

This issue does not appear related to the deprecated warning of -g, the same issue occurs when using `--location=global` on 8.11.0.

**Comment by greenhandzdl** [comment]
> Also encountering the issue with an invalid operation for using `link` on 8.11.0. Version 8.12.1 seems to have resolved this (at least I'm not seeing any `link` EISDIR or ENOTSUP issues installing packages). However that does not help in upgrading from 8.11.0 to 8.12.1 via command line. If you are using NodeJS 18.3.0 it comes with npm 8.11.0. May need to update npm manually or wait for a new nodejs version.
> 
> Also tried `--no-bin-links` and `-no-bin-links` without success.
> 
> This issue does not appear related to the deprecated warning of -g, the same issue occurs when using `--location=global` on 8.11.0.

But in fact, not adding -g will also prompt this kind of error

**Comment by greenhandzdl** [comment]
Strange, when I did not operate any operations of NPM, it could work normally (the only one may be that I got the system again)

**Comment by Shaif-Alam** [comment]
**npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: portfolio@0.0.0
npm ERR! Found: @angular/compiler@13.1.3
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"~13.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"13.3.11" from @angular/localize@13.3.11
npm ERR! node_modules/@angular/localize
npm ERR!   peer @angular/localize@"^13.0.0" from @ng-bootstrap/ng-bootstrap@12.1.2
npm ERR!   node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!     @ng-bootstrap/ng-bootstrap@"12.1.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\saif3\AppData\Local\npm-cache\eresolve-report.txt for a full report.**


### Same issue i geting can anyone tell to here what is the issue here exat

**Comment by Sprite0112** [comment]
> 

你解决了吗‘’
