### ISSUE TITLE
ansi-regex vulnerabilities in npm 6.14.17 due to fixed dependency versioning

### ISSUE THREAD

**Issue by lorand-horvath** [npm/cli#4999]
I've updated to the latest npm 6.14.17 globally with `npm install -g npm@6` which seems to not be able to install the latest of ansi-regex in several dependency chains. 
According to https://github.com/npm/cli/commit/a869ec48b9481c10302378e6c2d94fe36e4c81c2 which updated the deps it seems the versioning has changed for several ansi-regex from range ^ to fixed version. For example
in `node_modules/yargs/node_modules/ansi-regex/package.json`
from
`"_from": "ansi-regex@^4.1.0",`
to
`"_from": "ansi-regex@4.1.0",`
so that will only install the fixed version ansi-regex@4.1.0 instead of the latest 4.1.1 which contains the ReDoS vulnerability fix https://github.com/chalk/ansi-regex/commit/75a657da7af875b2e2724fd6331bf0a4b23d3c9a

Because of this, a global npm audit returns 5 High severity vulnerabilities in npm@6.14.17 (even if I do a clean install) all related to ansi-regex:
`Inefficient Regular Expression Complexity in chalk/ansi-regex`
in
```
npm > cli-columns > string-width > strip-ansi > ansi-regex
npm > npm-audit-report > cli-table3 > string-width > strip-ansi > ansi-regex
npm > update-notifier > boxen > ansi-align > string-width > strip-ansi > ansi-regex
npm > libnpx > update-notifier > boxen > ansi-align > string-width > strip-ansi > ansi-regex
npm > libnpx > yargs > string-width > strip-ansi > ansi-regex
```

The global npm audit was performed with `npx npm-global-audit --auditor npm`.

Can you please change from the fixed version bundling to ranges for all occurrences of ansi-regex here https://github.com/npm/cli/commit/a869ec48b9481c10302378e6c2d94fe36e4c81c2

**Comment by fritzy** [comment]
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v8`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+8.x&template=bug_8.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues/new?assignees=&labels=&template=rrfc.md&title=%5BRRFC%5D+%3Ctitle%3E) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback/discussions)
