### ISSUE TITLE
[BUG] npm prefix giving wrong output

### ISSUE THREAD

**Issue by adityag221** [npm/cli#5016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm prefix` return the right local prefix for a monorepo with workspace for `npm <= 8.4.1`, however it returns the wrong local prefix for `npm@8.5.1` and above. 

So, the current behavior for a package(`npmDemo`) with the structure 

root
|__packages
|&nbsp;&nbsp;&nbsp;|__packageA
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|__package.json
|__package.json
|__package-lock.json

is as follows,
```
C:\Users\adityagupta\Repos\npmDemo\packages\packageA> npm prefix
C:\Users\adityagupta\Repos\npmDemo
```

### Expected Behavior

The above happens only with npm>=8.5.0, while for lower versions the output is as expected

```
C:\Users\adityagupta\Repos\npmDemo\packages\packageA> npm prefix
C:\Users\adityagupta\Repos\npmDemo\packages\packageA
```

I have noticed that this is happening because of `workspaces` in the `package.json` at the root. Removing the `workspaces` makes it work again, however that's not an option for us due to this being a huge monorepo. 
Since this was working as expected earlier even for a monorepo and there are a bunch of other packages using `npm prefix`, this sudden change in behavior is breaking a lot of existing code. 

Is there any way for this functionality to be reintroduced as this is breaking a lot of existing workflows?  

### Steps To Reproduce

I have created https://github.com/adityag221/miniMonorepo as a demo for this scenario. 
- It's a skeletal repository with just the basic structure as mentioned above. 

To reproduce this issue,

- Ensure that you have the environment as mentioned above
- Clone the repository above or create another similar one
- run `npm prefix` inside `packageA` 
- You will get the prefix as the root of the repository instead of `packageA`
- Downgrade to npm@8.4.1 by running `npm install -g npm@8.4.1`
- run `npm prefix` inside `packageA`
- You will get the right prefix this time
- Removing `"workspaces": [
      "packages/*"
    ],` from the `root/package.json`, makes it work for both the versions of `npm`

### Environment

- npm: 8.5.5 and up
- Node.js: 16.15.0
- OS Name: Windows 11

**Comment by sunilsurana** [comment]
Facing same issue. Lot of our workflows break with this version

**Comment by zeus-sougata** [comment]
Facing the same issue.

**Comment by abhijeet-toptal** [comment]
bumping the thread!

**Comment by abahuja** [comment]
bumping the thread!

**Comment by nlf** [comment]
this is not a bug, it's the automatic workspace detection feature in action. if you run an npm command from within a workspace directory, we automatically correct the prefix to be the root project and we set the default workspace configuration to the workspace you're in the directory of. following your example, running `npm prefix` from within `package-a` gives the same behavior as running `npm prefix -w package-a` from the root.

this change was made because before we implemented it if you were to run `npm install` inside of a workspace directory, we would end up installing that workspace's entire dep tree inside of `package-a` instead of in the shared `node_modules` of the root.

if you want to bypass this feature and you really want the prefix to be the workspace, you can run `npm prefix --no-workspaces`
