### ISSUE TITLE
[BUG] No way to escape a ${} variable on the npm or npx command line

### ISSUE THREAD

**Issue by Blackclaws** [npm/cli#5054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The issue is also documented in this issue on semantic release: https://github.com/semantic-release/semantic-release/issues/2030

Basically trying to pass any combination of '${XYZ}' as an argument to a program run via npx or npm run -- will fail as the variable will get substituted on the way. I've tried any combination of escape sequences I can think of. The only real 'solution' is to put the parameters inside a package.json scripts section where it will not be substituted.

Is there any guidance on how to properly escape variables of the type ${XYZ} when passing them as arguments? This appears to have worked in previous npm versions.

### Expected Behavior

I can pass ${XYZ} itself as an argument to a command run via npx or npm run.

### Steps To Reproduce

See linked issue.

### Environment

- npm: 8.5.5
- Node.js: v16.15.0
- OS Name: Archlinux

**Comment by nlf** [comment]
this is fixed in npm@8.13.0, however there will be a new patch release being cut in the very near future to fix an edge case.

if you can run `node -p 'require("os").tmpdir()'` and the result is a path with no spaces or special characters, then updating to npm@8.13.0 will take care of things. if you do see spaces or special characters, though, you'll want to wait until 8.13.1 is released

**Comment by nlf** [comment]
8.13.1 is published and should be working for you. please feel free to reopen this issue if you have problems after updating!
