### ISSUE TITLE
[META] Question: How to setup my `.gitignore`/`.git/info/exclude` for contributing? 

### ISSUE THREAD

**Issue by AgainPsychoX** [npm/cli#5121]
### How to setup my `.gitignore`/`.git/info/exclude` for contributing? 

The source controls shows me a lot of `node_modules` updates, after `npm install`. I don't think I should commit those, so how do I ignore them?

![image](https://user-images.githubusercontent.com/23557839/177052237-01153370-dca0-4a27-87d4-3937ccf20d9c.png)

I tried using `.git/info/exclude` but I can't get it working perfectly. While it make the 4K+ file changes go away (inside that `node_modules` alone), some are still left (240+ as visible on the screen above). How should I proceed?

**Comment by AgainPsychoX** [comment]
After restarting VS Code I found out that below seems to work. Huh.
```gitignore
# git ls-files --others --exclude-from=.git/info/exclude
# Lines that start with '#' are comments.
# For a project mostly in C, the following would be a good set of
# exclude patterns (uncomment them if you want to use them):
# *.[oa]
# *~

node_modules/
node_modules/*
node_modules/**
node_modules/**/*
**/node_modules/**
```

Nevertheless, I wish someone can confirm whenever its valid practice? Maybe [contributing guide ](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md )needs to be updated?

**Comment by ljharb** [comment]
I usually only use `.gitignore` - things inside the `.git` directory aren't committed into the repo.

Typically, `node_modules` is gitignored, and if it's a monorepo, `**/node_modules` is as well.

**Comment by AgainPsychoX** [comment]
I don't think I should touch `.gitignore` of **this** project, should I? 

It looks like this at the moment, `node_modules` is explicitly set to be **not** ignored:
```gitignore
/*

!/.github/
!/bin/
!/changelogs/
!/docs/
!/lib/
!/node_modules/
/node_modules/.bin/
/node_modules/.cache/
!/scripts/
!/smoke-tests/
!/tap-snapshots/
!/test/
!/workspaces/
# ...
```

**Comment by ljharb** [comment]
You're right, it seems like the project is not following best practices.

**Comment by wraithgar** [comment]
npm bundles all of its dependencies in the published module, this is because of the bootstrapping issue involved with installing npm itself. It has to work "out of the box".  Because of this, we also "vendor", or include, the `node_modules` contents in version control.  This is why node_modules is not ignored.  We do have a manually generated .gitignore inside that folder that ignores dev dependencies, as those should not ship with the npm cli.

As to why the node_modules is different after you run `npm install` that's another issue.  This should not be the case and in fact is not the case for the rest of us who work on the repo.  What changes do you see?

Finally, when developing on npm itself it's recommended to consider running `node .` instead of `npm`.

**Comment by wraithgar** [comment]
contributing update to suggest using `node .` is [here](https://github.com/npm/cli/pull/5159)

**Comment by nlf** [comment]
@AgainPsychoX do you happen to be a windows user? some configurations in windows may be rewriting line endings in files from `\n` to `\r\n`, there's also a somewhat annoying problem with workspace symlinks that have been committed to the repo. i do quite a bit of testing in windows and have run into similar problems myself. the dev experience for the npm CLI in windows is sadly not great.
