### ISSUE TITLE
[BUG] npx npm_config_yes=true or --yes not working as expected and npx still requires confirmation for installation

### ISSUE THREAD

**Issue by ekelvin** [npm/cli#5123]
tried npm_config_yes=true
tried --yes
and I still get requires confirmation for installation
![image](https://user-images.githubusercontent.com/6638327/177124899-10ad515d-8ada-4108-8e02-41e219f5d5a6.png)

context: 
$ npm -v
8.11.0
$ node -v
v16.15.1

**Comment by ekelvin** [comment]
Can anyone help on this? Any workaround?

**Comment by nlf** [comment]
the prompts you're seeing aren't coming from npm, it looks like the `expo` package itself is printing those and offering to globally install packages for you. you can see that here: https://github.com/expo/expo/blob/8a782c0f0d548080e0c935a9cd94c36a600af01d/packages/expo/bin/cli.js#L24-L29

unfortunately we can't help much with that. i'm going to close this since it's not our bug, but i do think it would be a good idea for you to open an issue in their repo asking them to support some form of skipping that prompt.
