### ISSUE TITLE
[BUG] `install` removes `dev: true` from lockfile while it should not

### ISSUE THREAD

**Issue by felipecrs** [npm/cli#5128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Consider the following `package.json`:

```json
{
  "name": "typedoc-plugin-rename-defaults",
  "version": "0.6.1",
  "main": "dist/src/index.js",
  "devDependencies": {
    "typedoc-plugin-rename-defaults": "."
  }
}
```

Notice how it adds itself as a `devDependency`.

Now, if I run `npm install`, it generates a `package-lock.json` as follows:

```json
{
  "name": "typedoc-plugin-rename-defaults",
  "version": "0.6.1",
  "lockfileVersion": 2,
  "requires": true,
  "dev": true,
  "packages": {
    "": {
      "name": "typedoc-plugin-rename-defaults",
      "version": "0.6.1",
      "license": "MIT",
      "devDependencies": {
        "serve": "^13.0.2",
        "typedoc": "^0.23.0",
        "typedoc-plugin-rename-defaults": ".",
        "typescript": "^4.3.5"
      }
    }
  }
}
```

Notice that it lacks `dev: true`. It should contain `dev: true`. If I run `npm update`, then `dev: true` gets added:

```diff
{
  "name": "typedoc-plugin-rename-defaults",
  "version": "0.6.1",
  "lockfileVersion": 2,
  "requires": true,
  "dev": true,
  "packages": {
    "": {
      "name": "typedoc-plugin-rename-defaults",
      "version": "0.6.1",
+     "dev": true,      
      "license": "MIT",
      "devDependencies": {
        "serve": "^13.0.2",
        "typedoc": "^0.23.0",
        "typedoc-plugin-rename-defaults": ".",
        "typescript": "^4.3.5"
      }
    }
  }
}
```

But if I run `npm install` again, it gets removed.

### Expected Behavior

Mentioned above.

### Steps To Reproduce

Mentioned above.

### Environment

- npm: 8.13.2
- Node.js: 16.15.1
- OS Name: Ubuntu 20.04
- System Model Name: N/A
- npm config:
```ini
; "user" config from /home/felipecrs/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /home/felipecrs/.volta/tools/image/node/16.15.1/bin/node
; node version = v16.15.1
; npm local prefix = /home/felipecrs/repos/typedoc-plugin-rename-defaults
; npm version = 8.13.2
; cwd = /home/felipecrs/repos/typedoc-plugin-rename-defaults
; HOME = /home/felipecrs
; Run `npm config ls -l` to show all defaults.
```

**Comment by zigsong** [comment]
I was having same problem for several days.
In my case, after I deleted `legacy-peer-deps=true` in my npm config, the problem solved.  

check your npm config via following command:
`npm config get`

**Comment by felipecrs** [comment]
@zigsong thanks for the suggestion, and it's great that it seems to be reasonable for others too.

However I don't have this setting in my configuration. And even if I had, I don't think it should cause this bug.

**Comment by nlf** [comment]
this bug is actually due to the self reference of adding your package as a dev dependency of itself. this isn't a feature that works on purpose, it just happens to in some cases by coincidence. unless we modify things to support this use case explicitly, i don't see this getting fixed.

i think the right course of action here is to open an RRFC issue at https://github.com/npm/rfcs to discuss explicitly supporting self references as a dependency type. i'm going to close this issue since it's not really a bug so much as undefined behavior, but i really hope our RFC process can shake out a clear path here that we can implement.

for a bit more context, here's my hunch at what's happening: we interpret `.` to mean `file:./`, so we put a symlink at `node_modules/typedoc-plugin-rename-defaults` that points to `../../` creating a circular reference. since we have guards to prevent infinite looping when a circular reference is present, i suspect what's happening is we're alternating between two code paths. one that installs our dev dependency and flags it as dev, and another that tries to rebuild our whole tree and removes the flag because the root node was already seen and we don't allow recursion.
