### ISSUE TITLE
[BUG] having an internal script with the same name as a builtin, runs both scripts

### ISSUE THREAD

**Issue by VividLemon** [npm/cli#5213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

If you have a script, lets say "install", in your package.json, since it conflicts with the builtin script, if you do "npm install", it will actually run both the builtin install script, and the internal install script. 

### Expected Behavior

Preferably, it would be nice if doing "npm install" ran the builtin, and "npm run install" used the internal script. But then again, maybe it's a feature and not a bug.

### Steps To Reproduce

1. Add an "install" script in package.json, I simply had it do "node ./index.js" with a simple console log script.
2. run "npm install"
3. It will install the dependencies, and also run the console log. 

### Environment

- npm:8.11.0
- Node.js:v16.14.2
- OS Name: Windows 11
- System Model Name: ?
- npm config:
```ini
; "builtin" config from C:\Users\Issayah\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\Issayah\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.14.2
; npm local prefix = C:\Apps\a
; npm version = 8.11.0
; cwd = C:\Apps\a
; HOME = C:\Users\Issayah
; Run `npm config ls -l` to show all defaults.
```

**Comment by benwalder** [comment]
It seems this may be causing an issue when installing a package like canvas.  When I run `npm install canvas@latest`, the default npm install command node-gyp rebuild is being run:

```npm info run canvas@2.9.3 install node_modules/canvas node-gyp rebuild```

instead of what is in their [package.json](https://github.com/Automattic/node-canvas/blob/master/package.json#L32 ): 

```"install": "node-pre-gyp install --fallback-to-build --update-binary",```

 When I go back to npm 6, it runs their install command instead of the default.

**Comment by fritzy** [comment]
npm has "lifecycle scripts" that run when certain actions are taken. You name your scripts after these lifecycle events in order to have them executed.

https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-install

`npm install` for example will run:
- preinstall
- install
- postinstall
- prepublish
- preprepare
- prepare
- postprepare

This is expected and documented behavior.
