### ISSUE TITLE
[BUG] `npm i -g` with `npm@next` or `npm@latest` fail

### ISSUE THREAD

**Issue by SamuelMarks** [npm/cli#5746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for npm@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for npm@latest.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### Expected Behavior

Wanted to upgrade to v9 but couldn't through the mechanisms referenced in: https://docs.npmjs.com/try-the-latest-stable-version-of-npm ; PS: what did work is `npm i -g npm@9`

### Steps To Reproduce

1. In this environment Node 18.12.0 on macOS

### Environment

- npm: latest 8
- Node.js: 18.12.0
- OS Name: macOS
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```
Vanilla config first installed on this computer a week ago

**Comment by wraithgar** [comment]
npm 9 is not tagged as `latest` yet, `npm@latest` today will get you `8.19.2`.

npm does not have a `next` tag, and that docs page doesn't mention one.

`npm@latest` installs just fine for me, and if that tag didn't exist we would have thousands of new issues because this is how most folks install the latest version of npm.

Please fill out the entire issue when making a bug report.  What is your config? What exactly did you type?  It's impossible to triage issues that we can not reproduce.

```sh
~ $ npm i -g npm@latest

removed 22 packages, changed 72 packages, and audited 212 packages in 2s

found 0 vulnerabilities
```
