### ISSUE TITLE
[BUG] npm ERR! Unexpected token '.'

### ISSUE THREAD

**Issue by yassine-klilich** [npm/cli#5770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Can't init npm, I'm getting (npm ERR! Unexpected token '.') when I run command `npm init`

![198651118-6153fd51-adac-45c3-9d6d-229da3beddcf](https://user-images.githubusercontent.com/24640070/198665473-1a4cde7a-34a5-4b5d-b7ff-dd201a7dfedf.png)

**Logs**
[2022-10-28T14_38_02_332Z-debug-0.log](https://github.com/coreybutler/nvm-windows/files/9889302/2022-10-28T14_38_02_332Z-debug-0.log)
[2022-10-28T14_38_03_129Z-debug-0.log](https://github.com/coreybutler/nvm-windows/files/9889304/2022-10-28T14_38_03_129Z-debug-0.log)

### Expected Behavior

To initialize npm

### Steps To Reproduce

1. Open CMD
2. Type `npm init`
3. Press Enter

### Environment

- nvm: 1.1.9
- npm: 8.19.2
- Node.js: 18.12.0
- OS Name: Microsoft Windows 10 Pro

**Comment by Engagement-ultra** [comment]
[![Release](https://github.com/npm/cli/actions/workflows/release.yml/badge.svg)](https://github.com/npm/cli/actions/workflows/release.yml)

**Comment by romylloydcruz** [comment]
Any solution? This also occurs for any npm install

**Comment by nlf** [comment]
this is due to a bug in nvm-windows most likely. older versions of that tool downloaded a zip archive of this repository as a means of installing npm, but now that we use workspaces in this repository those are represented in the zip archive by plain text files. one of these files is being loaded by `require()` causing the thrown error.

the fix is to update nvm-windows and reinstall node and npm with it, after that you should be fine.
