### ISSUE TITLE
[BUG] ENEEDAUTH with private registries and .npmrc on publish

### ISSUE THREAD

**Issue by Ketec** [npm/cli#6024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
npm publish --registry="https://artifactory.<domain>.com/artifactory/api/npm/npm/"
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://artifactory.<domain>.com/artifactory/api/npm/npm/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

```
@fc:registry=https://artifactory.<domain>.com/artifactory/api/npm/npm/
//artifactory.<domain>.com/artifactory/api/npm/npm/:_auth = <token>
//artifactory.<domain>.com/artifactory/api/npm/npm/:always-auth = true
//artifactory.<domain>.com/artifactory/api/npm/npm/:email = user@email.com
```
It allows installing these scoped packages, but cannot publish - it wants adduser/login. But valid .npmrc already exists.

npm config get lists the correct .npmrc.

Same problem in local, WSL and github actions.

### Expected Behavior

It should use the .npmrc to login/authenticate for npm publish.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.19.3
- Node.js: 16
- OS Name: Windows, Ubuntu etc - all of them

**Comment by ljharb** [comment]
What does `npm whoami --registry="https://artifactory.<domain>.com/artifactory/api/npm/npm/"` say? if it doesn't report you're logged in, then the .npmrc isn't correctly authorized.

**Comment by Ketec** [comment]
whoami says the same - ENEEDAUTH.

But the npmrc is valid. I see no issues with its format. And it does allow installing packages from the private repository.

If the token was invalid - I would assume auth error. If no permissions 403 or similar.

**Comment by ljharb** [comment]
Often with artifactory, the URL for the registry behaves unpredictably. Do you see the same issue on npm 9 latest, or npm 6 latest?

**Comment by Ketec** [comment]
9 seems to behave the same (trying on wsl). So it uses npmrc for reading from the repository but writing/publishing misses it.

It should match by --registry (I think it doesn't work just by namespace alone?).
Perhaps some URL regex/matching issue with custom artifactory urls?

**Comment by karlo-humanmanaged** [comment]
I encountered the same problem. But the way you can troubleshoot it is by:
1. Identify if your npm config is being overwritten by another config. Probably by an environment variable or a custom userconfig. To find out about this, run `npm config ls -l`
2. Overwrite those values by using `npm config set` or by editing the files, whichever is applicable

I'm using JFrog artifactory so mine worked in CI environment running semantic-version/npm. I found out that the `userconfig` is being overwritten (usually `userconfig` is .npmrc in the user folder) but a plugin in my pipeline overwrites that to be on /tmp/xxxxx/.npmrc . So what I did is to append the config below to the temporary .npmrc just before it executes `npm publish` . :
```
//company.jfrog.io/artifactory/api/npm/repo-name/:_authToken=<jfrog access token>
registry=https://company.jfrog.io/artifactory/api/npm/repo-name/
```
I also had to set the registry back to the default `https://registry.npmjs.org/` after the publish, because the pipeline will run another `install` later on. FYI, I didn't have any success on `publishing` using scoped configuration (like what you have), it only works for me to resolve packages.

I'm using the latest version of npm 9 (did not test with earlier versions)

I hope this helps

**Comment by fritzy** [comment]
@Ketec please re-open if this is still an issue.
