### ISSUE TITLE
[BUG] Upgrading from npm 6 to 9 breaks relative path in scripts defined in package.json

### ISSUE THREAD

**Issue by halflumi** [npm/cli#6130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

scripts definition:

```
"scripts": {
  "build-server": "./node_modules/.bin/gulp build_server",
},
```

`npm run build-server` (in cmd or powershell) gives

```
> java@1.15.0 build-server
> ./node_modules/.bin/gulp build_server

'.' is not recognized as an internal or external command,
operable program or batch file.
```

It looks like the latest version of npm takes the relative path in its literal form. Changing it to `.\\node_modules\\.bin\\gulp build_server` works, which then breaks on Linux.

### Expected Behavior

Script run without any issue (which is the case in npm 6.14.18 on Windows and Linux).

### Steps To Reproduce

1. On Windows 22H2, create an empty folder and run `npm init` inside with everything at default.
2. Create a program folder with an `echo.bat` inside:
```batch
echo hey!
```
3. Add a script entry to `package.json` that has a relative path:
```json
{
  "name": "npm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "./program/echo"
  },
  "author": "",
  "license": "ISC"
}
```
4. Run `npm test` in cmd or powershell, which gives
```
> npm@1.0.0 test
> ./program/echo

'.' is not recognized as an internal or external command,
operable program or batch file.
```
5. Changing "scripts" to:
```json
  "scripts": {
    "test": ".\\program\\echo"
  },
```
6. Run `npm test` again, and it works:
```
> npm@1.0.0 test
> .\program\echo


C:\dev>echo hey!
hey!
```

### Environment

- npm: 9.3.1 (upgraded from 6.14.18)
- Node.js: 18.14.0
- OS Name: Windows 10 22H2
- System Model Name: MS-7C94 (Windows desktop)
- npm config:
```ini
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\wch\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.14.0
; npm local prefix = C:\dev
; npm version = 9.3.1
; cwd = C:\dev
; HOME = C:\Users\wch
; Run `npm config ls -l` to show all defaults.
```

**Comment by nlf** [comment]
> It looks like the latest version of npm takes the relative path in its literal form. Changing it to .\\node_modules\\.bin\\gulp build_server works, which then breaks on Linux.

this is exactly what's at hand here. we do not modify the content of your script before attempting to run it. trying to parse and convert a script between different shells is not something we aim to achieve.

that said, i think perhaps there's a slight misunderstanding here with regard to how bins that are packaged with your dependencies can be run. the `npm run` command automatically places your project's `node_modules/.bin` directory into your PATH for you so that you don't need to specify the path to the `gulp` binary at all. changing your script to simply `gulp build_server` will work appropriately in both windows and linux.
