### ISSUE TITLE
@npmcli/config only walks up dirs for package.json files

### ISSUE THREAD

**Issue by pflannery** [npm/cli#6154]
@npmcli/config only walks up directories to find `package.json` files for local projects. [source code here](https://github.com/npm/cli/blob/latest/workspaces/config/lib/index.js#L646)

But for `.npmrc` files it only attempts to resolve one file in one location. 
The `.npmrc` resolve [source code is here](https://github.com/npm/cli/blob/latest/workspaces/config/lib/index.js#L622)

The `cwd` parameter is really important to get right if we want the npm config to parse the correct `.npmrc` for mono repo projects where the `.npmrc` could exist in the child project or it could exist in the root of the project.

In version lens I've made a work around by doing it myself then providing the @npmcli/config the `cwd` to the first `.npmrc` it finds (if any). That seems to work nicely.

Would be great if 

- @npmcli/config walked up ` .npmrc` files and parsed them itself

Would be really great if 

- @npmcli/config also walked up  .env files (so external parties have no hands on peoples `.env` files)

**Comment by nlf** [comment]
in the future please use our issue templates, they are critical for helping us understand and triage bugs.

you'll note in the line you linked for reading `.npmrc` files that it references a value at `this.localPrefix`, that value is set by the `loadLocalPrefix` method found here: https://github.com/npm/cli/blob/latest/workspaces/config/lib/index.js#L636-L701

you can see from that link that we walk up directories until we find your project root. we then load the `.npmrc` file from that project root, which is what the line you linked to does. as of today we deliberately do not support `.npmrc` files stored within workspaces, your `.npmrc` must be at the project root in order to be respected. we may consider supporting workspace level `.npmrc` files in the future, but it is not planned at this time. you are welcome to open an issue in [our rfcs repo](https://github.com/npm/rfcs) to discuss adding this support though!

> @npmcli/config also walked up .env files (so external parties have no hands on peoples .env files)

we do not read `.env` files from any locations. it's up to you to populate the environment variables yourself and we'll read config from there, but at no point has npm parsed and set values found in a `.env` file.
