### ISSUE TITLE
[BUG] Override not working correctly for nested dependencies

### ISSUE THREAD

**Issue by jmandawg** [npm/cli#6176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Nested dependencies is not the expected version.

### Expected Behavior

Nested dependency should be the one specified in the override section of package.json

### Steps To Reproduce

1. package.json
```
  "devDependencies": {
    "jest": "29.4.2"
  },
  "overrides": {
    "jest": {
      ".": "29.4.2",
      "jest*": "29.4.2",
      "jest-*": "29.4.2",
      "@jest/*": "29.4.2"
    }
  }

```
2. run "npm i"
3. Look in file:  node_modules\jest\node_modules\jest-cli\package.json
4. Version of nested dependency is not 29.4.2

### Environment

- npm: 9.4.0
- Node.js: 19.6.0
- OS Name: Win 10
- System Model Name:
- npm config:  
```ini
; copy and paste output from `npm config ls` here
```
; "user" config from C:\Users\jmmandawg\.npmrc

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v19.6.0
; npm local prefix = F:\src\project
; npm version = 9.4.0
; cwd = F:\src\project
; HOME = C:\Users\jmandawg
; Run `npm config ls -l` to show all defaults.

**Comment by phaumer** [comment]
Is there any manual workaround for this issue, because even `npm audit fix` does not work, so there is no way I can find to fix security issues. Even if I edit the lock file manually, an `npm ci` will still report the problem, even though when I do an `npm audit` afterwards I get a 0 vulnerabilities. Any developer running an `npm install` will bring the security issue back as well.

**Comment by fritzy** [comment]
Wildcards for overrides are not supported.

**Comment by phaumer** [comment]
@fritzy overrides do not work at all for workspaces and nested dependencies.
