### ISSUE TITLE
[BUG] Cannot CLI publish with OTP (redirects to npmjs.com 404 page)

### ISSUE THREAD

**Issue by nuxy** [npm/cli#6242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running the following commands results with:
```
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
Authenticate your account at:
https://www.npmjs.com/auth/cli/6aa5f853-e556-4e5c-b6b7-277d88fc68ab
Press ENTER to open in the browser...
```

The URL above results with a 404 page "Route not found!"

### Expected Behavior

To match the following NPM v8 publishing workflow:
```
npm notice Publishing to https://registry.npmjs.org/
This operation requires a one-time password.
Enter OTP: XXXXXX
```

### Steps To Reproduce

Run `npm publish` on a NPM hosted project.

### Environment

- npm: 9.6.1
- Node.js: v16.15.1
- OS Name: Ubuntu
- System Model Name: 16.04 LTS
- npm config:
```ini
; "user" config from /home/mbrooks/.npmrc

//registry.npmjs.org/:_auth = (protected) 
//registry.npmjs.org/:_authToken = (protected) 
email = "devel@mbrooks.info" 
init-author-email = "devel@mbrooks.info" 
init-author-name = "Marc S. Brooks" 
init-author-url = "https://mbrooks.info" 
progress = false 

; node bin location = /usr/local/bin/node
; node version = v16.15.1
; npm local prefix = /home/mbrooks/Desktop
; npm version = 9.6.1
; cwd = /home/mbrooks/Desktop
; HOME = /home/mbrooks
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment]
You can add `auth-type=legacy` to `~/.npmrc` if you want the older behavior back.

**Comment by fritzy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.

**Comment by shellscape** [comment]
@fritzy that's what we call "tossing the ball over the fence." if a core component of the client is impacted by an upstream dependency _(and it still is as of 21:37 ET, 8 hours after your reply)_ then it's reasonable that the client should have some kind of intelligence around a brittle upstream dependency. at the least, offering an open to revert to the legacy auth type via input in the moment.

I know that Microsoft and Github has some really excellent product minds on board, let's put those to good use and really provide a great DX for the users, rather than taking the corporate route and putting the onus on another team.

There's also a really nifty feature of Github that allows one to transfer an issue to an appropriate repo.

**Comment by plynchnlm** [comment]
I had the same issue and started out at npmjs.com/support, which is the route @fritzy suggests here.  Ironically, the person who responded to me there directed me to post an issue here at https://github.com/npm/cli/issues, and before doing that I found this issue, already posted-- and closed -- and directing us back to npmjs.com/support.  Anyway, the work-around suggested by @ljharb does solve the problem for the present.

**Comment by nuxy** [comment]
:checkered_flag: **In case anyone else experiences this issue.** :checkered_flag:

It seems that at some point (I suspect post Microsoft transition) my password was reset for my NPM account.

Once I changed my password, which included TOTP authentication, I was no longer receiving the 404 page.

Hope this helps.

**UPDATE (4/18/2023)**
You must also be logged in to [npmjs.com](https://npmjs.com) or you will still receive the 404 error.

**Comment by mkantor** [comment]
Just had this happen to me after somehow getting logged out of my npm account (I don't recall clearing my cookies, but maybe I did). Logging back in using the web UI and then trying again fixed it, but the 404 was initially confusing and I thought there might be some technical problem.

It feels like this ought to have redirected me to the login page rather than giving me a 404 error, or at least given me a more descriptive status like 401.
