### ISSUE TITLE
[BUG] npm exec removes .gitignore files

### ISSUE THREAD

**Issue by smoliji** [npm/cli#6292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running a package directly from github using npm exec runs it without its `.gitignore` files.

Files in temp. installation directory:
```
➜  npm-removes-gitignore git:(main) tree /home/smoliji/.npm/_npx/8a4444a8203a8303/node_modules/npm-removes-gitignore
/home/smoliji/.npm/_npx/8a4444a8203a8303/node_modules/npm-removes-gitignore
├── bin.js
├── files_i_need
│   └── somejs.js
├── package.json
└── README.md

1 directory, 4 files
```

### Expected Behavior

Running a package directly from github using npm exec runs it with all the files that should be part of the package as per [package.json docs for file property](https://docs.npmjs.com/cli/v8/configuring-npm/package-json?v=true#files)

> Omitting the field will make it default to ["*"], which means it will include all files."

I expect the installed files to look like original source, i.e. with .gitignore

```
➜  npm-removes-gitignore git:(main) tree /home/smoliji/.npm/_npx/8a4444a8203a8303/node_modules/npm-removes-gitignore
/home/smoliji/.npm/_npx/8a4444a8203a8303/node_modules/npm-removes-gitignore
├── bin.js
├── files_i_need
│   ├── .gitignore
│   └── somejs.js
├── package.json
└── README.md

1 directory, 5 files
```

### Steps To Reproduce

Example repo available here: https://github.com/smoliji/npm-removes-gitignore

1. run `npm exec --yes -- github:smoliji/npm-removes-gitignore`
2. See error
```
file: somejs.js
// important contents

file: .gitignore
ENOENT: no such file or directory, open '/home/smoliji/.npm/_npx/8a4444a8203a8303/node_modules/npm-removes-gitignore/files_i_need/.gitignore'
```

### Environment

- npm: 8.19.2
- Node.js: v18.12.1
- OS Name: Ubuntu 22.04.1
- System Model Name: Lenovo X1 Carbon 6th gen
- npm config:
```ini
; "user" config from /home/smoliji/.npmrc

; node bin location = /home/smoliji/.nvm/versions/node/v18.12.1/bin/node
; node version = v18.12.1
; npm local prefix = /home/smoliji/projects/npm-removes-gitignore
; npm version = 8.19.4
; cwd = /home/smoliji/projects/npm-removes-gitignore
; HOME = /home/smoliji
; Run `npm config ls -l` to show all defaults.
```

**Comment by nlf** [comment]
this is intentional behavior. when we run a package from a git repository we download an archive of the repository, if necessary run prepare scripts, and then pack the directory and install it.

you can see that `npm pack --dry-run` from in your project does not include the gitignore file. this is because by default, we omit many files that are commonly seen which do not have a direct effect on the packaged tarball. the list of files that are ignored by default can be seen here: https://github.com/npm/npm-packlist/blob/main/lib/index.js#L15-L38

any files that are in that list that you want to be included in your packed tarball need to be added explicitly to your package.json `files` array. for this example case, you would want a files array of `["files_i_need/*", "files_i_need/.gitignore"]`

**Comment by smoliji** [comment]
Ok. I kind of understand the motivation for the common use case, but still find the "all" in the "Omitting the field will make it [...] include all files." confusing, because it made me think it should be included by default. Thanks!

**Comment by qiufeihong2018** [comment]
@nlf Specify the files array, npm install is still missing .gitignore after downloading
