### ISSUE TITLE
[BUG] <Node 18.16.0 doesn't support npm 9.5.1>

### ISSUE THREAD

**Issue by kkarol012** [npm/cli#6478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When run `npm` it throws error:
> ERROR: npm v9.5.1 is known not to run on Node.js v18.16.0. You'll need to upgrade
> to a newer Node.js version in order to use this version of npm. This version of
> npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You
> can find the latest version at https://nodejs.org/.

### Expected Behavior

I can use npm v9.5.1 with node 18.16

### Steps To Reproduce

1. install latest node with `nvm install 18.16.0`
2. run `npm`
3. see error

### Environment

- npm: 9.5.1
- Node.js: 18.16
- OS Name: Windows

**Comment by BobGerman** [comment]
Same issue here - thanks

ERROR: npm v9.5.1 is known not to run on Node.js v18.16.0. You'll need to upgrade
to a newer Node.js version in order to use this version of npm. This version of
npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You
can find the latest version at https://nodejs.org/.

Is 18.16 >= 18.0.0 ?
:-)

**Comment by BobGerman** [comment]
FWIW I found a solution here:
https://stackoverflow.com/questions/76141482/npm-v9-5-1-is-known-not-to-run-on-node-js-v18-16-0

This appears to be an nvm for Windows problem not an npm problem. The work-around is to upgrade nvm, then uninstall and reinstall 18.16.0. It worked for me ...

**Comment by kkarol012** [comment]
Thanks for your help. It works
