### ISSUE TITLE
How do I clone the NPM Registry?

### ISSUE THREAD

**Issue by jdai1** [npm/cli#6562]
Hi,

I am trying to clone the NPM registry at [https://replicate.npmjs.com/]. I have currently tried a number of things.

1) Posting a request to the couchdb _replicate endpoint with a target of a local couchdb. 

In this case, I believe that the npm registry has checkpointing disabled, so it must restart on any form of error. When I try to replicate with checkpoints enabled, I run into an error that says source commit failure. However, when I disable checkpointing, the replication almost always fails, even when I change around the configuration options

2) Sending a get request to https://replicate.npmjs.com/registry/_all_docs.

Receiving the entire data for this endpoint on a get request takes a very long time because the download speed is very slow. It usually fails when I can get around 300,000 lines of the 3,000,000 in the registry endpoint.

Is there an easier way to clone the entire registry?

**Comment by seng1e** [comment]
1. couchdb provide a `seq` for every event in stream. You can use this `seq` to orderly listen for changes to npm packages and then do your own parsing into the local database.
 for example: posting a request to https://replicate.npmjs.com/_changes?since=23010000, and get changes from seq=23010000. This `seq` number is ordered, so that when an error occurs, the `seq` can be backtracked and re-parsed

2. from https://replicate.npmjs.com/registry/_all_docs download all metadata, You can use the `limit`, `skip` and `startkey` parameters provided by the api to download the entire data on a sliding basis using the offsets. Of course it may take longer to download this way, but you can be sure to download a copy of the metadata completely.
for example:
posting a requests to :
https://replicate.npmjs.com/_all_docs?include_docs=true&limit=50&skip=0&startkey="regex"

**Comment by milaninfy** [comment]
**Closing:** this looks to be a general support question which is outside the scope of the repo. For support please post your question to [github.community](https://github.community).
