### ISSUE TITLE
[BUG] avoid accidentally running code from un-installed packages

### ISSUE THREAD

**Issue by mikemaccana** [npm/cli#6750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

This seems to be an unsafe default - to the point where a typescript stub package now advertises using yarn:

If the user forgot to run `npm i typescript`

```
% npx tsc --init


                This is not the tsc command you are looking for


To get access to the TypeScript compiler, tsc, from the command line either:

- Use npm install typescript to first add TypeScript to your project before using npx
- Use yarn to avoid accidentally running code from un-installed packages
```

This is presented as a big red warning that npm is unsafe:

<img width="730" alt="Screenshot 2023-08-31 at 16 32 18" src="https://github.com/npm/cli/assets/172594/353cd545-d7a3-4888-a01a-5c787f3e342b">

I hate the idea that people are having to use alternatives to avoid unsafe defaults. 

### Expected Behavior

A message that `tsc` isn't installed program.

### Steps To Reproduce

1. npm 9.8.1
2. Don't install `typescript`
3. Run `npx tsc --init`
4. See error above.

### Environment

```
% npm config ls
; node bin location = /usr/local/bin/node
; node version = v18.16.1
; npm local prefix = /Users/mikemaccana/Code/someapp/someapp-developers/someapp-helpers
; npm version = 9.8.1
; cwd = /Users/mikemaccana/Code/someapp/someapp-developers/someapp-helpers
; HOME = /Users/mikemaccana
```

**Comment by wraithgar** [comment]
How is npm supposed to know that `tsc` is part of `typescript` and not the package named `tsc` unless you tell it?

`npx` does have a way to tell npm that `typescript` is the package in which to look:

```sh
$ npx -p typescript tsc
Need to install the following packages:
typescript@5.2.2
```

When `typescript` is installed globally, it specifies that it also has a `tsc` binary so that is found in the future. But unless that's done it's not something npm can "discover".  This is unfortunately not a solvable problem if packages define executable names that are not the same as their package name.  The name of the executable and the package either have to match, or users have to tell npm which package to use.

**Comment by mikemaccana** [comment]
> How is npm supposed to know that tsc is part of typescript and not the package named tsc unless you tell it?

By `typescript` being installed, and `tsc` not being installed.

> When typescript is installed globally, it specifies that it also has a tsc binary so that is found in the future. 
> But unless that's done it's not something npm can "discover"

If `typescript` is installed locally, isn't there `.node_modules/.bin`, which could be looked for?

**Comment by wraithgar** [comment]
Yes, npm will look for it locally too.

```sh
~/D/n/s/npx $ npx tsc --version
Version 5.2.2
~/D/n/s/npx $ npm pkg get dependencies
{
  "typescript": "^5.2.2"
}
```
