### ISSUE TITLE
Allow package.json "engines" to support LTS

### ISSUE THREAD

**Issue by rluvaton** [npm/cli#6833]
There are cases where a package only supports the LTS versions of node.

```json
{
  "engines": {
    "node": "lts"
  }
}
```

so 

This is an example of which versions would be available:

|           | `lts`              | Notes                                                    |
|-----------|--------------------|----------------------------------------------------------|
| Jul, 2020 | 10, 12, 14         |                                                          |
| Nov, 2020 | 10, 12, 14, 15     | In Oct, 2020 v14 reaches LTS and v15 is released         |
| May, 2021 | 10, 12, 14, 15, 16 | In Apr, 2021 v10 reaches EOL and v16 is released         |
| Jul, 2021 | 10, 12, 14, 16     | On 1/Jun/2021, v15 reaches EOL and is removed from `lts` |
| Nov, 2021 | 10, 12, 14, 16, 17 | In Oct, 2021 V16 reaches LTS and v17 should be released  |

we can use this to find our which node.js versions are currently alive:
https://raw.githubusercontent.com/nodejs/Release/master/schedule.json

Related issues:
- https://github.com/npm/npm/issues/11113

there was interest a long time ago:
- https://github.com/npm/npm/issues/11113#issuecomment-172436759

and wanna know if we can implement it now (I'm willing to do it of course)

**Comment by ljharb** [comment]
That doesn't make sense, because that's not how semver works. If in package X at version Y you say you support a version of node Z, then X@Y must support Z *forever*. The passage of time, nor arbitrary schedule changes for LTS support, *must not* suddenly allow something to stop working.

If you want to match LTS, then you need to manually make a breaking change every time something goes EOL, and a minor version every time something enters LTS. There's no way around that.

**Comment by rluvaton** [comment]
I didn't think about it that way, you are right

**Comment by rluvaton** [comment]
Because this is only been validated when installing packages what if we use the date that this version is published (I'm pretty sure we have that) and we can know the LTS in that time

**Comment by ljharb** [comment]
That’s certainly possible, but dropping support of something is a breaking change, and that’s not something you want to automate.

**Comment by wraithgar** [comment]
There are two issues with this.  First, tags are not a safe way to specify versions in manifests. Tags are mutable and can point anywhere with no semver contract.
Second, there is no mechanism to "translate" lts tags on node versions like there are with npm versions.

This is not something we are likely to implement.  If you think these two problems are solvable please submit an [rfc](https://github.com/npm/rfcs) issue.

**Comment by wundersolutions-juanjo** [comment]
> The passage of time, nor arbitrary schedule changes for LTS support, must not suddenly allow something to stop working

Doesn't the existence of `latest` for `dependencies` kinda invalidate this point? 
One could even argue that the `^` and `~` operators do cause things to stop working at times, either by one of the dependencies not strictly following semver or a simply bug being introduced in a new patch release.

As far as I know, this is what `package-lock` aims to address, itself keeping a "known-good" set of pinned versions of the dependencies. Couldn't it also keep the "resolved" `engines` declaration for the current set of packages?

**Comment by ljharb** [comment]
No, it doesn't, because "latest" is a (dangerous, very ill-advised) way for a *consumer* to opt out of protection from breaking changes. Certainly a bug could break anything at any time, but bugs will be fixed (and "not following semver" is also a bug).

Lockfiles are only for applications, and `engines` declarations are also for packages.
