### ISSUE TITLE
[BUG] npm update -g npm on Node 20.3.1 issues "EBADENGINE Unsupported engine" warnings. Did I break my installation??

### ISSUE THREAD

**Issue by futuremotiondev** [npm/cli#6866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`PS C:\Users\[username]\Desktop> nvm use 20.3`
> Now using node v20.3.1 (64-bit)

`PS C:\Users\[username]\Desktop> npm update -g npm`
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'npm@10.2.0',
> npm WARN EBADENGINE   required: { node: '^18.17.0 || >=20.5.0' },
> npm WARN EBADENGINE   current: { node: 'v20.3.1', npm: '9.8.1' }
> npm WARN EBADENGINE }

> removed 2 packages, and changed 62 packages in 3s

Should I be concerned? Did I just break `npm` on `20.3.1`?

Any info would be appreciated. I thought  `npm update -g npm` would automatically select the appropriate version for my version of node.

### Expected Behavior

No warnings or errors. A compatible version of npm gets installed.

### Steps To Reproduce

1. Ensure you have `nvm` installed.
2. Ensure you installed Node.js v20.3.1 via `nvm`
3. Run `nvm use 20.3.1`
4. Run `npm update -g npm`
5. See error... (hopefully reproducable)

### Environment

- npm: `npm --version` gives me this:
```
WARN cli npm v10.2.0 does not support Node.js v20.3.1. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.
10.2.0
```
- Node.js: v20.3.1
- OS Name: Windows 10 Pro x64 Version 22H2 (Build 19045.3448)
- System Model Name: PC, Custom Built
- npm config: 
```ini
; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\[username]\Desktop
; HOME = C:\Users\[username]
; Run `npm config ls -l` to show all defaults.
```

**Comment by futuremotiondev** [comment]
As a note, I just downgraded to [9.8.1](https://www.npmjs.com/package/npm/v/9.8.1). After checking the `NPM` versions on npmjs, it seems 9.8.1 was the immediate version prior to 10. 

I just want to check -  Is there a more recent update compatible with Node `v20.3.1`?

Thanks!

**Comment by lukekarrys** [comment]
Two things:

1. It would be nice if `npm install npm@latest -g` was able to select an appropriate version of npm based on the version of node. This would be best brought up as an RFC since there would be some more nuance to that feature that should be discussed: https://github.com/npm/rfcs/issues/new/choose

2. `npm@10` supports `^18.17.0 || >=20.5.0`, so you are not missing anything. And you should not have broken your `npm` install. That error message you received is saying that it did not  complete the install since your target version of `npm` is not supported by your current version of `node`. I would recommend updating to the latest version of node 20 or 18 for now.
