### ISSUE TITLE
[BUG] npm Can't find path to an installed module's command.

### ISSUE THREAD

**Issue by AuricX** [npm/cli#6964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm does not recognize the commands from the installed modules when using npm run <command>
it is a path issue since `export PATH=./node_modules/.bin:$PATH` and then running the commands works.

### Expected Behavior

npm should add the path to the node-modules folder whenever using npm run <command>.

### Steps To Reproduce

1. Create a vite app with npm init vite@latest
2. Default config
3. cd into the created project, run npm install, run npm run dev
4. sh: vite: command not found
5. try npm run build, tsc command not found

### Environment

- npm: 10.2.3
- Node.js: 21.1.0
- OS Name: MacOS Sonoma
- System Model Name: MacBook Air M1 8GB 8C CPU 7C GPU

**Comment by AuricX** [comment]
Current Temporary Solution: Add the export command stated above to the .zshrc file.
This way it is run whenever a new terminal session is opened.

**Comment by ljharb** [comment]
That temporary solution is very dangerous, as it can cause your builtin commands to be silently shadowed by any package in your graph.

What you’re saying it should do, it already does and always has done, so if it’s not working, that’s the bug.

You can run `npx vite` etc to confirm if that is running the installed one or not?

**Comment by wraithgar** [comment]
I think you've confused `npm run` with `npm exec`.  `run` looks in the `scripts` entry of your local package.

When you create a new vite project, the only scripts it provides appear to be:

```sh
~/D/n/s/v/vite-project $ npm pkg get scripts
{
  "dev": "vite",
  "build": "tsc && vite build",
  "preview": "vite preview"
}
```

Those are the only things you would expect `npm run` to work for.  `npm exec` will find `vite` because one of the packages defines that in its `bin` entry.  `npm run dev` will also work because of the same reason.

npm appears to be working as intended here.  `npm run dev` and `npm exec vite` both work for me locally after creating a new vite package and running `npm install`

**Comment by wraithgar** [comment]
I can't reproduce this locally. When I run `npm init vite@latest`, let everything default, cd into `vite-project` and run `npm install`, the commands all work as expected
