### ISSUE TITLE
[BUG] `npm init` duplicates `optionalDependencies` to `dependencies`

### ISSUE THREAD

**Issue by christianbundy** [npm/cli#724]
# What / Why

Recently I've been running `npm init` on modules to ensure that `package.json` is well-formed and has all of the relevant data. I just noticed a fun bug where `npm init` copies your `optionalDependencies` to `dependencies`, which [the documentation](https://docs.npmjs.com/files/package.json#optionaldependencies) discourages:

> Entries in **`optionalDependencies`** will override entries of the same name in **`dependencies`**, so it’s usually best to only put in one place.

## When

I run `npm init` on a module with optional dependencies.

## Where

* n/a

### Current Behavior

`npm init` duplicates `optionalDependencies` to `dependencies`

### Steps to Reproduce

- `cd $(mktemp -d)`
- `npm init -y`
- `npm i --save-optional lodash`
- `npm init -y`

I've made a Git repository with the output tree of each command [here](https://github.com/christianbundy/wtf-npm/commits/master).

### Expected Behavior

npm should not duplicate `optionalDependencies` to `dependencies`

## Who

* n/a

## References

* n/a

**Comment by Huauauaa** [comment]
`dependencies` is not ```{}```, when I run ``` npm init```

**Comment by christianbundy** [comment]
Sorry, could you explain what you mean or maybe give some context? I don't think that I understand.

**Comment by Huauauaa** [comment]
> Sorry, could you explain what you mean or maybe give some context? I don't think that I understand.

when I run `npm init -y`, there are  many dependencies in package.json

**Comment by Huauauaa** [comment]
> > Sorry, could you explain what you mean or maybe give some context? I don't think that I understand.
> 
> when I run `npm init -y`, there are many dependencies in package.json

I remove the node_modules, and run `npm init -y` again , it is normal, thanks anyway

**Comment by feross** [comment]
I am noticing this same issue on npm 7.0.6.

**Comment by christianbundy** [comment]
Fancy seeing you here. 

I _think_ this bug is happening here: https://github.com/npm/init-package-json/issues/93

But I haven't had time to track it down.

**Comment by feross** [comment]
It's happening when I run `rm -rf node_modules package-lock.json && npm install`.

Does `npm install` trigger `npm init` internally?

**Comment by christianbundy** [comment]
I'm not sure, but I found the problem -- maybe this code is being called without `npm init`?

https://github.com/npm/normalize-package-data/blob/f2373b1bb423bb390e331658ed696483c6418d69/lib/fixer.js#L371-L379

I don't know what the use-case is for adding `optionalDependencies` to `dependencies`. I'll open a PR fixing it and maybe the maintainer will tell me why that's bad. 🙃

**Comment by davidje13** [comment]
The mutating `normalize-package-json` behaviour has been there since the very first commit of that repository. And that repo is used in a lot of places by the various packages here. I suspect your change might be a bit dangerous.

I tried to track down what actually happened to break this (specifically, making `npm install` copy optional dependencies into regular dependencies, which is clearly broken behaviour. I can't speak about `npm init`).

It looks like the `install` command of the CLI [uses `arborist`](https://github.com/npm/cli/blob/latest/lib/install.js#L32), which [uses `read-package-json`](https://github.com/npm/arborist/blob/main/lib/arborist/load-actual.js#L208), which [passes its output through `normalize-package-json`](https://github.com/npm/read-package-json/blob/latest/read-json.js#L424). So `arborist`'s view of the package.json is mutated. Also `arborist.reify` will conditionally [save its view of the package.json file](https://github.com/npm/arborist/blob/main/lib/arborist/reify.js#L844) (the comments suggest this is so that `--save` / `--save-dev` work).

The use of arborist at all for `install` is a version 7 change (edfc8167d was one of the earlier commits on the v7 branch, finally merged in fff3e8eae with the release of version 7).

The problem seems pretty obvious. Sadly it looks like it wasn't introduced by a specific change, but by a large rewrite of the system, so it's not easy to compare it to how it used to work. The result of my analysis though is that whatever needs fixing, it needs fixing in the `arborist` package.

**Comment by vegerot** [comment]
I am experiencing this as well
