### ISSUE TITLE
[BUG] "_postinstall" script unexpectedly runs after install

### ISSUE THREAD

**Issue by djcsdy** [npm/cli#7322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Since npm 10.4.0, when installing a package, if there is a script named `_postinstall`, npm seems to run it as if it were a `postinstall` script.

I would expect this to break installation of a *lot* of packages because of wide usage of the tool `pinst`. This tool is intended to disable `postinstall` scripts before publication, and it works by renaming the script to `_postinstall`.

### Expected Behavior

I expect npm to run scripts named `postinstall` after installation.

I don't expect npm to run scripts named `_postinstall` after installation.

npm 10.3.0 and earlier behave as expected.

### Steps To Reproduce

In Windows 10:

```powershell
npm i -g "@djcsdy/npm-bug-maybe@1.0.8"
```

Output:

```txt
npm ERR! code 1
npm ERR! path C:\Users\djc\AppData\Roaming\nvm\v20.11.1\node_modules\@djcsdy\npm-bug-maybe
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c bibble
npm ERR! 'bibble' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in: C:\Users\djc\AppData\Local\npm-cache\_logs\2024-03-28T20_02_56_746Z-debug-0.log
```

The package `@djcsdy/npm-bug-maybe` contains a `_postinstall` script with the text `bibble`, see: https://www.npmjs.com/package/@djcsdy/npm-bug-maybe?activeTab=code

### Environment

- npm: 10.4.0 (tested with 10.5.0 also)
- Node.js: 20.11.1
- OS Name: Windows 10
- System Model Name: PC cobbled together out of parts
- npm config:
```ini
; "user" config from C:\Users\djc\.npmrc

//npm.pkg.github.com/:_authToken = (protected)
//registry.npmjs.org/:_authToken = (protected)

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.11.1
; npm local prefix = C:\Users\djc\Code
; npm version = 10.4.0
; cwd = C:\Users\djc\Code
; HOME = C:\Users\djc
```

**Comment by milaninfy** [comment]
@djcsdy this is reproducible only for this package. if you manually create and publish package without pinst and rename your script to _postinstall it does not get executed. 

when I checked the more information on publishing details, here is what I found from this link https://registry.npmjs.org/@djcsdy%2fnpm-bug-maybe

```sh
user@laptop % npm view @djcsdy/npm-bug-maybe@1.0.8 scripts

{
  postinstall: 'bibble',
  prepack: 'pinst --disable',
  postpack: 'pinst --enable'
}
```

since it has regular postinstall script it try to execute. Don't think this is an issue with npm-cli.

**Comment by djcsdy** [comment]
@milaninfy You may be right that it's not an issue with the npm CLI, but something weird is happening somewhere in the npm infrastructure.

You can download the tarball for yourself direct from npm and see:

https://registry.npmjs.org/@djcsdy/npm-bug-maybe/-/npm-bug-maybe-1.0.8.tgz

Look in package.json. No `postinstall` script. But for some reason `npm view` and `npm install` are acting as if there is.

![image](https://github.com/npm/cli/assets/310800/4b220fad-489e-4ca4-b2f4-60ece4143563)

**Comment by djcsdy** [comment]
I'm not familiar with the internals of the npm publishing process, but I'm guessing perhaps package metadata gets uploaded separately from the package itself. ~I probably published this using yarn, and I'm guessing yarn reads the package metadata before running prepack scripts. In which case the problem might be yarn. Investigating.~

I published this using npm. Perhaps npm reads the package metadata before it runs the prepack script?

I think also maybe the actual difference between npm 10.3 and 10.4 is that 10.3 runs the `postinstall` script specified in the tarball, whereas 10.4 runs the `postinstall` script specified by the package metadata on the npm registry, but I'm just guessing at this point.

**Comment by djcsdy** [comment]
This bug report is not accurate, but I do think there is a bug here. I am preparing a new report and will close this one for now.

**Comment by djcsdy** [comment]
@milaninfy Thank you for your input on this.

**Comment by zburke** [comment]
@djcsdy, you mentioned back in April that this report was not accurate but "I do think there is a bug here" and that you would file a new report. Did you ever file that report? In https://github.com/SimenB/add-asset-html-webpack-plugin/issues/373, we continue to see exactly the problems described here, namely:
1. registry.npmjs.org contains metadata for a `package.json`'s `scripts` attribute that differs from the contents of the module tarball, i.e. the actual assets, itself
2. npm <= 10.3.x appears to read metadata from the module tarball while versions >= 10.4.x appear to read from the registry

For example, registry metadata for add-asset-html-webpack-plugin at https://registry.npmjs.org/add-asset-html-webpack-plugin contains `scripts.postinstall` whereas the actual `package.json` in corresponding asset https://registry.yarnpkg.com/add-asset-html-webpack-plugin/-/add-asset-html-webpack-plugin-6.0.0.tgz contains `scripts._postinstall`. 

Both feel like real problems. Of course there should not be a discrepancy between the registry and the assets, but given that there is and that it is long-standing, it feels like the new behavior in 10.4.x (use the registry instead of the actual assets as the source of truth) was a breaking change that should have been released in a new major version.

**Comment by djcsdy** [comment]
@zburke I agree with everything you've said. The reason I was being cagey is because I considered the underlying problem to be a security flaw, so I reported it to npm privately via HackerOne. They responded that they were aware of the issue and were tracking it internally so at the time I left it at that. I stopped providing information in public in line with the usual protocol for reporting security flaws.

I've since been informed that [the underlying problem has been public knowledge for a long time](https://blog.vlt.sh/blog/the-massive-hole-in-the-npm-ecosystem). It's fair to assume that npm have known about this issue for about as long as it has been public knowledge, probably longer, but so far in over a year the actions they have taken have only exacerbated the problem.

Considering their actions so far, it's my opinion that npm either don't care about this problem or are incompetent to even attempt to fix it without making things worse, so I haven't bothered engaging further.

I published a [write-up of my own findings](https://gist.github.com/djcsdy/2f5a287b3ba16f2a8f0312f45588e6ce) a few days ago if you're interested.

If you want to report this to npm as a bug, please do. The above blog post and my findings should give you enough information to make a complete report, and I'm happy to help you fill in any gaps if needed.

**Comment by xobotyi** [comment]
For those facing issues while using `pinst` along with `semantic-release`:

Although `pinst` recommends using `prepack` and `postpack` scripts to handle the `postinstall` script, this method only works for tarball creation and not during the stage of sending metadata to the npm registry.

The workaround is to remove the `prepack` and `postpack` scripts altogether and perform `pinst --disable` within CI, before building and releasing the package, re-enabling it back only after release phase (if needed).

**Comment by djcsdy** [comment]
@xobotyi That approach works, or alternatively you can use [semantic-release-pinst](https://www.npmjs.com/package/semantic-release-pinst) which integrates pinst as part of the semantic-release process itself.

(But to be honest running `pinst --disable` in your CI script is probably more straightforward than using the plugin, unless you already have a customized semantic-release configuration).

This does remind me that I never got around to documenting semantic-release-pinst so I should probably get on that.
