### ISSUE TITLE
[BUG] Different maintainer list output by CLI with different flags

### ISSUE THREAD

**Issue by robatwilliams** [npm/cli#7620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm view ms` - gives 8 maintainers under the "maintainers:" section, matching npmjs.com
`npm view ms --json` - gives 55 maintainers under the "maintainers" key
`npm view ms maintainers` - gives 55 maintainers under the "maintainers" key

### Expected Behavior

The commands give the same maintainer list, which matches the Collaborators sidebar section on npmjs.com

Definition of maintainer: https://github.com/npm/www/issues/133#issuecomment-284906561

### Steps To Reproduce

Run the above commands for presumably any package (I used ms as an example)

May be related to #2266 which was closed without investigation.

### Environment

- npm: 10.7.0
- Node.js: 20.14.0
- OS Name: Windows 10
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by robatwilliams** [comment]
`npm owner ls` also gives the 8, so that's an alternative while this issue remains

**Comment by reggi** [comment]
Here's my explanation:

*  `ms` package currently has 8 maintainers
*  It was last published with a `latest` version over a year ago
*  I believe at the time of publish it had 55 maintainers and has since been changed
* `npm view ms` lists the current maintainers for the package
* `npm view ms maintainers` lists the maintainers for the latest published package
* `npm view ms` operates on the packument level
* `npm view ms [with any flags]` is a query to the latest version's manifest

I think we can close this one out unless anyone has any objections, feel free to comment below / open a new issue and link back to this one.

**Comment by ljharb** [comment]
also `npx publishers ms` will list who published each version (altho, not who *could* have published at that time)
