### ISSUE TITLE
[BUG] Unable to upgrade two packages with a dep and peer dep on the same package that is also bumped

### ISSUE THREAD

**Issue by Artur-** [npm/cli#7719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
npm init
npm i vite-plugin-checker@0.6 vite-plugin-dts@3 --save-dev
npm i vite-plugin-checker@0.7 vite-plugin-dts@4 --save-dev
```

fails with

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vite-plugin-checker@0.6.4
npm ERR! node_modules/vite-plugin-checker
npm ERR!   dev vite-plugin-checker@"0.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev vite-plugin-checker@"0.7" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue-tsc@2.0.29
npm ERR! node_modules/vue-tsc
npm ERR!   peerOptional vue-tsc@">=2.0.0" from vite-plugin-checker@0.7.2
npm ERR!   node_modules/vite-plugin-checker
npm ERR!     dev vite-plugin-checker@"0.7" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Expected Behavior

```
npm init
npm i vite-plugin-checker@0.7 vite-plugin-dts@4 --save-dev
```

works fine and installs the new versions

### Steps To Reproduce

As above

### Environment

- npm: 10.8.2
- Node.js: v20.12.2
- OS Name: macOs
- System Model Name: Macbook M1
- npm config:
```ini
ignore-scripts = true
```

**Comment by neehhaa06** [comment]
Hello @Artur-  :)

> Have you followed these steps?

```
Clear npm cache.

Install packages with --legacy-peer-deps option.

If needed, use --force option to override conflicts.

Update all dependencies.

If the issue persists, delete node_modules and package-lock.json, then reinstall dependencies.
```

**Comment by Artur-** [comment]
The bug is that you cannot upgrade the packages without using `--force` or `--legacy-peer-deps`. 

If you remove `node_modules` and `package-lock.json` you can also install the new versions. You can also install them in a clean project. But that is not the bug.

**Comment by Tayvon** [comment]
@Artur-  Thanks for filing this! This is currently working as intended.

The issue here is the order in which the packages are being installed.

- `vite-plugin-dts@3` has a dependency on `vue-tsc^1.8.27` and `vite-plugin-checker@0.6` has `vue-tsc@">=1.3.9"` as peerOptional , so `npm` installs `vue-tsc@1.8.27` which satisfies everything
- when running the 2nd install command to update both packages the `vite-plugin-checker@0.7`,  which has a peerOptional dependency on `vue-tsc@>=2.0.0`, conflicts with the dependency of `vite-plugin-dts@3` since it's expecting `^1.8.27`

Try installing `vite-plugin-dts@4` first so that it will install vue-tsc@2.0.29  since it is a dependency for it.
Then install `vite-plugin-checker@0.7` thereby satisfying the peerDependency specs for it.

```
npm init
npm i vite-plugin-checker@0.6 vite-plugin-dts@3 --save-dev

npm i vite-plugin-dts@4 --save-dev
npm i vite-plugin-checker@0.7  --save-dev
```

For more information on how `npm` handles peer dependencies, feel free to checkout the rfc's on [installing peer dependencies](https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md) and [handling peer conflicts](https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md).

**Comment by Artur-** [comment]
The actual problem I am facing is that there is a tool that upgrades package.json and then the new versions should be installed. You end up with something similar to this
```
npm init
npm i vite-plugin-checker@0.6 vite-plugin-dts@3 --save-dev
npx npm-check-updates -u
npm i
```

and this also fails the same way.

Don't you think it is a bit odd that you cannot upgrade both packages at the same time even though they are compatible? And that you can install the packages using the final package.json only if you remove both `package-lock.json` and `node_modules` first?

It is a problem to us as we are basically shipping an update to `package.json` as part of a version upgrade and there is no way to run individual `npm i` commands in some predefined order.

**Comment by Tayvon** [comment]
You can also install the packages with the `--legacy-peer-deps` flag set on the `npm i` command, which will [ignore all peer dependencies when installing](https://github.com/npm/rfcs/blob/40fc9931438931e95708a6917c3e3dea3864c230/implemented/0031-handling-peer-conflicts.md#detailed-explanation). 

The point i'm making here is, this behavior is not viewed as a bug, or a bit odd. This has been intentionally implemented in order to reconcile the differences within a peer dependency conflict and adheres to the design choices that were made and formally agreed upon for the `npm` cli. If you'd like to know more about the motivation behind the design choices made to solve peer dependency conflicts, feel free to to checkout the rfc's on [installing peer dependencies](https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md) and [handling peer dependency conflicts](https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md). If you'd like to be apart of influencing the established behavior of the cli, feel free to open an [rfc issue here](https://github.com/npm/rfcs/issues).
