### ISSUE TITLE
[BUG] 10.8.3 does not publish workspace packages when package-spec is a path to a workspace root

### ISSUE THREAD

**Issue by everett1992** [npm/cli#7771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm publish --workspaces` does not publish workspace packages when the package-spec argument is a path to a workspace root. It prints a warning 
> npm warn Ignoring workspaces for specified package(s)

and only publishes the workspace root. If the package-spec argument is omitted, or exactly `.` the root and it's workspaces will be published. This is a change from npm <=10.8.2 where `npm publish .`, `npm publish $PWD`, and `npm publish` appeared to be equivalent. 

### Expected Behavior

I expect the behavior of npm <=10.8.2, it's surprising that providing the current directory as an argument is different from passing `.` or omitting the argument.

### Steps To Reproduce

# Setup
```
# package.json
{
  "name": "root",
  "version": "1.0.0",
  "workspaces": ["sub"]
}

# sub/package.json
{ "name": "sub", "version": "1.0.0" }
```

# 10.8.3 does not publish workspace sub projects
```
$ npx npm@10.8.3 publish "$PWD" --dry-run --workspaces --include-workspace-root
npm warn Ignoring workspaces for specified package(s)
+ root@1.0.0
```

# 10.8.2 does

```
npx npm@10.8.2 publish "$PWD" --dry-run --workspaces --include-workspace-root
+ root@1.0.0
+ sub@1.0.0
```

### Environment

- npm: 10.8.3
- Node.js: 20.17.0
- OS Name: Ubuntu
- System Model Name: N/A
- npm config: N/A

**Comment by milaninfy** [comment]
@everett1992 In 10.8.2 it was not considering package spec when the command ran with workspace mode as per my understanding, but when you mentioned "$PWD" or any spec for that matter with workspaces and workspace root what exactly are you expecting to happen ?

**Comment by everett1992** [comment]
I expected `npm publish /path/to/package` to be the same as `cd
/path/to/package && npm publish`, or `npm publish .` and `npm pubish` when
the current working directory is /path/to/package. As far as I can tell
that was the behavior of npm 8 and 10 up to 10.8.3, and it matches how I
understand the description in [the docs](https://docs.npmjs.com/cli/v10/commands/npm-publish)

A package is interpreted the same way as other commands (like npm install)
and can be:
-   a) a folder containing a program described by a package.json file


I can work around this change, but it broke our CI workflow as it only published the root package.

**Comment by milaninfy** [comment]
@everett1992 You are right in your explanation. It should work the same and it is working the same if I understand the issue report currently. 

Here is the example.. I have `rep/cli/workspaces/*pkgs*`
checkout below command which I ran and it correctly picks up the `libnpmpublish` folder deep within cli workspaces. 
```sh 
~/workarea/rep $ npm publish cli/workspaces/libnpmpublish --dry-run 
npm notice
npm notice 📦  libnpmpublish@9.0.9
npm notice Tarball Contents
npm notice 717B LICENSE
npm notice 4.5kB README.md
npm notice 97B lib/index.js
npm notice 9.7kB lib/provenance.js
npm notice 7.2kB lib/publish.js
npm notice 3.3kB lib/unpublish.js
npm notice 1.7kB package.json
npm notice Tarball Details
npm notice name: libnpmpublish
npm notice version: 9.0.9
npm notice filename: libnpmpublish-9.0.9.tgz
npm notice package size: 8.9 kB
npm notice unpacked size: 27.2 kB
npm notice shasum: cf6ada45e6efbacdd8c9f62474502572d771ff28
npm notice integrity: sha512-Y35DuyMxAA/QR[...]ZrZg5ID9aDbiw==
npm notice total files: 7
npm notice
npm warn This command requires you to be logged in to https://registry.npmjs.org/ (dry-run)
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access (dry-run)
+ libnpmpublish@9.0.9
``` 

I believe that's what is happening when you run your command `npx npm@10.8.3 publish "$PWD" --dry-run --workspaces --include-workspace-root` here whatever is at`$pwd`, only that is getting published and it's ignoring workspace config since you explicitly provided package-spec. 

Till 10.8.2 
`npx npm@10.8.2 publish "$PWD" --dry-run --workspaces --include-workspace-root`  was equivalent to 
`npx npm@10.8.2 publish  --dry-run --workspaces --include-workspace-root`  which lead to a bug of not considering pacakge-spec when package is inside a workspace package or command ran with workspace config.  
Current behaviour matches how `pack` works.
