### ISSUE TITLE
[BUG] I have published a package currently, but unable to view README.md in npm registry ,but visible in github, and searching my package doesn't show it 

### ISSUE THREAD

**Issue by sahad0** [npm/cli#7967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Unable to view README.md in npm registry ,but visible in github.
[https://www.npmjs.com/package/react-native-draggable-sections](https://www.npmjs.com/package/react-native-draggable-sections)

Am i missing something ? searching my package also doesnt work

### Expected Behavior

Readme should be visible

### Steps To Reproduce

[https://www.npmjs.com/package/react-native-draggable-sections](https://www.npmjs.com/package/react-native-draggable-sections)

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by stronk-dev** [comment]
[Same here](https://www.npmjs.com/package/@stronk-tech/react-librespot-controller). Issue seems to have started after the maintenance on 2024-12-08.

The `README.md` exists in the NPM code section, but the NPM Readme section displays `This package does not have a README. [Add a README](https://docs.npmjs.com/about-package-readme-files) to your package so that users know how to get started.`

```
❯ Environment
npm: 10.8.3
Node.js: v22.9.0
OS Name: macOS 15.1 24B83 arm64
System Model Name: Apple M3 Max
```

**Comment by milaninfy** [comment]
**Closing:** this looks to be an issue with the registry which is outside the scope of this repo. For registry support please go to [npmjs.com/support](https://www.npmjs.com/support). If you believe this is a bug with the cli, please provide further clarifying details.
