### ISSUE TITLE
could not be a bug, may be a performance issue reported.

### ISSUE THREAD

**Issue by Cecil0o0** [npm/cli#7999]
![image](https://github.com/user-attachments/assets/889e710c-5e5c-4846-90f4-8367397fa7bb)

As shown above, after I execute `npm i` for project's dependencies, my machine has a high-speed fan with a loudly sound, then I try to inspect and locate this, I found this process of `npm i` could require a 300% CPU which is a big usage.

If there some more information for me to track and locate for this issue, I have no idea about it and how to improve it now...

**Comment by milaninfy** [comment]
@Cecil0o0 Thanks for the report. This could be due to many reasons, Please refile the issue and fill out all the details of the issues template so that we'll know some details about environment, configs, reproduction steps etc.

Please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
