### ISSUE TITLE
[BUG] readable-stream v3.6.0 fixes prototype modification brittleness

### ISSUE THREAD

**Issue by ljharb** [npm/cli#824]
# What / Why
it uses the proper babel transform, so it’s now spec-compliant and not vulnerable to Object.prototype modification.

It'd be great to get this into a v6 release (esp since it's unlikely that v7 will use readable-stream).

(cc @mikemimik, per https://node-js.slack.com/archives/C0J6DJ4PL/p1581699856037300)

see https://github.com/nodejs/readable-stream/pull/428

**Comment by Sief6** [comment]
يستخدم تحويل بابل الصحيح ، لذلك أصبح الآن متوافقًا مع المواصفات وغير عرضة لتعديل Object.prototype.

سيكون من الرائع الحصول على هذا الإصدار v6 (esp لأنه من غير المحتمل أن يستخدم الإصدار v7 الدفق القابل للقراءة).

( ccmikemimik ، لكل https://node-js.slack.com/archives/C0J6DJ4PL/p1581699856037300 )

##### Edit (from @mikemimik): 

> Created from translate.google.com

Correct Babylon conversion is used, so it's now compliant with specifications and not subject to modifying Object.prototype.

It would be nice to have this v6 version (esp because v7 is unlikely to use readable stream).

**Comment by Sief6** [comment]
يستخدم تحويل بابل الصحيح ، لذلك أصبح الآن متوافقًا مع المواصفات وغير عرضة لتعديل Object.prototype.

سيكون من الرائع الحصول على هذا الإصدار v6 (esp لأنه من غير المحتمل أن يستخدم الإصدار v7 الدفق القابل للقراءة).

( ccmikemimik ، لكل https://node-js.slack.com/archives/C0J6DJ4PL/p1581699856037300 )

**Comment by darcyclarke** [comment]
Closing as this should/would have gotten fixed in [`6.14.0`](https://github.com/npm/cli/releases/tag/v6.14.0)
